### ISSUE TITLE
Variations/Swatches Giving Error on all swatches after #2

### ISSUE THREAD

**Issue by tlctara** [woothemes/woocommerce#10272]
I am getting "Sorry, no products matched your selection. Please choose a different combination." for any swatch selected after the second one in the group. I am using the variation swatches and photos extension for WooCommerce. 
You can see the error here: http://castlegoods.com/product/girl-burp-cloths/
This began occurring after the latest update on 2/1/16 to version 2.5.2. I tried activating default twenty-fifteen theme and this did not solve the problem.
Screenshot:
https://www.dropbox.com/s/md2aoecazw8hnhv/Screenshot%202016-02-04%2010.12.05.png?dl=0

**Comment by mikejolley** [comment]
@lucasstark https://github.com/woothemes/woocommerce/commit/5f52a4e77ca4591af09fab99c2d3824c4e3645aa Would this do it?

**Comment by lucasstark** [comment]
@tlctara What version of Variation Swatches and Photos do you have?   That should not occur, since in the most recent version of Variation Swatches and Photos options which are unavailable are disabled, even when AJAX variations are triggered.

**Comment by tlctara** [comment]
I am using 2.1.0.


Tara Claeys
Design TLC, LLC
703-981-3588
[image: http://www.designtlc.com] <http://www.designtlc.com>

**Comment by tlctara** [comment]
The swatches are available ... if you go to the link http://castlegoods.com/product/girl-burp-cloths/ and click any swatch after the second one, the error appears. @mikejolley I am not sure what you are suggesting for me to do... 
Thank you!

**Comment by lucasstark** [comment]
@tlctara Why are the variations unavailable?   Are they out of stock, don't have a price configured, or simply are not available in those combinations?

**Comment by tlctara** [comment]
They ARE available. That is the issue. They are showing as not available when they are.

**Comment by mikejolley** [comment]
You may want to check they are in stock - 2.5.1 had an issue where it would enable stock management on save, even if unintended.

**Comment by tlctara** [comment]
All are showing in stock. Try the butterfly - screenshot attached. https://www.dropbox.com/s/x8gpz2ex6oidtsn/Screenshot%202016-02-04%2010.43.22.png?dl=0

**Comment by mikejolley** [comment]
@tlctara were you running 2.5.x before, or did you jump?

Have you disabled swatches to see if the regular variation form does the same thing?

Can you screenshot all variations, or see if you have an 'any' 'any' variation setup?

**Comment by tlctara** [comment]
I am in the process of restoring to pre 2.5.2 on my staging server to see if that fixes it.
I have not disabled swatches - will try that after backup restore if that does not fix it.
Interestingly, this is also happening on the Boy Burp Cloth page, but NOT on all pages with swatches applied (see receiving blankets and bibs), so may have something to do with the larger number of swatches for these 2 products? It was working a week or so ago, so I have assumed it is related to the update.
Here is a screenshot of all variations. blob:http%3A//castlegoods.com/71fa3ed2-720a-41b7-8277-75cec9a9725a

**Comment by mikejolley** [comment]
Broken link.

**Comment by tlctara** [comment]
Include the whole thing with blob in front 

Tara Claeys 
Design TLC, LLC
703-981-3588
http://www.designtlc.com




On Thu, Feb 4, 2016 at 7:57 AM -0800, "Mike Jolley" <notifications@github.com> wrote:












Broken link.

**Comment by mikejolley** [comment]
Nope...

**Comment by tlctara** [comment]
[blob:http%3A//castlegoods.com/71fa3ed2-720a-41b7-8277-75cec9a9725a
]
(blob:http%3A//castlegoods.com/71fa3ed2-720a-41b7-8277-75cec9a9725a)
This link works for me - it is a narrow and long

**Comment by mikejolley** [comment]
Chrome/safari won't show it. Can you just share it from dropbox or something?

**Comment by tlctara** [comment]
![castlegoods-screenshot](https://cloud.githubusercontent.com/assets/9441744/12821435/789a7fe8-cb31-11e5-8c16-09dbc54cdffe.png)

https://www.dropbox.com/s/394vp612kh6091e/castlegoods-screenshot.png?dl=0

**Comment by tlctara** [comment]
Backup restore on staging site confirms this is issue with update.http://staging1.castlegoods.com/
This backups is running WooCommerce 2.5.1 and WordPress 4.4.1

**Comment by mikejolley** [comment]
There is only 1 page pictured. Just go through those variations and see if you have a variation setup where 'design' is set to 'any' rather than an option.

The only change in core was to that variation file, using `preventDefault` instead of `return false`. If you could confirm whether or not swatches is causing it, or if it happens with the default variation form that would help.

**Comment by tlctara** [comment]
As noted, reverting to WP 4.4.1 and Woo 2.5.1 solves the issue. The settings within the products have not changed. It is only happening on two products, both of which have over 30 swatches/variations. Products with fewer variations are working fine. I have set the max_input_vars a while ago to accommodate the over 30 swatches as recommended here https://docs.woothemes.com/document/woocommerce-color-and-image-swatches/, and this was working fine before the update.
I am happy to share admin settings if you want to troubleshoot. Since the pre-update version is working, I continue to think this is a bug with the update.

**Comment by mikejolley** [comment]
Right; if you'd just deactivate swatches and confirm that will save me needing to create a test environment just for this. It would take you 2 mins to check.

**Comment by tlctara** [comment]
Ok - sorry I missed that. I just deactivated and get the message even without swatches plugin active. So what does that mean?

**Comment by mikejolley** [comment]
That means I have no idea, because if you compare 2.5.1 to 2.5.2 there are no changes to that part of core :)

**Comment by lucasstark** [comment]
@tlctara I see that you have the swatches still enabled on both the live and staging site.  Can you disable the plugin for a short while so we can verify if the issue is in WooCommerce, or in WooCommerce Variation Swatches, or with how the variations themselves might be configured?

**Comment by tlctara** [comment]
This is very odd! Argh. 
OK, deactivated swatches plugin on live and staging.
Here is an oddity to note: if you select "Girl Dress" you get no error, if you select "Groovy Flowers" you DO get the error. Looking at set up for both in variations, they are identical - both in variations and swatches set up

**Comment by mikejolley** [comment]
Managed to reproduce it with a text attribute containing spaces.

**Comment by mikejolley** [comment]
Although, its happening on 2.4 and 2.5 so I don't see how 2.5.1 would work. Rolling back to test some more.

**Comment by lucasstark** [comment]
@mikejolley It does not work on her stage site either, whichever version that is at.

**Comment by mikejolley** [comment]
@lucasstark Yeah, 2.5.1 is the same. As is 2.4. So this must have been long standing unless the attribute was edited recently.

**Comment by tlctara** [comment]
thanks. Webhost did some server work recently. Perhaps that is the issue. It looked like it was working on the staging site when I tested there an hour ago but now see the error. How bizarre and frustrating. Sorry to pester you! Seems like a glitch somewhere.

**Comment by tlctara** [comment]
Argh. This is pointing to a server issue after all. If this is Site Ground I am so sorry to have bothered you. Thank you for your patience and attention.

**Comment by mikejolley** [comment]
Okay. I know whats causing it.

@claudiosmweb I think this is one you'd best tackle for 2.5.3.

When you save variations, if the attribute is left set as 'any', the meta key/value is not set. If the meta value is not set, the query within `get_matching_variation()` does not match the variation. meta key needs to exist.

I think your variation save script doesn't set this data because 'any' has no value.

To reproduce:

- Set woocommerce_ajax_variation_threshold to 0
- Create variable product
- Add 2 attributes.
   - One called 'design'
   - One called 'personalization'
- Add several random values to each attribute
- For each variation, set the design attribute, but leave personalization to 'any'. Give each a price etc.
- Save. View product. Works.
- Now edit the product and rename personalization to personalization-2
- Save variations
- Save product
- No longer matches. No meta is set for each variation named personalization-2

**Comment by tlctara** [comment]
Wow. Thanks! So I am not crazy. Is there a fix for this site in the meantime without redoing everything?

**Comment by mikejolley** [comment]
Did you rename the personalisation attribute? If so, change it back and save.

**Comment by lucasstark** [comment]
@mikejolley @tlctara Another potential workaround is to create the attribute as a global product attribute rather than a custom product attribute.   Remove your custom product attribute and change it to the global one.   

You'll have to relink the variations, but that should get you going until they have a chance to patch it.

**Comment by mikejolley** [comment]
I have a workaround. Will commit in a sec.

**Comment by mikejolley** [comment]
Try that patch on 2.5.2 ^

**Comment by mikejolley** [comment]
@tictara let me know if you give it a try.

**Comment by tlctara** [comment]
Thanks @mikejolley ... I was out at a meeting all afternoon. I am not clear on what you want me to do. You mean create all 60+ designs as separate attributes within their own attribute group under the main WooCommerce Settings Menu? ... Instead of the list I have inside the individual Girl and Boy Burp Cloth Product page. Screenshots: 
https://www.dropbox.com/s/657bdvs8qaheanx/Screenshot%202016-02-04%2017.31.36.png?dl=0
https://www.dropbox.com/s/4yvgkuwyznw65pj/Screenshot%202016-02-04%2017.32.12.png?dl=0
https://www.dropbox.com/s/ilczuztum1udcxc/Screenshot%202016-02-04%2017.33.53.png?dl=0

.... or is there a patch I am supposed to use?

Seems very tedious to have to do so want to make sure that is what you are saying before I proceed.
Thanks

**Comment by mikejolley** [comment]
Patch above.

**Comment by mikejolley** [comment]
Closing as it seems resolved by the patch I submitted.

**Comment by tlctara** [comment]
I am still having the issue. I edited the
includes/class-wc-product-variable.php file with the patch.


Tara Claeys
Design TLC, LLC
703-981-3588
[image: http://www.designtlc.com] <http://www.designtlc.com>

**Comment by tlctara** [comment]
http://castlegoods.com/product/girl-burp-cloths/

I am ALSO supposed to do the global attributes? That is going to take some time to rework if necessary so don't want to proceed until I confirm.

**Comment by tlctara** [comment]
Never mind --- it is working! Thanks!


Tara Claeys
Design TLC, LLC
703-981-3588
[image: http://www.designtlc.com] <http://www.designtlc.com>
