### ISSUE TITLE
WC_Session_Handler subject to race conditions

### ISSUE THREAD

**Issue by psprindys** [woothemes/woocommerce#11062]
Current session handler implementation is subject to race conditions.

Session data is read at the beginning of each request and stored in memory under `$this->_data`. Any changes made to session during the lifetime of the request are made to the original `$this->_data` only. All changes to `$this->_data` are permanently stored on shutdown. If two or more requests that modify session data happen at about the same time, some changes may not be preserved.

If WC sessions are not supposed to be used by extensions, then it may be fine, you know what you are doing. However, if developers are expected to make use of it, then they may (and some will) run into issues.

I observed this when working on Ajax multiple file upload implementation that stores file meta data in WC session temporarily. When I tested it with multiple small files, only the last one had any data present in WC session.

**Comment by psprindys** [comment]
This could potentially be solved by changing method `set()` to do the following:
1. Read session data from the database (not from cache) and issue a row lock in the same query
2. Add new value to `$this->_data`
3. Write updated `$this->_data` data to the database and issue a lock release in the same query

This can be made optional by adding a third parameter to `set()` with default value false that would indicate that race conditions need to be prevented. Regular queries would have no performance penalty then.

**Comment by psprindys** [comment]
I withdraw my suggestion to use row level locking since not all WP-compatible database engines support that.

Alternative locking system could be similar to [this Semaphore implementation](https://github.com/crowdfavorite/wp-social/blob/master/lib/social/semaphore.php). Single WP option could be used to store lock status and single SQL query "set to locked if not yet locked" could be executed to acquire lock (counts affected rows to see if lock is acquired). The only thing that I changed from the aforementioned Semaphore implementation is that I went with having one option named `session_is_locked` and then changing its value from `0` to `1` instead of changing option name from "locked" to "unlocked" which sometimes resulted in InnoDB deadlocks (did not spend time investigating the actual cause).

Method `set()` could look something like this:

    /**
     * Set a session variable.
     *
     * @param string $key
     * @param mixed $value
     * @param bool $locking
     */
    public function set( $key, $value, $locking = false ) {

        // Value already exists
        if ( $value === $this->get( $key ) ) {
            return;
        }

        // Optional session locking
        if ( $locking ) {

            // Attempt to lock session
            if ( ! $this->lock() ) {
                return false;
            }

            // Get session data from database
            if ( $this->has_session() ) {
                // SQL query here to read session data directly from the database (not from cache) and assign it to $this->_data
            } else {
                $this->_data = array();
            }
        }

        $this->_data[ sanitize_key( $key ) ] = maybe_serialize( $value );
        $this->_dirty = true;

        // Optional session locking
        if ( $locking ) {

            // Update session data in database
            // SQL query here to insert/update session data directly in the database so that another set() request gets new data

            // Release lock
            $this->unlock();
        }
    }

Proposed method `lock()` may need to wait for the lock to be released by another process. This is similar to SQL queries that wait in a queue when a table or row is locked. Not so elegant solution but does the job:

    /**
     * Lock session for writing
     *
     * @param int $wait_time
     */
    public function lock( $wait_time = 5 ) {

        $started = time();

        while ( time() < ( $started + $wait_time ) ) {

            // Attempt to acquire lock
            if ( $this->lock_attempt() ) {
                return true;
            }

            // Sleep for 100 ms
            usleep( 100000 );
        }

        return false;
    }

This is still susceptible to new values overwritten by requests that do not set `$locking` to `true` and happen at the same time though. Use of locking when writing to session could be made mandatory too to solve this but this need to be weighted against performance costs.

**Comment by statik-jos** [comment]
We also encountered this problem.

Have a look at the above pull request to see a possible reduction of this problem.
In the case of the psprindys, my fix probably will not work. As I don't expect it to prevent multiple concurrent requests changing the cart.
So, I admit, this is a stopgap measure. The proposed solution above, has more of a performance impact IMHO, but is more thorough and would fix our issue as well.

I would argue, though, that this is too big a problem to fix in 2.7
I would suggest putting this temporary fix in version 2.6.2 and 2.5.6, so merchants don't lose purchases because of this.
And on the flipside, as a customer, I would be suspicious to pay on a site which seems a bit flaky in remembering what I put in my cart.

I would like to add my findings while researching this bug.

Our use case:
- concurrent requests that don't modify the cart, but can potentially save a stale cart.
- one request at a time that modifies the cart (add a product, change quantities, etc).

In one instance we had a 404 CSS file on the page. This was the perfect flaw to expose this bug.
It seemed the browser would start loading the CSS file before the cart modify request would save the cart in the database.
The CSS file would trigger the 404 page, which retrieves the cart on request start and saves the cart on request shutdown.
This was the perfect sequence of events to almost always get a stale cart.
In this instance it was almost impossible to add an item to the cart (~90% failure rate).

Next we removed the 404 CSS file and failure rates dropped dramatically.
But still in ~10% of the time the cart modify request would get clobbered by other requests.
Especially multiple tabs and ajax requests would increase the chance of the cart getting clobbered.

Now after the above PR in place, I can't seem to get a failure.
My debugging info also shows the session saves are reduced to only the cart modifying requests.

The only caveat I've found is the cart page itself, it changes some totals in the cart which subsequent non-modifying requests seem to reset.
This causes these non-modifying requests to save the session and potentially put a stale cart in the database, again.
Though I haven't encountered this yet, I would expect it to be a possibility.

**Comment by mikejolley** [comment]
https://github.com/woothemes/woocommerce/pull/11269

**Comment by statik-jos** [comment]
Although this issue is closed and a fix is merged, it does not address the specific problem for which psprindys started this issue.

My previous PR reduced the faulty data dramatically in our shop when doing one cart-modify action at a time. Naively I thought multiple requests modifying the cart simultaneously would be edge cases and would not occur often.

Now we noticed that the basket gets overwritten when we use ajax to modify the cart from the product overview page in rapid succession.
So when using ajax and modifying the cart it's a lot more common for the cart to get overwritten with stale data.

To solve this we need a more substantial solution.

The suggested locking mechanics would be nice to have, but with this we are recreating some database functionality (I think the I in ACID).

To go fully blown I personally would like to have an event based cart, capturing the intent of the user instead of the resulting state.
With such an implementation, we could ask the database, for example, who put product A in their cart, but subsequently removed it and put product B in the cart before proceeding to checkout.
This would allow for some powerful marketing tools to be developed.

These features are maybe to hairy to develop in a timely fashion.
So maybe we should just retrieve the session from the DB when we try to change it (WC_Session->set()), change it and immediately sync it back to the database.
This way we keep the collision time to a few ms instead of 1-2s (on a slow host), but we do introduce some extra database traffic.

**Comment by userabuser** [comment]
@statik-jos I can confirm that race conditions are still an issue with AJAX based add-to-cart requests (in quick succession) and perhaps in other areas too.
