### ISSUE TITLE
Update order via API adding new line items

### ISSUE THREAD

**Issue by amjad0** [woothemes/woocommerce#11450]
When I try to update an order via the API by sending in new line items, I get this error: 

```
{
  "errors": [
    {
      "code": "woocommerce_invalid_item_id",
      "message": "Order item ID provided is not associated with order"
    }
  ]
}
```

because its a PUT request and also because the new line item does not have an id associated with it. Is this is a limitation because this is a show stopper for us not being able to update an order. Existing line items update fine but we are not able to delete them as well (i.e. make quantity as 0 for example)

I know the workaround is to delete and create new order but that way we will loose the order number.

**Comment by claudiosmweb** [comment]
Fixed in https://github.com/woothemes/woocommerce/commit/8f62c322dde7c5d5df3cacc97d9163b9df65b197

**Comment by amjad0** [comment]
@claudiosmweb ... you the best bro! I will test it out and post my results here.

**Comment by amjad0** [comment]
@claudiosmweb Unfortunately, that does not fix this. I am trying to add new line items to an pending order. 

![screen shot 2016-07-16 at 1 42 56 am](https://cloud.githubusercontent.com/assets/1428634/16893222/c894f6dc-4af6-11e6-8e7d-f94bd2f38317.png)

**Comment by amjad0** [comment]
@claudiosmweb this issue is still not resolved.

**Comment by claudiosmweb** [comment]
@amjad0 Sorry, My fix is for other thing. But I just tested and it works fine. If you are getting this message is because there is no order item with that ID.

**Comment by amjad0** [comment]
@claudiosmweb So how can I update a pending order by adding new line items or removing line items to it via the API?

**Comment by claudiosmweb** [comment]
You can add new or update (in this case using the correct line item ID), but not possible to remove right now.

**Comment by amjad0** [comment]
@claudiosmweb So in this case I am adding a new line item (product 762) what line item ID do I put there? Aren't line item ID's auto generated when creating the order? Here I am updating the order.

**Comment by amjad0** [comment]
the line item id 758 in this example was auto generated when I created the order as a pending order in the first place. Now when I want to add new line items it asks for line item id which the new line items don't have. 

I know we can provide line item id for those which already have line item ids. So that means for adding new line items to an order how can it be done without line item id?

I hope you understand my question! :)

**Comment by claudiosmweb** [comment]
I understand what you are doing and theoretically it's all right.
But if is showing this message is because you are using a incorrect item line ID.
Maybe you get an order and trying to update other order with the same item line ID.

**Comment by claudiosmweb** [comment]
This message comes from here: https://github.com/woothemes/woocommerce/blob/ed08e51ddb1788eaa0a3266e099c0b886363cfa0/includes/api/legacy/v3/class-wc-api-orders.php#L876-L887

**Comment by amjad0** [comment]
@claudiosmweb

does not work. it always requires line item id to update an order. I am unable to add a new line item to an existing order. :( 

The only workaround is to delete the order and create again but then I lose the order number.

**Comment by claudiosmweb** [comment]
@amjad0 have you read the query?
There is no error, if you are using an item ID that don't belongs for the order, you'll see that error.

**Comment by amjad0** [comment]
Yes I read it. The problem is there is no item id to use so I cannot use any wrong item id. The new item I am trying to add has no item id! If its an existing line item, it has an item id. But a new one does not. 

Is the line item id unique to each item or does it keep incrementing?

**Comment by amjad0** [comment]
@mikejolley I'd like to get your input as well bro. This things got us stumped.

**Comment by amjad0** [comment]
Steps to recreate the issue:

All tasks are done via the REST API.

1. Create a new order with pending status and add products A & B. 
2. Update the same order to add product C. <-- not working

**Comment by claudiosmweb** [comment]
@amjad0 ohh I understand what you mean.
Just use `id` as `null` for add new ones:

```json
{
  "id": null,
  "product_id": 762,
  "quantity": 1
}
```

**Comment by claudiosmweb** [comment]
This last commit will make more easy, since don't requires to send the `"id": null,` now.

**Comment by amjad0** [comment]
My bad for not following the steps to post a new issue. But I'm glad you got it. Thank you @claudiosmweb :)

**Comment by gijoecodes** [comment]
I'm attempting to update an order according to the documentation as shown here: http://woocommerce.github.io/woocommerce-rest-api-docs/#update-an-order. When updating the quantity of a line item that is currently in the order, the order is updated. When adding new line items, the response is.


"code":"woocommerce_rest_invalid_item_id",
"message":"Order item ID provided is not associated with order."

It is my understanding that line items ids are generated automatically when the order is process therefore when adding new line items I do not include the id for that new item. This was change from a few years ago when null was required as the value for id as described here: https://github.com/woocommerce/woocommerce/issues/11450#issuecomment-233696284. 

Adding additional line items to the order was working up to a month or two ago by simply not including the line item id. I can't find where I read that solution.

          "line_items" : [
            {
              "id" : 140,
              "product_id" : 250,
              "quantity" : 3,
              "sku" : "",
              "subtotal" : "777.0",
              "price" : "259",
              "variation_id" : 0,
              "tax_class" : "",
              "meta_data" : [],
              "total" : "777.0"
              "name" : "Chair"
            },
            {
              "product_id" : 238,
              "quantity" : 1,
              "sku" : "",
              "subtotal" : "267.0",
              "price" : "267",
              "variation_id" : 0,
              "tax_class" : "",
              "meta_data" : [],
              "total" : "267.0",
              "name" : "Table"
            }
          ],

How can I update an order by adding additional line items using with a PUT request to the WooCommerce REST API?
