### ISSUE TITLE
Spurious database errors

### ISSUE THREAD

**Issue by WillBrubaker** [woothemes/woocommerce#37095]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

With the HPOS feature not enabled (default WooCommerce installation), database errors are thrown when visiting the "Tools" tab of the status screen.

Also see https://wordpress.org/support/topic/getting-database-error-wp_wc_orders-table-doesnt-exist/ and https://wordpress.org/support/topic/table-bd-wpgq_wc_orders-doesnt-exist/

### Expected behavior

For database errors to not be thrown

### Actual behavior

Database errors are thrown

### Steps to reproduce

1. Visit WooCommerce > Status > Tools
2. View the database error log. Alternatively, use a tool such as Query monitor to view database errors.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://testsite.local
Site address (URL): https://testsite.local
WC Version: 7.4.1
REST API Version: ✔ 7.4.1
WC Blocks Version: ✔ 9.4.4
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.43 (Unix)
PHP Version: 7.4.30
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 7.84.0
(SecureTransport) OpenSSL/1.1.1q

SUHOSIN Installed: –
MySQL Version: 8.0.16
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.4.1
WC Database Prefix: wp_
Total Database Size: 86.54MB
Database Data Size: 45.78MB
Database Index Size: 40.76MB
wp_woocommerce_sessions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.34MB + Index: 0.66MB + Engine InnoDB
wp_woocommerce_order_items: Data: 1.52MB + Index: 0.50MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 11.52MB + Index: 12.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fakenames: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_actionscheduler_actions: Data: 1.02MB + Index: 1.16MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 1.02MB + Index: 2.03MB + Engine InnoDB
wp_afwc_campaigns: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_afwc_commission_plans: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_afwc_hits: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_afwc_payout_orders: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_afwc_payouts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_afwc_referrals: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_abandoned_carts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_customer_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_customers: Data: 0.14MB + Index: 0.31MB + Engine InnoDB
wp_automatewoo_events: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_guest_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_guests: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_automatewoo_log_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 1.52MB + Index: 0.72MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 7.05MB + Index: 0.09MB + Engine InnoDB
wp_postmeta: Data: 10.52MB + Index: 10.03MB + Engine InnoDB
wp_posts: Data: 1.52MB + Index: 0.78MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 2.52MB + Index: 5.03MB + Engine InnoDB
wp_users: Data: 0.14MB + Index: 0.17MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_bookings_availability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availabilitymeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.23MB + Index: 0.17MB + Engine InnoDB
wp_wc_deposits_payment_plans: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_deposits_payment_plans_schedule: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_composite_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 2.52MB + Index: 5.00MB + Engine InnoDB
wp_wc_order_stats: Data: 0.45MB + Index: 0.44MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_gc_activity: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_gc_cards: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_gc_cardsmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_flat_rate_boxes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_square_customers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

af_dis_cart_rule: 1
attachment: 47
aw_workflow: 1
bookable_resource: 1
customize_changeset: 3
event_ticket: 2
event_ticket_email: 3
nav_menu_item: 6
not: 1
page: 17
post: 5
product: 34
product_variation: 62
revision: 15
shop_order: 4086
shop_order_refund: 1
shop_subscription: 18
wc_booking: 4
wc_order_status: 9
wcpf_item: 4
wcpf_project: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (11) ###

Query Monitor: by John Blackbourn – 3.11.2
AutomateWoo: by WooCommerce – 5.6.8
BTCPay Server Donations: by Your Name – 1.0
My Template Overrides: by Hiro – 0.1b
Testing various code snippets: by Will    Brubaker – 1.0
WooCommerce All Products For Subscriptions: by WooCommerce – 4.0.4
WooCommerce Bookings: by WooCommerce – 1.15.75
WooCommerce Stripe Gateway: by WooCommerce – 7.1.0
WooCommerce Square: by WooCommerce – 3.6.1
WooCommerce Subscriptions: by WooCommerce – 4.9.1
WooCommerce: by Automattic – 7.4.1

### Inactive Plugins (22) ###

Affiliate For WooCommerce: by StoreApps – 6.3.1
Box Office Ticket Email Fixer Upper: by Hiro – 0.1b
Facebook for WooCommerce: by Facebook – 3.0.13
Gutenberg Examples: by the Gutenberg Team – 1.1.0
Order Simulator for WooCommerce: by 75nineteen Media LLC – 1.0.2
Order Status Change Update Backtrace Logger: by Hiro – 0.1b
Product Category Update Logger: by Hiro – 0.1b
Product Filters for WooCommerce: by WooCommerce – 1.4.1
Proxy HTTP requests: by Hiro – 0.1b
Smart Manager - WooCommerce Advanced Bulk Edit, Inventory Management & more...: by StoreApps – 7.4.0
Subscription Creation Backtrace Logger: by Hiro – 0.1b
WooCommerce Australia Post Shipping: by WooCommerce – 2.5.0
WooCommerce Box Office: by WooCommerce – 1.1.48
WooCommerce Brands: by WooCommerce – 1.6.43
WooCommerce Deposits: by WooCommerce – 2.1.3
WooCommerce Flat Rate Box Shipping: by WooCommerce – 2.2.0
WooCommerce Gift Cards: by WooCommerce – 1.15.2
WooCommerce Min/Max Quantities: by WooCommerce – 4.0.7
WooCommerce Order Status Manager: by SkyVerge – 1.14.0
WooCommerce Product Add-ons: by WooCommerce – 6.1.1
WooCommerce Smooth Generator: by Automattic – 1.0.4
WP Crontrol: by John Blackbourn & crontributors – 1.15.1

### Dropin Plugins (1) ###

db.php: Query Monitor Database Class (Drop-in)

### Must Use Plugins (2) ###

My Muplugin: by Ghost in the machine – 1.0
WP Migrate Lite Compatibility: by Delicious Brains – 1.3

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: booking (booking)
composite (composite)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: ✔
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Shop base: #7 - /shop/
Cart: #8 - /cart/
Checkout: #9 - /checkout/
My account: #10 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 4.2.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://testsite.local/
Subscriptions-core Library Version: 5.4.0
Subscription Statuses: wc-active: 9
wc-pending: 2
wc-on-hold: 2
wc-cancelled: 5

WooCommerce Account Connected: ✔ Yes
Active Product Key: ❌ No
Report Cache Enabled: ✔ Yes
Cache Update Failures: ✔ 0 failure

### Store Setup ###

Country / State: United States (US) — Delaware

### Subscriptions by Payment Gateway ###

Stripe: wc-on-hold: 1
wc-cancelled: 3
wc-active: 9

### Payment Gateway Support ###

Cash on delivery: products
Stripe: products
refunds
tokenization
add_payment_method
subscriptions
subscription_cancellation
subscription_suspension
subscription_reactivation
subscription_amount_changes
subscription_date_changes
subscription_payment_method_change
subscription_payment_method_change_customer
subscription_payment_method_change_admin
multiple_subscriptions

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
new-product-management-experience
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
product-variation-management
settings

Daily Cron: ✔ Next scheduled: 2023-03-08 06:19:22 +00:00
Options: ✔
Notes: 51
Onboarding: completed

### All Products for WooCommerce Subscriptions ###

Template Overrides: –

### Action Scheduler ###

Complete: 587
Oldest: 2023-02-05 22:09:20 +0000
Newest: 2023-03-07 06:50:12 +0000

Failed: 2
Oldest: 2023-01-06 00:01:53 +0000
Newest: 2023-03-02 00:49:01 +0000

Pending: 13
Oldest: 2023-03-07 07:19:55 +0000
Newest: 2023-04-06 23:43:22 +0000

### Status report information ###

Generated at: 2023-03-07 07:11:19 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by stoltzrx** [comment]
6006551-zen

**Comment by jorgeatorres** [comment]
After some research, I don't think we can fix this in WC core:

- When `wpdb` executes a `DESCRIBE` query to find out if a table exists and the table doesn't exist, an error is produced which `wpdb` then [adds to the global `$EZSQL_ERROR` array](https://github.com/WordPress/wordpress-develop/blob/b98b5e59d72a68bc31f99b866fa26f7769d16e97/src/wp-includes/class-wpdb.php#L1829-L1832). This is not a problem in and of itself, as with `suppress_errors`, `wpdb` doesn't log this to the error log nor outputs the error. This is the case with our calls to determine whether HPOS tables exist, as those always end up in `dbDelta()` and `dbDelta()` [does `suppress_errors()`](https://github.com/WordPress/wordpress-develop/blob/b98b5e59d72a68bc31f99b866fa26f7769d16e97/src/wp-admin/includes/upgrade.php#L2796-L2798) so shouldn't log nor output any error.
- Thing is, Query Monitor specifically [looks inside the `$EZSQL_ERROR` global](https://github.com/johnbillion/query-monitor/blob/e99ee362229fd749945faf51ce0756de90b9c430/collectors/db_queries.php#L247-L261) to collect errors, which are later displayed. This is independently of the `suppress_errors` value in `$wpdb`.

So, even though we're doing everything right and attempting to suppress errors when we should, QM will always log/display those failures. With QM disabled, no error is logged or output anywhere, so this looks like something QM-specific. Whether it is a feature or not, that's up for discussion.

As such, I'm closing this issue, but feel free to re-open if I've missed something in my brief research.

**Comment by johnbillion** [comment]
The underlying issue with Query Monitor being over-enthusiastic about showing this error has been fixed in version 3.12.3.

**Comment by Nick776** [comment]
@johnbillion 

John, we're still getting the error in the WP backend. Our configuration:

WordPress: current version
WooCommerce: current version
Query Monitor: current version

Do you need more information to get to the bottom of the error?

**Comment by johnbillion** [comment]
@Nick776 Please [open a support thread with all the information](https://wordpress.org/support/plugin/query-monitor/), including the query that's triggering the error. Thanks.

**Comment by Nick776** [comment]
@johnbillion 

already happened John. see the last entry from two weeks ago here:
https://wordpress.org/support/topic/fake-error-in-qm-in-combination-with-wp-wc/
