### ISSUE TITLE
Quantity max value not updated on change variation

### ISSUE THREAD

**Issue by tambaqui** [woothemes/woocommerce#37129]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The attributes of the quantity input field, min and max, are not updated when changing variation. 

The bug is located in the `VariationForm.prototype.onFoundVariation` method of the `assets/frontend/add-to-cart-variation.js` file.  Here, the $qty selector has changed, and instead of selecting the layer with the "quantity" class, as it did before, it selects the input:

`$qty = form.$singleVariationWrap.find( '.quantity input[name="quantity"]' ),`

For this reason the selection of the input, which is done later, does not work:

`var $qty_input = $qty.find( 'input.qty' )`

Since he is looking for himself ;)

For the later logic to work, the initial $qty selector must be changed to the way it was in the previous version, ie:

`$qty = form.$singleVariationWrap.find( '.quantity' ),`

### Expected behavior

Quantity input min and max attributes are updated on change of variance with stock restrictions.

### Actual behavior

The min and max attributes of the quantity input are NOT updated when changing variations with stock constraints, since the quantity input selector in the js file is incorrect.

### Steps to reproduce

1. Create a product with variations for some attribute.
2. Manage stock for variations with different stock limits.
3. In frontend, change attribute/variation option.
4. The quantity input does not take into account the stock restrictions of each variation

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://shop.local
Site address (URL): https://shop.local
WC Version: 7.4.1
REST API Version: ✔ 7.4.1
WC Blocks Version: ✔ 9.4.4
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.16.0
PHP Version: 8.0.22
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 7.84.0
(SecureTransport) OpenSSL/1.1.1q

SUHOSIN Installed: –
MySQL Version: 8.0.16
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.4.1
WC Database Prefix: wp_
Total Database Size: 42.85MB
Database Data Size: 40.32MB
Database Index Size: 2.53MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_duplicator_packages: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wp_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ewwwio_images: Data: 0.14MB + Index: 0.09MB + Engine InnoDB
wp_ewwwio_queue: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gdpr_cc_options: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 3.11MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 21.52MB + Index: 0.70MB + Engine InnoDB
wp_posts: Data: 14.52MB + Index: 0.30MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 46
customize_changeset: 2
dsalv: 1
elementor_library: 5
nav_menu_item: 9
page: 11
post: 1
postman_sent_mail: 1
product: 9
product_variation: 16
pscw-size-chart: 3
revision: 1339
size-chart: 11
wp_global_styles: 2
wpcf7_contact_form: 3

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (18) ###

EditorsKit: by Munir Kamal – 1.34.5
Contact Form 7: by Takayuki Miyoshi – 5.7.4
Custom Fonts: by Brainstorm Force – 1.3.7
Yoast Duplicate Post: by Enrico Battocchi & Team Yoast – 4.5
Duplicator: by Snap Creek – 1.5.2.1
Elementor: by Elementor.com – 3.11.2
EstadoDeRuido: by Raúl Solana – 1.0.1
EWWW Image Optimizer: by Exactly WWW – 6.9.3
Facebook for WooCommerce: by Facebook – 3.0.14
GDPR Cookie Compliance: by Moove Agency – 4.10.2
Advanced Linked Variations for WooCommerce: by theDotstore – 1.0.1
Maintenance: by WebFactory Ltd – 4.07
Post SMTP: by Post SMTP – 2.4.3
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.5
SVG Support: by Benbodhi – 2.5.5
Product Size Charts Plugin for WooCommerce: by theDotstore – 2.4.2
Variation Images Gallery for WooCommerce: by RadiusTheme – 2.2.7
WooCommerce: by Automattic – 7.4.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Shop base: #18 - /lookbook/
Cart: ❌ Page visibility should be public
Checkout: #20 - /checkout/
My account: #21 - /account/
Terms and conditions: #3 - /privacy-policy/

### Theme ###

Name: EstadoDeRuido
Version: 1.0.1
Author URL: https://tambaqui.es/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: shop/woocommerce/myaccount/form-edit-account.php

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
new-product-management-experience
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
product-variation-management
settings

Daily Cron: ✔ Next scheduled: 2023-03-09 14:04:01 +00:00
Options: ✔
Notes: 45
Onboarding: completed

### Action Scheduler ###

Complete: 36
Oldest: 2023-02-08 15:10:40 +0000
Newest: 2023-03-08 17:32:04 +0000

Failed: 1
Oldest: 2023-02-21 19:19:57 +0000
Newest: 2023-02-21 19:19:57 +0000

Pending: 1
Oldest: 2023-03-09 09:34:13 +0000
Newest: 2023-03-09 09:34:13 +0000

### Status report information ###

Generated at: 2023-03-08 17:34:36 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by jonathansadowski** [comment]
Hi @tambaqui,

Thanks for the report. This looks to me like it might be a duplicate of #36855, which was fixed with #36871, the release of which will be part of WooCommerce 7.5, which is currently slated for release on March 14.

I'm going to close this as a duplicate, but if there's something that I'm missing, please reply and let us know.

**Comment by tambaqui** [comment]
Ok, thanks @jonathansadowski. I don't see this change being included in the 7.5.0-rc.1 pre-release.

**Comment by jonathansadowski** [comment]
> Ok, thanks @jonathansadowski. I don't see this change being included in the 7.5.0-rc.1 pre-release.

Thanks @tambaqui... to clarify — you're still experiencing this issue with that RC? If so, I'll re-open this and we'll try and reproduce.

**Comment by tambaqui** [comment]
Hi @jonathansadowski, yes, I have downloaded and tested version 7.5.0-rc.1 and the problem persists here.
You can see it in the onFoundVariation method of assets/front/add-to-cart-variation.js file.

**Comment by helgatheviking** [comment]
This has been fixed as far as I can tell as of https://github.com/woocommerce/woocommerce/commit/2b4ed6fe03d366ead9d8c471c3f0a7e7666847af. But couldn't say if it's in the RC or not.

Can quickly test using:
```
function kia_test_variation_max( $available_variation ) {
	$available_variation['max_qty'] = 2;
	return $available_variation;
}
add_filter( 'woocommerce_available_variation', 'kia_test_variation_max' );
```
If the variations are limited to 2 max, then it's working.

**Comment by calyweb** [comment]
This has not been fixed on 7.5 released, still the same problem

and the code below does not work

 function kia_test_variation_max( $available_variation ) {
	$available_variation['max_qty'] = 2;
	return $available_variation;
}
add_filter( 'woocommerce_available_variation', 'kia_test_variation_max' );
![Capture d’écran 2023-03-14 à 17 14 55](https://user-images.githubusercontent.com/63538887/225070682-e57ec729-7cfe-47f2-a1e4-5ea113f46cc1.png)

**Comment by helgatheviking** [comment]
@calyweb the code is a quick way to demonstrate the problem... so if it's not working I think we can conclude that the https://github.com/woocommerce/woocommerce/commit/2b4ed6fe03d366ead9d8c471c3f0a7e7666847af was not included in the 7.5. I definitely think it should have been and imo would warrant a hotfix.

**Comment by calyweb** [comment]
I don't understand why it takes so much time for a big problem regarding the fact that it's a sell plugin, if the customer can add more quantity than it exists, it's a major bug, and it's present since 2 months now ...
I rollback to the 7.3

**Comment by seldimi** [comment]
Unfortunately, there was no fix.. Rollbacked to 7.3 as well.

**Comment by clustercis** [comment]
We can confirm that #36871 has not been included yet in the [7.5 branch](https://github.com/woocommerce/woocommerce/tree/release/7.5) and the 7.5.0 release.

@jonathansadowski @Konamiman Would you consider releasing a 7.5.1? The issue has been affecting our customer base as well.

**Comment by samueljseay** [comment]
Hey folks, just wanted to let you know we're going to do a fix release for this issue. Sorry for the inconvenience.

**Comment by ahawtin** [comment]
Thank you. Ended up holding our English site at 7.3 and patching the French site which was at 7.4. Looking forward to the update so we can get rolling again with latest releases.

**Comment by jonathansadowski** [comment]
Sorry that this wasn't included in 7.5.0. We've just released a 7.5.1 fix release which should address this issue.
