### ISSUE TITLE
Variable Product Attribute (first in list) not saving with WooCommerce 7.6

### ISSUE THREAD

**Issue by lynnjat7** [woothemes/woocommerce#37761]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

With version 7.6 of WooCommerce, when creating a Variable Product, the first Attribute in the list of Attributes is not saved (or is erased) if all attributes are set to "not used for variations", when the product is actually published.

If only one attribute has been added, and it is set to not used for variations, then publishing the product will remove that one.

This can also be seen when editing existing variable products. If all attributes are set to "not used for variations" and you change the detail on any one attribute, then Update, whatever the first attribute was in the list is erased.

### Expected behavior

When creating or editing a Variable product, you should be able to Attributes under the Product Data > Attributes Tab, and have each one added marked as "not used for variations" if you wish.

However, if all attributes are marked as "not used for variations", the first attribute set in the list mysteriously vanishes when the product is published.

### Actual behavior

For a newly created product in WooCommerce 7.6:
* add one or more Attributes (global or custom); mark all added attributes as NOT used for variations
* save attributes --> all looks well
* publish the product --> the first Attribute in the list vanishes and is not saved with the product

For an existing product, created in 7.6 or an earlier version of WooCommerce:
* if all attributes are already marked as NOT used for variations, edit any existing attribute and Update the product --> first attribute in the list of attributes vanishes and is permanently deleted from this product
* if any attributes were used for variations, uncheck them so they are now NOT used for variations, make an edit to any one attribute, and Update --> first attribute in the list vanishes and is permanently deleted from this product

### Steps to reproduce

1. Create a new product, and make it a Variable Product -> add a price.
2. Under the Attributes tab, add an attribute (can be global or custom).
3. Mark this attribute set as "not used for variations" by unchecking the "used for variations" box.
4. Now add a second Attribute (can be global or custom), also mark that second one as "not used for variations".
5. Save attributes --> all looks well.

![IqqfXB.png](https://user-images.githubusercontent.com/109691691/232554504-0fb5ecaf-ee6a-491d-be89-dae91dd04fe8.png)

7. Now click "publish" to publish the product --> double check Attributes --> the first one in the list is gone.
![vNRggp.png](https://user-images.githubusercontent.com/109691691/232554667-8f93c814-bed6-4fd0-900b-59ee7d74278c.png)

You can also duplicate this behaviour on existing Variable products. If you are editing an existing product and change anything about any one of the attributes, and all attributes are marked as "not used for variations", then the first one is erased.

The erasure appears to be true and permanent -- downgrading to version 7.5.1 does not make the deleted/unsaved attribute reappear.

Additional testing notes:
If only one attribute is used for testing, and it's set to "not used for variations" then this one attribute will be erased when the product is published.

If any one attribute set in the list is set to "used for variations" then all attributes, including the first one, will be saved correctly.

If you create your product with any one attribute set to "used for variations" so the attributes save correctly, then come back and uncheck the box so now all attributes are NOT "used for variations" and Update, then all attributes are saved correctly. You will only see the top one erased on an existing variable product if you make an edit to at least one attribute other than just unchecking the box, i.e. change its attribute values.

### WordPress Environment

From my test site:

`
### WordPress Environment ###

WordPress address (URL): https://numberone.mystagingwebsite.com
Site address (URL): https://numberone.mystagingwebsite.com
WC Version: 7.6.0
REST API Version: ✔ 7.6.0
WC Blocks Version: ✔ 9.8.4
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 8.0.28
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 7.86.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 10.4.25-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.6.0
WC Database Prefix: wp_
Total Database Size: 28.87MB
Database Data Size: 17.33MB
Database Index Size: 11.54MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.19MB + Index: 0.17MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 1.02MB + Index: 1.56MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 2.25MB + Index: 2.86MB + Engine InnoDB
wp_automatewoo_abandoned_carts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_customers: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_automatewoo_customer_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_events: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_guests: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_automatewoo_guest_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_log_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_referrals: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_referral_advocate_keys: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_automatewoo_referral_invites: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_ce4wp_abandoned_checkout: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ce4wp_contacts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.23MB + Index: 0.16MB + Engine InnoDB
wp_gla_budget_recommendations: Data: 0.22MB + Index: 0.14MB + Engine InnoDB
wp_gla_merchant_issues: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_shipping_rates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_custom_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_dynamic_segment_filters: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_feature_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_newsletter_links: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_newsletter_option: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_option_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_segment: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_templates: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_scheduled_tasks: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_scheduled_task_subscribers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_segments: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_sending_queues: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_settings: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_bounces: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_statistics_clicks: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_statistics_opens: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_statistics_unsubscribes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_woocommerce_purchases: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_mailpoet_stats_notifications: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_subscribers: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
wp_mailpoet_subscriber_custom_field: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_ips: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_segment: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_subscriber_tag: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_tags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_user_agents: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_user_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.05MB + Index: 0.08MB + Engine InnoDB
wp_postmeta: Data: 2.52MB + Index: 3.00MB + Engine InnoDB
wp_posts: Data: 0.25MB + Index: 0.13MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.14MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_bundle_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_order_composite_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.05MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_exported_csv_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_gc_activity: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_gc_cards: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_gc_cardsmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_flat_rate_boxes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpml_mails: Data: 3.52MB + Index: 0.00MB + Engine InnoDB
wp_yoast_indexable: Data: 0.11MB + Index: 0.09MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

acf-field: 1
acf-field-group: 1
attachment: 125
aw_workflow: 6
enr_email_template: 1
global_product_addon: 2
mailpoet_page: 1
nav_menu_item: 6
page: 12
post: 2
product: 105
product_variation: 100
revision: 16
shop_coupon: 4
shop_order: 219
shop_subscription: 37
wcpf_item: 8
wcpf_project: 2
wc_membership_plan: 4
wc_user_membership: 7
wp_global_styles: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (26) ###

Akismet Anti-Spam: by Automattic – 5.1
AutomateWoo - Refer A Friend Add-on: by WooCommerce – 2.6.20
AutomateWoo: by WooCommerce – 5.7.1
Code Snippets: by Code Snippets Pro – 3.3.0
Debug Bar: by wordpressdotorg – 1.1.4
Enhancer for WooCommerce Subscriptions: by FantasticPlugins – 3.7.0
Facebook for WooCommerce: by Facebook – 3.0.18
Jetpack: by Automattic – 12.1-a.5
WooCommerce All Products For Subscriptions: by WooCommerce – 4.0.5
WooCommerce Composite Products: by WooCommerce – 8.7.5
WooCommerce Distance Rate Shipping: by WooCommerce – 1.3.0
WooCommerce Memberships: by SkyVerge – 1.24.0
WooCommerce Payments: by Automattic – 5.7.0
WooCommerce Product Add-ons: by WooCommerce – 6.2.0
WooCommerce Product Bundles: by WooCommerce – 6.18.4
WooCommerce Product CSV Import Suite: by WooCommerce – 1.10.57
Product Filters for WooCommerce: by WooCommerce – 1.4.4
WooCommerce Shipping & Tax: by WooCommerce – 2.2.4
WooCommerce Flat Rate Box Shipping: by WooCommerce – 2.2.0
WooCommerce UPS Shipping: by WooCommerce – 3.4.1
WooCommerce - ShipStation Integration: by WooCommerce – 4.3.4
WooCommerce Subscriptions: by WooCommerce – 5.0.1
WooCommerce Table Rate Shipping: by WooCommerce – 3.1.1
WooCommerce: by Automattic – 7.6.0
Yoast SEO: by Team Yoast – 20.5
WP Mail Logging: by WP Mail Logging Team – 1.11.0

### Inactive Plugins (14) ###

Advanced Custom Fields: by WP Engine – 6.0.7
Advanced Product Fields for WooCommerce: by StudioWombat – 1.5.8
Custom Post Type UI: by WebDevStudios – 1.13.4
Extra Fees for WooCommerce: by FantasticPlugins – 4.2
Flexible Checkout Fields: by WP Desk – 3.5.4
Google Listings and Ads: by WooCommerce – 2.3.8
Loco Translate: by Tim Whitlock – 2.6.3
MailPoet: by MailPoet – 4.6.1
WooCommerce Customer/Order/Coupon CSV Import Suite: by SkyVerge – 3.11.0
WooCommerce Customer/Order/Coupon Export: by SkyVerge – 5.4.1
WooCommerce Force Sells: by WooCommerce – 1.1.31 (update to version 1.2.0 is available)
WooCommerce Name Your Price: by Kathy Darling – 3.3.10 (update to version 3.5.2 is available)
WooCommerce Quick View: by Themesquad – 1.7.0
WooCommerce Subscriptions Gifting: by WooCommerce – 2.5.1 (update to version 2.6.0 is available)

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
composite (composite)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
exclude_from_catalog (exclude_from_catalog)
exclude_from_search (exclude_from_search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)
visible (visible)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: ✔
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 4.2.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Memberships ###

Restriction mode:: Hide content only
Public content:: –
Excluded from discounts:: –
Membership plans:: 4
Free Membership:: Members: 2Access method: User account registrationAccess length: Unlimited Subscription: No
Basic membership:: Members: 0Access method: Product(s) purchaseAccess length: Specific length (60 days)Subscription: No
Fruit Basket Delivery:: Members: 2Access method: Product(s) purchaseAccess length: Unlimited Subscription: YesInstallment plan: No
VIP Membership:: Members: 3Access method: Product(s) purchaseAccess length: Specific length (6 months)Subscription: YesInstallment plan: No

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://numberone.mystagingwebsite.com
Subscriptions-core Library Version: 5.5.0
Subscription Statuses: wc-active: 22
wc-expired: 4
wc-pending-cancel: 1
wc-pending: 1
wc-on-hold: 4
wc-cancelled: 5

WooCommerce Account Connected: ✔ Yes
Active Product Key: ✔ Yes
Report Cache Enabled: ✔ Yes
Cache Update Failures: ✔ 0 failure

### Store Setup ###

Country / State: United States (US) — New York

### Subscriptions by Payment Gateway ###

Check payments: wc-on-hold: 1
WooCommerce Payments: wc-active: 19
wc-cancelled: 5
wc-expired: 4
wc-on-hold: 2
wc-pending-cancel: 1

### Payment Gateway Support ###

WooCommerce Payments: products
refunds
multiple_subscriptions
subscription_cancellation
subscription_payment_method_change_admin
subscription_payment_method_change_customer
subscription_payment_method_change
subscription_reactivation
subscription_suspension
subscriptions
subscription_amount_changes
subscription_date_changes
tokenization
add_payment_method

Check payments: products
Cash on delivery: products

### Composite Products ###

Database Version: 8.7.5
Loopback Test: ✔
Template Overrides: –

### Product Bundles ###

Database Version: 6.18.4
Loopback Test: ✔
Template Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: block-editor-feature-enabled
minified-js
new-product-management-experience
product-variation-management
settings

Daily Cron: ✔ Next scheduled: 2023-04-17 19:51:29 -04:00
Options: ✔
Notes: 90
Onboarding: completed

### WooCommerce Payments ###

Version: 5.7.0
Connected to WPCOM: Yes
Blog ID: 210717503
Account ID: acct_1Ljq8PFtdYohmYFC

### All Products for WooCommerce Subscriptions ###

Template Overrides: –

### Action Scheduler ###

Canceled: 9
Oldest: 2023-03-20 09:53:41 -0400
Newest: 2023-04-11 15:04:28 -0400

Complete: 1,843
Oldest: 2023-03-18 12:24:04 -0400
Newest: 2023-04-17 12:49:02 -0400

Failed: 16
Oldest: 2022-10-18 12:07:43 -0400
Newest: 2023-04-17 12:29:35 -0400

Pending: 44
Oldest: 2023-04-17 12:58:13 -0400
Newest: 2024-05-21 23:00:00 -0400

### Status report information ###

Generated at: 2023-04-17 12:53:42 -04:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by xue28** [comment]
6202400-zen

**Comment by syntaxerror** [comment]
Related: https://github.com/woocommerce/woocommerce/issues/37750

Note that we don't even need to touch the attributes on existing products, it's enough to just push the update button.

**Comment by xue28** [comment]
6210226-zen

**Comment by xue28** [comment]
6207392-zen

**Comment by mateoteleo** [comment]
I can confirm that even the automatic change of the stock size after a purchase is deleting the attribute.

**Comment by csmcneill** [comment]
Reported in 42061106-hc, can reproduce under conflict test conditions and on my own test site.

**Comment by csmcneill** [comment]
Flagging this to @thisissandip as this can be fairly high impact.

**Comment by xue28** [comment]
6219256-zen

**Comment by andy-jam** [comment]
We have the same issue. But not Variable products.

I’ve been looking at the wp_postmeta table.

For a selected product:

SELECT * FROM wp_postmeta WHERE post_id = 507902 AND meta_key = “_product_attributes”

gives:

a:1:{s:9:”sub-group”;a:6:{s:4:”name”;s:9:”Sub-Group”;s:5:”value”;s:4:”HD15″;s:11:”is_taxonomy”;i:0;s:8:”position”;i:0;s:10:”is_visible”;i:0;s:12:”is_variation”;i:0;}}

Updating the product without any editing and the query gives Empty Set.

Recreating the the Sub-Group attribute manually gives:

a:1:{s:12:”pa_sub-group”;a:6:{s:4:”name”;s:12:”pa_sub-group”;s:5:”value”;s:0:””;s:8:”position”;i:0;s:10:”is_visible”;i:0;s:12:”is_variation”;i:1;s:11:”is_taxonomy”;i:1;}}

All of these products are imported using WooCommerce Product CSV Import Suite it’s been working fine for at least 18 months.

That “pa_” is certainly new.

I suspect that any product with attributes created before 7.6 will lose their attributes if the product is updated even without any changes. Just hit update.

Our site has 460,000+ products. All with attributes.

**Comment by kalthoum21** [comment]
we’re experiencing issues with the attributes disappearing when updating a simple product or even the variable one after we’ve updated to WooCommerce 7.6.0. Please anyone could help to fix this issue

**Comment by EjayhanFernandes** [comment]
42065205-hc

**Comment by Euroracers** [comment]
This bug is reported more than a week ago, any updates on when it will be fixed?

**Comment by xue28** [comment]
6225422-zen

**Comment by xue28** [comment]
6225960-zen

**Comment by xue28** [comment]
6215984-zen

For this particular thread, this is the scenario:

-     Duplicate an old product with attributes that were created prior to the 7.6.0 update
-     Publish the product
-     Notice that the attributes of this duplicated product were deleted after publishing

Please note that this does not happen when a newly created product with attributes are being duplicated.

**Comment by xue28** [comment]
6219256-zen

For this particular thread, it affects simple products too.

**Comment by xue28** [comment]
6228159-zen

**Comment by seldimi** [comment]
Have you introduced a fix for 7.7;

**Comment by louwie17** [comment]
This issue will be addressed in a patch release for `7.6` -> `7.6.1`, this should be released in a couple day's.
Will close this issue once that is released.

**Comment by lanej0** [comment]
> Have you introduced a fix for 7.7;

In addition to the patch release (7.6.1) this issue is also confirmed to be fixed in 7.7 (which is currently in beta testing)

**Comment by xue28** [comment]
6233867-zen

**Comment by xue28** [comment]
6236878-zen

**Comment by csmcneill** [comment]
Maybe 6233879-zen

**Comment by lsinger** [comment]
7.6.1 has been released and should solve this issue. The upcoming 7.7 has also been confirmed to have this fixed. 

Feel free to reopen if this happens again in 7.6.1 or later.

**Comment by germamzva** [comment]
Hi,

I have the same issue with attributes and currently using the 7.9.0 version. 

I have an issue with setting attributes for my product. Whenever I save the attributes, the newly added ones (such as the 'Brand') disappear.

I have noticed that some of my products display appropriate attributes when being saved.

Any help is highly appreciated. 

Thanks

**Comment by m33ts4k0z** [comment]
Hello.

~~This is still an issue on version 7.9. If you edit the dimensions of a variation and then save it, then it stays saved but as soon as you press the update button for the whole product, the dimensions return to 0.~~

EDIT: This issue was caused by an addon called Fortnox.

**Comment by Nihal12-dev** [comment]
Hi Team,

We're currently experiencing this on one of our client's sites as well on the latest version 8.3.1 and saving an existing or creating a new variable product be it in draft mode or published mode seems to wipe out all the attributes and subsequently it's variations which is super strange. 

Note that the variations and attributes aren't being deleted but just get removed altogether. So when it gets wiped and i go back in and add them all back and hit save again the same thing happens and it's an endless cycle. Could someone please help with this ? 

This site's a multi-site, We've got a staging environment setup with an older version of woocommerce which is on 8.2.1 and this doesn't seem to be happening with this version. 


Here are the site details below :


`
### wp-core ###

version: 6.3.2
site_language: en_AU
user_language: en_AU
timezone: America/New_York
permalink: /%postname%/
https_status: true
multisite: true
user_registration: false
blog_public: 1
default_comment_status: closed
environment_type: production
site_count: 5
network_count: 1
user_count: 452
dotorg_communication: true

### wp-dropins (1) ###

object-cache.php: true

### wp-active-theme ###

name: Twenty Twenty-One (twentytwentyone)
version: 2.0
author: the WordPress team
author_website: https://wordpress.org/
parent_theme: none
theme_features: core-block-patterns, block-templates, wc-product-gallery-zoom, wc-product-gallery-lightbox, wc-product-gallery-slider, woocommerce, widgets-block-editor, post-thumbnails, automatic-feed-links, title-tag, post-formats, menus, html5, custom-logo, customize-selective-refresh-widgets, wp-block-styles, align-wide, editor-styles, editor-style, editor-font-sizes, custom-background, editor-color-palette, editor-gradient-presets, responsive-embeds, custom-line-height, link-color, custom-spacing, custom-units, infinite-scroll, jetpack-geo-location, jetpack-content-options, widgets
theme_path: /home/runcloud/webapps/gripstar-prd/wp-content/themes/twentytwentyone
auto_update: Enabled

### wp-themes-inactive (3) ###

Twenty Twenty-Three: version: 1.3, author: the WordPress team, Auto-updates enabled
Twenty Twenty-Two: version: 1.6, author: the WordPress team, Auto-updates enabled
YITH Wonder: version: 1.3.3, author: YITH, Auto-updates enabled

### wp-mu-plugins (2) ###

ManageWP - Worker Loader: version: 1.0.0, author: GoDaddy
WP Migrate Compatibility: version: 1.3, author: Delicious Brains

### wp-plugins-active (40) ###

Code Snippets: version: 3.6.2, author: Code Snippets Pro, Auto-updates enabled
Custom Order Numbers for WooCommerce: version: 1.6.0, author: Tyche Softwares, Auto-updates enabled
Custom Post Type UI: version: 1.15.1, author: WebDevStudios, Auto-updates enabled
Elementor: version: 3.17.3, author: Elementor.com, Auto-updates enabled
Elementor Pro: version: 3.17.1, author: Elementor.com, Auto-updates enabled
Facebook for WooCommerce: version: 3.1.4, author: Facebook, Auto-updates enabled
GeoTargetingWP: version: 3.5.1.1, author: Timersys, Auto-updates enabled
GTM4WP: version: 1.18.1, author: Thomas Geiger, Auto-updates enabled
Head, Footer and Post Injections: version: 3.2.7, author: Stefano Lissa, Auto-updates enabled
Jetpack: version: 12.8.1, author: Automattic, Auto-updates enabled
LiteSpeed Cache: version: 5.7.0.1, author: LiteSpeed Technologies, Auto-updates enabled
Mailchimp for WooCommerce: version: 3.3, author: Mailchimp, Auto-updates enabled
ManageWP - Worker: version: 4.9.17, author: GoDaddy, Auto-updates disabled
Meta pixel for WordPress: version: 3.0.14, author: Facebook, Auto-updates enabled
myStickymenu Pro: version: 2.6.5, author: Premio (latest version: 2.6.6), Auto-updates enabled
Options for Twenty Twenty-One: version: 1.7.2, author: Webd Ltd, Auto-updates enabled
Order Export & Order Import for WooCommerce: version: 2.4.2, author: WebToffee, Auto-updates enabled
Products By Attributes & Variations for WooCommerce: version: 1.5.0, author: Addify, Auto-updates enabled
Read More Without Refresh: version: 3.3.3, author: Eightweb Interactive, Auto-updates enabled
Sucuri Security - Auditing, Malware Scanner and Hardening: version: 1.8.39, author: Sucuri Inc., Auto-updates enabled
SVG Support: version: 2.5.5, author: Benbodhi, Auto-updates enabled
Ultimate Addons for Elementor: version: 1.36.25, author: Brainstorm Force, Auto-updates enabled
Variation Images Gallery for WooCommerce: version: 2.3.8, author: RadiusTheme, Auto-updates enabled
Variation Swatches for WooCommerce: version: 2.3.12, author: RadiusTheme, Auto-updates enabled
Variation Swatches for WooCommerce Pro: version: 2.2.5, author: RadiusTheme, Auto-updates enabled
WooCommerce: version: 8.3.1, author: Automattic, Auto-updates enabled
WooCommerce Shipment Tracking: version: 2.3.5, author: WooCommerce (latest version: 2.4.1), Auto-updates enabled
WooCommerce Shipping & Tax: version: 2.4.1, author: WooCommerce, Auto-updates enabled
WooCommerce Stripe Gateway: version: 7.7.0, author: WooCommerce, Auto-updates enabled
WooCommerce USPS Shipping: version: 4.6.2, author: WooCommerce (latest version: 4.7.5), Auto-updates enabled
Woo Discount Rules: version: 2.6.2, author: Flycart, Auto-updates enabled
Woo Discount Rules PRO 2.0: version: 2.6.1, author: Flycart, Auto-updates enabled
WordPress Importer: version: 0.8.1, author: wordpressdotorg, Auto-updates enabled
WP Crontrol: version: 1.16.1, author: John Blackbourn & crontributors, Auto-updates enabled
WP File Manager: version: 7.2.1, author: mndpsingh287, Auto-updates enabled
WP Migrate: version: 2.6.10, author: WP Engine, Auto-updates enabled
WP Store Locator: version: 2.2.241, author: Tijmen Smit, Auto-updates enabled
YaySMTP - Simple WP SMTP Mail: version: 2.5.5, author: YayCommerce, Auto-updates enabled
Yoast Duplicate Post: version: 4.5, author: Enrico Battocchi & Team Yoast, Auto-updates enabled
Yoast SEO: version: 21.6, author: Team Yoast, Auto-updates enabled

### wp-plugins-inactive (25) ###

Afterpay Gateway for WooCommerce: version: 3.7.1, author: Afterpay, Auto-updates enabled
Akismet Anti-spam: Spam Protection: version: 5.3, author: Automattic - Anti-spam Team, Auto-updates enabled
Broken Link Checker: version: 2.2.3, author: WPMU DEV, Auto-updates enabled
Complianz Privacy Suite (GDPR/CCPA) premium: version: 6.5.2, author: Really Simple Plugins (latest version: 7.0.3), Auto-updates enabled
Conditional Shipping for WooCommerce: version: 3.1.2, author: Lauri Karisola / WP Trio, Auto-updates enabled
Google Listings and Ads: version: 2.5.12, author: WooCommerce, Auto-updates enabled
Import Export for WooCommerce Wrapper: version: 1.2.0, author: WebToffee, Auto-updates enabled
LocaliQ - Tracking Code: version: 1.9, author: LocaliQ, Auto-updates enabled
New Zealand Shipping Zones for WooCommerce: version: 1.0.2, author: Daniel Shaw, Auto-updates enabled
Omnivore: version: 3.12, author: City Beach Software, Auto-updates enabled
Points and Rewards for WooCommerce: version: 2.0.1, author: WP Swings, Auto-updates enabled
Points and Rewards For WooCommerce Pro: version: 2.4.0, author: WP Swings, Auto-updates enabled
Pre-Orders for WooCommerce: version: 1.2.14, author: Bright Plugins, Auto-updates enabled
Pre-Orders for WooCommerce PRO: version: 1.7.1, author: Bright Plugins, Auto-updates enabled
Product Import Export for WooCommerce: version: 2.3.7, author: WebToffee, Auto-updates enabled
Product Import Export for WooCommerce Add-on: version: 1.1.7, author: WebToffee, Auto-updates enabled
Product Slider for WooCommerce: version: 2.6.9, author: ShapedPlugin LLC, Auto-updates enabled
Query Monitor: version: 3.15.0, author: John Blackbourn, Auto-updates disabled
Redirection: version: 5.3.10, author: John Godley, Auto-updates enabled
WooCommerce Google Product Feed: version: 10.11.1, author: Ademti Software Ltd., Auto-updates enabled
WooCommerce PayPal Payments: version: 2.4.1, author: WooCommerce, Auto-updates enabled
WooCommerce Product Search: version: 4.15.0, author: itthinx (latest version: 5.0.4), Auto-updates enabled
WooCommerce Wholesale Prices: version: 2.1.10.1, author: Rymera Web Co, Auto-updates enabled
WPForms Lite: version: 1.8.5.2, author: WPForms, Auto-updates enabled
YHP-Worldline-Gateway-Click: version: 4.0, author: YHP, Auto-updates enabled

### code-snippets (1) ###

snippet-6: name: Mini cart fix, scope: global, modified: 2023-11-24 02:07:55

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1691
imagemagick_version: ImageMagick 6.9.11-60 Q16 x86_64 2021-01-25 https://imagemagick.org
imagick_version: 3.7.0
file_uploads: File uploads is turned off
post_max_size: 256M
upload_max_filesize: 256M
max_effective_size: 256 MB
max_file_uploads: 20
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 122 MB
	imagick::RESOURCETYPE_DISK: 1073741824
	imagick::RESOURCETYPE_FILE: 786432
	imagick::RESOURCETYPE_MAP: 512 MB
	imagick::RESOURCETYPE_MEMORY: 256 MB
	imagick::RESOURCETYPE_THREAD: 1
	imagick::RESOURCETYPE_TIME: 9.2233720368548E+18
imagemagick_file_formats: 3FR, 3G2, 3GP, AAI, AI, APNG, ART, ARW, AVI, AVIF, AVS, BGR, BGRA, BGRO, BIE, BMP, BMP2, BMP3, BRF, CAL, CALS, CANVAS, CAPTION, CIN, CIP, CLIP, CMYK, CMYKA, CR2, CR3, CRW, CUR, CUT, DATA, DCM, DCR, DCX, DDS, DFONT, DNG, DPX, DXT1, DXT5, EPDF, EPI, EPS, EPS2, EPS3, EPSF, EPSI, EPT, EPT2, EPT3, ERF, FAX, FILE, FITS, FRACTAL, FTP, FTS, G3, G4, GIF, GIF87, GRADIENT, GRAY, GRAYA, GROUP4, H, HALD, HDR, HEIC, HISTOGRAM, HRZ, HTM, HTML, HTTP, HTTPS, ICB, ICO, ICON, IIQ, INFO, INLINE, IPL, ISOBRL, ISOBRL6, J2C, J2K, JBG, JBIG, JNG, JNX, JP2, JPC, JPE, JPEG, JPG, JPM, JPS, JPT, JSON, K25, KDC, LABEL, M2V, M4V, MAC, MAGICK, MAP, MASK, MAT, MATTE, MEF, MIFF, MKV, MNG, MONO, MOV, MP4, MPC, MPG, MRW, MSL, MTV, MVG, NEF, NRW, NULL, ORF, OTB, OTF, PAL, PALM, PAM, PATTERN, PBM, PCD, PCDS, PCL, PCT, PCX, PDB, PDF, PDFA, PEF, PES, PFA, PFB, PFM, PGM, PGX, PICON, PICT, PIX, PJPEG, PLASMA, PNG, PNG00, PNG24, PNG32, PNG48, PNG64, PNG8, PNM, POCKETMOD, PPM, PREVIEW, PS, PS2, PS3, PSB, PSD, PTIF, PWP, RADIAL-GRADIENT, RAF, RAS, RAW, RGB, RGBA, RGBO, RGF, RLA, RLE, RMF, RW2, SCR, SCT, SFW, SGI, SHTML, SIX, SIXEL, SPARSE-COLOR, SR2, SRF, STEGANO, SUN, TEXT, TGA, THUMBNAIL, TIFF, TIFF64, TILE, TIM, TTC, TTF, TXT, UBRL, UBRL6, UIL, UYVY, VDA, VICAR, VID, VIDEO, VIFF, VIPS, VST, WBMP, WEBM, WEBP, WMV, WPG, X, X3F, XBM, XC, XCF, XPM, XPS, XV, XWD, YCbCr, YCbCrA, YUV
gd_version: bundled (2.1.0 compatible)
gd_formats: GIF, JPEG, PNG, WebP, BMP, XPM
ghostscript_version: 9.55.0

### wp-server ###

server_architecture: Linux 6.2.0-1016-aws x86_64
httpd_software: LiteSpeed
php_version: 7.4.33 64bit
php_sapi: litespeed
max_input_variables: 120
time_limit: 60
memory_limit: 1024M
max_input_time: 120
upload_max_filesize: 256M
php_post_max_size: 256M
curl_version: 7.81.0 OpenSSL/3.0.2
suhosin: false
imagick_availability: true
pretty_permalinks: true
htaccess_extra_rules: true
current: 2023-11-29T02:14:59+00:00
utc-time: Wednesday, 29-Nov-23 02:14:59 UTC
server-time: 2023-11-28T21:14:56-05:00

### wp-database ###

extension: mysqli
server_version: 10.11.6-MariaDB-1:10.11.6+maria~ubu2204
client_version: mysqlnd 7.4.33
max_allowed_packet: 67108864
max_connections: 4096

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /home/runcloud/webapps/gripstar-prd/wp-content
WP_PLUGIN_DIR: /home/runcloud/webapps/gripstar-prd/wp-content/plugins
WP_MEMORY_LIMIT: 256M
WP_MAX_MEMORY_LIMIT: 512M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: true
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_ENVIRONMENT_TYPE: Undefined
WP_DEVELOPMENT_MODE: undefined
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable

### jetpack ###

site_id: 197118045
ssl_cert: No
time_diff: undefined
version_option: 12.8.1:1699912923
old_version: 12.8:1699308091
public: Public
master_user: #302 boylensupport
is_offline_mode: off
is_offline_mode_constant: off
current_user: #4 joelm
tokens_set: Blog 
blog_token: B1oRU&$yY@8F6XJJe*zbeYTu19$!op2&
user_token: Not set.
version: 12.8.1
jp_plugin_dir: /home/runcloud/webapps/gripstar-prd/wp-content/plugins/jetpack/
plan: free
protect_header: {"trusted_header":"HTTP_X_FORWARDED_FOR","segments":0,"reverse":false}
full_sync: {"started":"Tue, 31 Oct 2023 12:43:14 +0000","finished":"Tue, 31 Oct 2023 12:43:32 +0000","progress":{"options":{"finished":true},"functions":{"finished":true},"constants":{"finished":true},"users":{"total":"1","sent":1,"finished":true,"last_sent":"302"},"network_options":{"finished":true}},"config":{"options":true,"functions":true,"constants":true,"users":[302],"network_options":true}}
sync_size: undefined
sync_lag: 0 seconds
full_sync_size: undefined
full_sync_lag: 0 seconds
idc_urls: {"home":"https:\/\/gripstarsocks.com","siteurl":"https:\/\/gripstarsocks.com","WP_HOME":"","WP_SITEURL":""}
idc_error_option: false
idc_optin: false
cxn_tests: All Pass.

`

**Comment by lsinger** [comment]
@Nihal12-dev thanks for reaching out. Is that the same issue as above, as in, are the "Steps to reproduce" mentioned in the original issue the same that you'd be using for reproduction? If yes please confirm, if no please open a separate issue with your own "Steps to reproduce". Thanks!

**Comment by TomasHurtz** [comment]
I also still have this issue in Feb 2024 - the strange thing is, on my staging site it does not happen, but on my production site it happens when I try to update the post / page.  

The woo attributes get lost, but if I update the woo product attributes in the woo section of the product post, they save ok.  

It only gives problem when I update the main post using top right blue button.....

**Comment by lillianind24** [comment]
Hello! Its June and this problem still exists in the most recent module update.

Has there been any update on fixing this bug by any chance? Is Woocomerce support aware that the problem persists almost a year after opening this ticket?

**Comment by ImpossibleK** [comment]
This exact issue started today with me for the first time. Hitting the update button on an existing product after making normal changes (adding three variations) deletes the attributes. After re-adding attributes, the variations are there (with photos still attached) but I need to pick the attributes that match them.  I must pick the variations one at a time, and save them each one with the "Save Changes" button, as if I try and change all 15 and save, it hangs *indefinitely*. Then, all the attributes are deleted again after pressing the "Update" button. I cannot save this product. I can no longer SELL this product. I have lost the same changes 4 times now - as I am not a developer, I am completely lost as to how I can get my product back online. Can anyone help?

**Comment by TomasHurtz** [comment]
Hello Everyone, I don't know if my solution will work for you, but I discovered after trial and error, that my issue seemed to be caused by the plugin called Yoast SEO.  Once I disabled that plugin, attributes were saving correctly again.
I moved to the AIOSEO instead.

**Comment by SKR2004** [comment]
> مرحبًا بالجميع، لا أعلم ما إذا كان حلي سينجح معكم، ولكنني اكتشفت بعد التجربة والخطأ أن المشكلة التي واجهتها كانت ناجمة عن المكون الإضافي المسمى Yoast SEO. بمجرد تعطيل هذا المكون الإضافي، تم حفظ السمات بشكل صحيح مرة أخرى. لذا انتقلت إلى AIOSEO بدلاً من ذلك.

**Comment by SKR2004** [comment]
We are really fed up with it. We tried for three days in a row, but nothing worked. Something is wrong. All plugins have been disabled and the theme has been changed too, and the problem still persists.

Themes and their configurations are not supported for multi-variety products.
Yoast SEO plugin has also been disabled and removed, and it also doesn't work.
If there is any update, please provide us.
