### ISSUE TITLE
7.8.1 introduces a fatal error regarding wc_get_default_product_type_options during tracking

### ISSUE THREAD

**Issue by dgwatkins** [woothemes/woocommerce#38996]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

At the moment, I don't have too much but I wanted to raise the flag as soon as possible.

Since 7.8.1 was launched, our end to end tests are failing with this error message:
`PHP Fatal error: Uncaught Error: Call to undefined function wc_get_default_product_type_options() in wp-content/plugins/woocommerce/includes/tracks/events/class-wc-products-tracking.php:242`

This didn't happen with WC 7.8

I'm guessing this won't be noticeable to users because tracking happens in the background.

### Expected behavior

I expect no error

### Actual behavior

We get a fatal error

### Steps to reproduce

I started with a fresh WC install and storefront (with its sample products).

One way to trigger the error is to publish a product outside of the admin context (the missing function seems to be loaded only in admin).

For example, with: `wp wc product create --name=testing --regular_price=50 --user=admin`

I'm getting:
```
Fatal error: Uncaught Error: Call to undefined function wc_get_default_product_type_options() in wp-content/plugins/woocommerce/includes/tracks/events/class-wc-products-tracking.php:242
Stack trace:
#0 wp-content/plugins/woocommerce/includes/tracks/events/class-wc-products-tracking.php(259): WC_Products_Tracking::get_possible_product_type_options_ids()
#1 wp-content/plugins/woocommerce/includes/tracks/events/class-wc-products-tracking.php(311): WC_Products_Tracking::get_product_type_options(75)
#2 wp-includes/class-wp-hook.php(308): WC_Products_Tracking->track_product_published(75, Object(WP_Post), false, NULL)
#3 wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#4 wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#5 wp-content/plugins/woocommerce/includes/tracks/events/class-wc-products-tracking.php on line 242
```

### WordPress Environment

WordPress address (URL): https://wcml.dvl.to
Site address (URL): https://wcml.dvl.to
WC Version: 7.8.1
REST API Version: ✔ 7.8.1
WC Blocks Version: ✔ 10.2.4
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.2.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: –
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.54 (Unix) OpenSSL/3.0.7
PHP Version: 8.1.14
PHP Post Max Size: 1 GB
PHP Time Limit: 5000
PHP Max Input Vars: 3000
cURL Version: 7.74.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 10.10.3-MariaDB-1:10.10.3+maria~ubu2204-log
Max Upload Size: 600 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.8.1
WC Database Prefix: wp_
Total Database Size: 7.07MB
Database Data Size: 5.01MB
Database Index Size: 2.06MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 3.34MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.11MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 36
customize_changeset: 1
page: 14
post: 3
product: 15
revision: 5
shop_order: 1
wp_global_styles: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 7.8.1

### Inactive Plugins (178) ###

n/a

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #19 - /shop/
Cart: #20 - /cart/
Checkout: #21 - /checkout/
My account: #22 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 4.3.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: core-profiler
minified-js
new-product-management-experience
product-variation-management
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-06-28 12:13:48 +00:00
Options: ✔
Notes: 58
Onboarding: skipped

### Action Scheduler ###

Complete: 5
Oldest: 2023-06-28 12:14:53 +0000
Newest: 2023-06-28 12:24:44 +0000

Pending: 2
Oldest: 2023-06-28 12:27:10 +0000
Newest: 2023-06-29 12:14:53 +0000

Failed: 2
Oldest: 2023-06-28 12:15:54 +0000
Newest: 2023-06-28 12:23:07 +0000

### Status report information ###

Generated at: 2023-06-28 12:26:28 +00:00

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by kamarkiewicz** [comment]
You can add a quick fix at the beginning of the file `woocommerce/includes/tracks/events/class-wc-products-tracking.php`:
```php
<?php
/**
 * WooCommerce Import Tracking
 *
 * @package WooCommerce\Tracks
 */

require_once dirname( __FILE__ ) . '/../../admin/wc-admin-functions.php'; // QUICK FIX

use Automattic\Jetpack\Constants;
// ...

**Comment by DtheRock** [comment]
same issue here.

**Comment by sgarner** [comment]
I'm working with a WooCommerce store that uses Lightspeed POS. This bug prevents the Lightspeed integration from syncing product data to WC using the API. Requests to `POST /wp-json/wc/v2/products` hit the error and return a 500 response.

This is quite impactful, so I hope a hot fix can be released ASAP 🙏

**Comment by ptrkx747** [comment]
same problem on current project

**Comment by PontusTideman** [comment]
This is stopping WPML from working correctly and fills up the ATE-log with errors also:

`Call to undefined function wc_get_default_product_type_options() /var/www/HIDDEN-URL.tld/wp-content/plugins/woocommerce/includes/tracks/events/class-wc-products-tracking.php:242`

Edit: the hotfix provided above fixed the errors for WPML and is working fine again!

**Comment by malcra** [comment]
The hotfix proposed above resolved my issues with the creating a product with wc python api; rather than failingt to create the product, it created it with missing attributes, making it more fun to bebug.

**Comment by scottybo** [comment]
Just echoing that the hotfix has resolved the issue - causing a lot of failures with our API integrations.

**Comment by alexpetrie69** [comment]
We are also having it affect some scripts written to synch product data, however, the hot fix is not working for me.

I pasted 

require_once dirname( __FILE__ ) . '/../../admin/wc-admin-functions.php'; // QUICK FIX

into 

\wp-content\plugins\woocommerce\includes\tracks\events\class-wc-products-tracking.php

But I still get the error

**Comment by strategio** [comment]
This issue is pretty annoying and causing significant problems to our WPML users.

We've published an errata https://wpml.org/errata/woocommerce-php-fatal-error-uncaught-error-call-to-undefined-function-wc_get_default_product_type_options/.

For the record:
- This ticket contains very clear and simple minimal steps to reproduce the issue.
- It's not a compatibility issue, it happens on a basic WC site.
- It's affecting a lot of users in many different contexts.
- It's a regression from WC 7.8.0 (and previous WC versions).

**A quick patch version is more than expected.**

**Comment by namiokuzono** [comment]
WE - 6480725-zen

**Comment by sgarner** [comment]
Great to see the fix by @louwie17 has been merged, thank you. Could we please get an indicative timeline for releasing this as a patch version?

In my case the store is hosted on wordpress.com so there is no ability to edit the woocommerce plugin files to apply the hacks in this thread, we're reliant on an official update being released for the plugin.

Aside: I have now discovered that each time this error occurs when creating a product through the API, a partial "stub" version of the product is created with only a title and description (no images, no SKU, nor any other attributes). And when an integration retries a failed attempt to create a product, it causes another duplicate stub product to be left behind on each attempt. The fact that an error during creation can leave the system in an inconsistent state suggests to me that there is a wider issue with transaction handling and atomicity in this API.

**Comment by garidium** [comment]
I also saw the phantom product generation issue @sgarner mentioned. It was hours of troubleshooting with a customer on their integration until I found this thread.

**Comment by psealock** [comment]
>Could we please get an indicative timeline for releasing this as a patch version?

@sgarner We are aiming for a 7.8.2 patch release next week

**Comment by blueloto** [comment]
The Fix above solved my issues, Thank you @kamarkiewicz 

I was dealing with customer service since yesterday thinking it was a problem from their end until I installed a different dropshipping service to Woo.

**Comment by recca004** [comment]
Thanks The Fix above solved my issues.

**Comment by ASMRcode** [comment]
Fixed my issue! After days of troubleshooting this fixed it instantly!! Thanks guys!

**Comment by juansansonjr** [comment]
I broke my website completely trying to apply

**Comment by kwongchung** [comment]
Printful is having trouble uploading products to our WooCommerce Wordpress store. Keep getting messages:  "Product was not added! 500 Internal Server Error occurred!"

Will a WooCommerce plugin update fix this? Thanks.

**Comment by sgarner** [comment]
> @sgarner We are aiming for a 7.8.2 patch release next week

Thanks @psealock. I just want to emphasise that this bug is having a real business impact for the many stores that rely on the API, and for those of us using wordpress.com there is no resolution yet. So I hope this release is being given the utmost urgency.

**Comment by rossviviano** [comment]
6486829-zen

**Comment by LucMacPaquet** [comment]
Cannot edit class-wc-products-tracking.php

I always got - Read-only file system

**Comment by Obustin** [comment]
Hello. Since the update, my project(https://passionplants.fr/) which was starting off well, has come to a standstill. Sellers can no longer add products to the shop on my marketplace. It's a real blow to the credibility and future of my business. I have a lot of questions about whether to continue working with Woocommerce and its various extensions...too complicated, too many problems.

**Comment by ttridley** [comment]
This problem has bought our business to a standstill.  We please stress the urgency of a fix.

**Comment by Obustin** [comment]
I rolled back to the previous version of WC Vendors (v 2.4.6 ) and Woocommerce (v 7.8), and magically everything is working fine again... Crazy. So much time wasted for this.

**Comment by spookymadeit** [comment]
i too am having this same issue, I suppose I'll try rolling back as well. I've been using WC & WP for 3 days now and have gotten a wonderful first impression lol

**Comment by juansansonjr** [comment]
Many will switch to Shopify because of this standstill and no sense of urgency from Woocommerce. I am already considering it too.

**Comment by stoltzrx** [comment]
6474219-zen

**Comment by markuznw** [comment]
This should be marked as critical and hotfixed in a matter of hours not days, got several breakages and lost time tracking up to this bug.
Rolling back to 7.8 fixed it

**Comment by Obustin** [comment]
Rolling back to previous version of Woocommerce(7.8) fixed it(I can upoad product image) but I can't add any more images in the product gallery even after increasing the max upload size...(really tired of it)

**Comment by dgwatkins** [comment]
@psealock Will this be included in 7.9 RC1? Its supposed to be released tomorrow and we wont be able to test it properly with this issue.

**Comment by xue28** [comment]
6477180-zd

**Comment by spookymadeit** [comment]
I tried to do the hot fix this morning as a last ditch effort however that didn't work either :(( Really in a bind here as my physical store uses Square POS Hardware, can't just switch my inventory to shopify without spending a bunch of $$$ on new hardware :(

**Comment by hohner369** [comment]
I also rolled back to 7.8.0 and I can now work normally. Printify gives no clues as to what the problem is, but printful will at least give a vague error 500 message to give you something to work on.

**Comment by lynnjat7** [comment]
6484775-zen

**Comment by juansansonjr** [comment]
I too have rolled back to 7.7.2, downloaded it, uploaded the plugin, confirmed the downgrade, then presto. All is working for now. I also disabled auto-updates to prevent issues.

**Comment by muhamadjuwara** [comment]
im having issues list product from cj to my store is there anyone having same issue.
video link below
https://www.awesomescreenshot.com/video/18801786?key=7bbb6caa2ca6f71041909c85d27a2bb9

i try the quick fix but it always crashes my store
![screenshot (5)](https://github.com/woocommerce/woocommerce/assets/47766927/ebd89261-6d3d-4994-895e-8221ffc15bcb)

**Comment by LucMacPaquet** [comment]
I just chat with WP support (my site is hosted by them). The fix should be out tomorrow. 

"As the bug fix release is planned to release tomorrow. The fix should be released with WooCommerce 7.8.2, and your site should automatically update to that version once it's available."

**Comment by muhamadjuwara** [comment]
thank you work the info, i really appreciate that

**Comment by ashleybaileydesigns** [comment]
7.8.2 Woocommerce was just released. Let me know if this patch has or has not fixed your integration.

**Comment by spookymadeit** [comment]
So Far I seem to be having the same luck. Only now I've had a couple of products sync from square over to WC. I will leave it be for the rest of the day and report back tomorrow if it comes to that. In my case rolling back to several different versions of WC didn't help either so I wonder if this is even what's going on at this point.

**Comment by kwongchung** [comment]
I updated the WooCommerce plugin to 7.8.2 - it works now! No more 500
Internal Server Error message.

Thank you WooCommerce Team

**Comment by skyedgedev** [comment]
> You can add a quick fix at the beginning of the file `woocommerce/includes/tracks/events/class-wc-products-tracking.php`:
> 
> ```
> <?php
> /**
>  * WooCommerce Import Tracking
>  *
>  * @package WooCommerce\Tracks
>  */
> 
> require_once dirname( __FILE__ ) . '/../../admin/wc-admin-functions.php'; // QUICK FIX
> 
> use Automattic\Jetpack\Constants;
> // ...
> ```

That fix did the work! Thank you.

**Comment by stoltzrx** [comment]
6483079-zen

**Comment by muhamadjuwara** [comment]
Yes it did fix it, thank you so much Sent from my iPhoneOn Jul 3, 2023, at 6:52 PM, kwongchung ***@***.***> wrote:﻿
I updated the WooCommerce plugin to 7.8.2 - it works now! No more 500

Internal Server Error message.



Thank you WooCommerce Team









On Mon, Jul 3, 2023 at 5:53 PM spookymadeit ***@***.***>

wrote:

**Comment by AashikP** [comment]
Another report in 6484734-zen - Error while adding products via Printful.

**Comment by kaushikasomaiya** [comment]
Hi everyone! Just posting it here in case if it helps anyone. Does disabling usage tracking from **WooCommerce > Settings > Advanced > WooCommerce.com** help?

**Comment by kaushikasomaiya** [comment]
Adding some more findings:

**Steps to replicate:**

1. Enable Usage Tracking in WooCommerce
2. Using Rest API -> Try creating a new product: /wp-json/wc/v3/products
3. See the fatal error
4. Disable Usage Tracking
5. Issue is resolved.

**Comment by vedanshujain** [comment]
Hey folks, this should be fixed in WC 7.8.2, are you still seeing this error on latest WooCommerce?

**Comment by kaushikasomaiya** [comment]
@vedanshujain Apologies I was testing it on 7.8.1 - it seems the issue is not there on 7.8.2.

**Comment by vedanshujain** [comment]
Closing this issue as per ^ fixed in #39030

**Comment by peachtwists** [comment]
How do I rollback to the previous WooCommerce version?

**Comment by peachtwists** [comment]
@vedanshujain I'm still experiencing issues. This is not fixed for me

**Comment by peachtwists** [comment]
> @vedanshujain I'm still experiencing issues. This is not fixed for me

Spinning wheel on new product that was added yesterday 
<img width="683" alt="image" src="https://github.com/woocommerce/woocommerce/assets/138255410/cccc2dda-34d5-4b75-a1e0-d176cd692af4">

**Comment by Obustin** [comment]
> 
[
](https://fr.wordpress.org/plugins/wp-rollback/)

**Comment by kaushikasomaiya** [comment]
Hi there @peachtwists The spinning wheel issue seems a different one and might be due to conflict with Klarna plugin that you are using:

![https://d.pr/i/hvIWeU](https://d.pr/i/hvIWeU+) 
Full Size: https://d.pr/i/hvIWeU

**Comment by peachtwists** [comment]
@kaushikasomaiya Thank you. Disabling Klarna plugin worked!

**Comment by Obustin** [comment]
When vendors try to upload an image to the dashboard gallery(WC Vendors Pro) by taking a photo with their mobile phone, the image does not load at all. They are required to choose an image from their phone's gallery instead for it to work. Does anyone happen to have a solution please? Thank you very much.

**Comment by SilverCairns** [comment]
I'm still having this issue with 7.8.2. I've tried rolling back, i've tried adding the hotfix, nothing is working and still getting publishing error from printify. Any other suggestions? Thank you all in advance!

**Comment by Mxchael** [comment]
6517316-zen

**Comment by mattsherman** [comment]
@SilverCairns 

> I'm still having this issue with 7.8.2. I've tried rolling back, i've tried adding the hotfix, nothing is working and still getting publishing error from printify. Any other suggestions? Thank you all in advance!

Can you please share the exact error messages you are getting? Thanks!

**Comment by SilverCairns** [comment]
I'm still having this issue with 7.8.2. I've tried rolling back, i've tried adding the hotfix, nothing is working and still getting publishing error from printify. Any other suggestions? Thank you all in advance!
> 
> Can you please share the exact error messages you are getting? Thanks!

@mattsherman 
Here's a screenshot - Printify products getting a "publishing error" every time now. thanks for your help! 
<img width="980" alt="Screenshot 2023-07-10 at 9 11 53 AM" src="https://github.com/woocommerce/woocommerce/assets/138894377/8821cb18-c972-46c2-b236-3b526d489db5">

**Comment by mattsherman** [comment]
@SilverCairns 

> I've tried rolling back

If you have tried rolling back to WooCommerce 7.8.0 and are still getting this error, I am pretty confident it is not this specific issue, as it was introduced in 7.8.1. 

In order to best help you out, please open a support request at:

https://woocommerce.com/my-account/create-a-ticket/

We will then be able to help you figure out what's going on!
