### ISSUE TITLE
[Enhancement]: Verify, unify and stabilize (or not) experimental events fired from Blocks

### ISSUE THREAD

**Issue by kmanijak** [woothemes/woocommerce#42985]
### Describe the solution you'd like

In [Features Flags and Experimental Interfaces](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-blocks/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md) - [Usages of experimental prefix](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-blocks/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md#usages-of-experimental-prefix) section we describe the set of events that are supposed to be fired for 3PD.

Recently it was flagged on WooCommerce Community Slack that some of the events are not fired or are fired inconsistently, like `experimental__woocommerce_blocks-cart-add-item` is fired from All Products block but not from Products or Product Collection.

There's another set of hooks from Core ([documentation](https://wp-kama.com/plugin/woocommerce/hook)) which in some cases is symmetrical to Blocks events. The key difference is:
- Core events are fired in PHP (server-side rendered blocks)
- Blocks events are fired in JS (client-side rendered blocks)
As an example, there are:
- Core: [`woocommerce_add_to_cart`](https://wp-kama.com/plugin/woocommerce/hook/woocommerce_add_to_cart)
- Blocks: [`experimental__woocommerce_blocks-cart-add-item `](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-blocks/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md#usages-of-experimental-prefix)

---

TODO:
- [ ] Decide whether events should be kept duplicated (as-is) or we should stick with Core events

**If unified:**
- [ ] Make sure all events are available in Core. Initiate deprecation process.

**If duplicated:**
- [ ] Verify that the events are fired from all blocks and places they're supposed to. (Example of quick patch to trigger event from server-side rendered block: https://github.com/woocommerce/woocommerce/pull/42946. It should be extracted as util if we want to implement across multiple blocks).
- [ ] Decide whether or not to stabilize the events.
- [ ] Document the payload for each event.

**Comment by kkoteen** [comment]
Hi @kmanijak - 
Can you provide feedback on this issue? Thanks! 

The bit that needs a closer look: This is not a simple missing event bug anymore. Trunk still uses the experimental event system and one inconsistency was fixed, but the remaining open question is architectural: whether to keep, unify, or stabilize these extension hooks and how to define their contract.

**Comment by vladolaru** [comment]
Hi @kmanijak, I rechecked this against current trunk. I think this should stay open as the parent contract/architecture issue rather than being reduced to one missing event.

Current trunk still has both event surfaces:

- `useStoreEvents()` dispatches `@wordpress/hooks` actions with the `experimental__woocommerce_blocks-*` and `experimental__woocommerce_blocks-checkout-*` prefixes: [use-store-events.ts#L13-L52](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/client/blocks/assets/js/base/context/hooks/use-store-events.ts#L13-L52)
- The internal developer docs still describe those as actions fired while using WooCommerce Blocks and list specific store/checkout events: [feature-flags-and-experimental-interfaces.md#L113-L232](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/client/blocks/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md#L113-L232)
- The built-in Google Analytics integration consumes the experimental actions for checkout, cart, product-list, product-view, product-search, product-render, and store-notice events: [constants.ts#L1-L2](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/client/blocks/assets/js/extensions/google-analytics/constants.ts#L1-L2), [index.ts#L31-L112](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/client/blocks/assets/js/extensions/google-analytics/index.ts#L31-L112), [index.ts#L133-L284](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/client/blocks/assets/js/extensions/google-analytics/index.ts#L133-L284)
- Native DOM events also exist for overlapping frontend use cases, including add-to-cart, product-list-rendered, and viewed-product: [legacy-events.ts#L47-L83](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/client/blocks/assets/js/base/utils/legacy-events.ts#L47-L83)
- Product Collection has its own native event helpers for `wc-blocks_product_list_rendered` and `wc-blocks_viewed_product`: [product-collection/legacy-events.ts#L44-L63](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/client/blocks/assets/js/blocks/product-collection/legacy-events.ts#L44-L63)

The related history points in the same direction:

- #42946 added `experimental__woocommerce_blocks-cart-add-item` to the Interactivity API Product Button path.
- #43177 reverted that change after it caused compatibility problems.
- #42924 was later closed with Product Collection consumers directed toward native JS events (`wc-blocks_adding_to_cart`, `wc-blocks_added_to_cart`, `wc-blocks_viewed_product`, and `wc-blocks_product_list_rendered`).
- #53390 is still open for a concrete missing `experimental__woocommerce_blocks-cart-add-item` dispatch.
- #45952 is still open and would add more cart events, which makes the contract decision more important before expanding the surface further.

My recommendation is to keep #42985 open and make the next step an explicit contract decision:

1. If native DOM events are the canonical public frontend event surface, update the experimental-interface docs to say which `wp.hooks` actions are deprecated or unsupported for Product Collection / Interactivity API paths, document the native event payloads, and close/split the remaining missing experimental-hook issues accordingly.
2. If `experimental__woocommerce_blocks-*` actions remain a supported compatibility API, add a docs-to-dispatch audit matrix and regression coverage, then fix the known parity gaps across Product Collection, Mini-Cart / Interactivity API paths, and documented events with no current dispatch site.
3. Pause or scope new event additions, such as #45952, against that decision so we do not expand an unstable contract.

The important point is that this is no longer just "fire this event from one block." We have an experimental `wp.hooks` surface that extensions and built-in analytics consume, plus a native event surface that Product Collection/iAPI paths have already moved toward. We need to choose and document the supported contract before doing more piecemeal event work.

**Comment by kmanijak** [comment]
Hey @vladolaru, thanks for verifying it's still an issue.

I want to make sure I understand your recommendation. The original issue is already about deciding whether we keep the duplicated events as-is or move toward Core/native events with follow-up actions depending on that decision.

Is your suggestion mainly that we keep this issue open with the same decision to make, or are you also recommending that we lean toward one of those options?

> The related history points in the same direction:

Could you clarify what direction you mean here? To me, the linked PRs/issues seem to show both options: some adding experimental events, and others reverting or directing consumers toward native events.

**Comment by kkoteen** [comment]
[vladolaru](https://github.com/vladolaru) just a friendly reminder here - see the comment above. TY!

**Comment by vladolaru** [comment]
@kmanijak, yes, I the PRs point toward both directions because both directions are currently active and in use - that is the conundrum this issue is trying to resolve, IIUC. And yes, keep this issue open to make a decision and, of course, to act on that decision (even if that means creating new focused issues).

About what is the better option, I honestly can't say since there are pluses and minuses with both. But I would expect that people much closer to blocks and how they are used in the wild, what feedback trickled in, where are the big friction points, can balance those and make a decision (for better or worse).
