### ISSUE TITLE
Customizer - disable Checkout menu item when the Checkout block is set as the default

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#44120]
**Description:** users with a Classic theme can access a Checkout section in the Customizer (Appearance > Customize > WooCommerce > Checkout). This creates a suboptimal and confusing experience, as the settings/content changes in this section aren't reflected in the Checkout block. See #35499

<img width="1399" alt="Captura de ecrã 2024-01-26, às 14 48 47" src="https://github.com/woocommerce/woocommerce/assets/3380168/f42a9e70-9f37-4a2d-8875-e77ffedbb103">

We should redirect the user to the Editor rather than supporting two different experiences to accomplish the same goal. 

**Acceptance criteria:**
When the Checkout block is set as the default
- [x] Disable the Checkout menu item in the Customizer
- [x] Add a notification in the panel redirecting the user to the Editor with the following copy: Checkout can be customized in the Editor with your active theme.
- [ ] If the store has a block theme, the user should be redirected to the template
- [x] If the store has a classic theme, the user should be redirected to the page

<img width="1656" alt="300586822-8d8d7c70-d792-402e-a9e6-4f1c3d03c286" src="https://github.com/woocommerce/woocommerce/assets/3380168/2cf11c38-7a69-44aa-a43d-985b9a801b4f">

Figma: GzMPKqA4Fm2ZUDH1WVyTGs-fi

**Comment by pmcpinto** [comment]
@elizaan36 feel free to add the Figma file with the design specs for the notification. Thanks.

**Comment by elizaan36** [comment]
Thanks for the ping, I updated the notice design to align with the Calypso design system.

<img width="1656" alt="Frame 2" src="https://github.com/woocommerce/woocommerce/assets/5121465/8d8d7c70-d792-402e-a9e6-4f1c3d03c286">

Here's the Figma: GzMPKqA4Fm2ZUDH1WVyTGs-fi

**Comment by elizaan36** [comment]
I think we can experiment with the copy but here's what I have so far:

> Checkout can be customized _in the Editor_ with your active theme.

**Comment by pmcpinto** [comment]
Thanks. I'll update the issue description with the copy and the new notice design.

**Comment by nielslange** [comment]
@pmcpinto The acceptance criteria state _"If the store has a block theme, the user should be redirected to the template"_. However, the Customizer is not visible when using a block theme:

![Image](https://github.com/woocommerce/woocommerce/assets/3323310/e5979012-d488-4c53-895d-ed31e195139d)

Shall I remove that acceptance criteria?

**Comment by nielslange** [comment]
@elizaan36 I've picked up this issue and implemented it. On your design, it appears that the text is bold, and the underline is black. For other notices, e.g. the incompatible extension notice, we're using a regular font weight and links are displayed in blue. What are your thoughts on this? Do you want me to stick to your design proposal or the styles we're using in other areas? Here's a comparison of what I mean:

<table>
<tr>
<td valign="top">This PR:
<br><br>
<img width="306" alt="Screenshot 2024-03-12 at 23 31 11" src="https://github.com/woocommerce/woocommerce/assets/3323310/69e38ea0-b7f3-4ffe-b27d-779b8465e660">
</td>
<td valign="top">Other notices:
<br><br>
<img width="288" alt="Screenshot 2024-03-12 at 23 30 40" src="https://github.com/woocommerce/woocommerce/assets/3323310/2c4267cd-433e-475d-9225-80ecaf0a54a3">
</td>
</tr>
</table>

**Comment by elizaan36** [comment]
> What are your thoughts on this? Do you want me to stick to your design proposal or the styles we're using in other areas?

hey @nielslange, I was going back and forth on whether we should use the Calypso design system for this notice (since it appears in the customizer) but I don't think it's necessary. Let's use the styles we're using in other areas as shown in the PR - regular font weight and blue links.

**Comment by nielslange** [comment]
> hey @nielslange, I was going back and forth on whether we should use the Calypso design system for this notice (since it appears in the customizer) but I don't think it's necessary. Let's use the styles we're using in other areas as shown in the PR - regular font weight and blue links.

Thanks for your reply, @elizaan36. In this case, I'll keep the styles as I've implemented them already. The notice styles in the Customizer are identical with the notice styles in the editor.

**Comment by medmans** [comment]
Hello, I'm using beTheme and waiting for this fix to go on production.

**Comment by alancontino** [comment]
This issue was posted in the GH problem reported #35499  - an issue which still exists and does not relate to this issue referenced as the "solution".     Checkout Phone Settings in the Woocommerce Block editor do NOT work regardless of customizer settings.
