### ISSUE TITLE
[New Product Editor Issue]: When a global Attribute has more than 10 values, only 10 show when adding them to product variations

### ISSUE THREAD

**Issue by filipanoscampos** [woothemes/woocommerce#49212]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When the new Product Editor is enabled, and we try to set up Variations for a product from a global Attribute with more than 10 values et, only 10 are loaded in the Editor.
if the new editor is deactivated, all values are loaded and can be added.

**Note:** This has been addressed in 9.1.2 partially, where it is fixed in the **Add new** modal, but not in the **Edit modal**, see this comment: https://github.com/woocommerce/woocommerce/issues/49212#issuecomment-2230516804

### Expected behavior

The values should all load, and users should be able to add them as product variation values.

### Actual behavior

Only 10 values are loaded, regardless of the number of Attribute values set.

### Steps to reproduce

1. Products > Attributes
2. Create an Attribute with 11 values
3. Make sure that the new Product Editor is enabled 
4. Create a product 
5. Proceed to add a Variation from the previously defined Attribute
6. Notice that only 10 values are loaded and the missing values can't be searched for

Example:
![Screenshot 2024-07-06 at 13 28 47](https://github.com/woocommerce/woocommerce/assets/2540430/dc3232a2-ce96-4309-b76f-cdef0a90fd01)

Yet, only 10 values show in the Product Editor:
![Screenshot 2024-07-06 at 13 28 43](https://github.com/woocommerce/woocommerce/assets/2540430/eb6fd149-40f8-49c2-8e61-1ce63d8d459c)

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://4drachma.com
Site address (URL): https://4drachma.com
WC Version: 9.0.2
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.7.4
Log Directory Writable: ✔
WP Version: 6.5.5
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 8.1.29
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 8.7.1
OpenSSL/1.1.1w

SUHOSIN Installed: –
MySQL Version: 10.6.15-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 9.0.2
WC Database Prefix: wp_
Total Database Size: 140.46MB
Database Data Size: 81.50MB
Database Index Size: 58.96MB
wp_woocommerce_sessions: Data: 2.02MB + Index: 0.08MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 15.03MB + Index: 18.19MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 10.05MB + Index: 8.05MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gla_attribute_mapping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_budget_recommendations: Data: 0.19MB + Index: 0.14MB + Engine InnoDB
wp_gla_merchant_issues: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_shipping_rates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_jetpack_sync_queue: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mo_openid_linked_user: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 2.25MB + Index: 0.11MB + Engine InnoDB
wp_postmeta: Data: 31.17MB + Index: 21.41MB + Engine InnoDB
wp_posts: Data: 16.19MB + Index: 4.75MB + Engine InnoDB
wp_social_users: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_terms: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.20MB + Index: 0.14MB + Engine InnoDB
wp_term_taxonomy: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_tinvwl_analytics: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_tinvwl_items: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_tinvwl_lists: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_usermeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.45MB + Index: 0.41MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 2.52MB + Index: 4.19MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woo_shippment_provider: Data: 0.14MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 2486
customize_changeset: 134
custom_css: 1
elementor_library: 1
jetpack_migration: 2
jp_img_sitemap: 10
jp_img_sitemap_index: 3
jp_sitemap: 7
jp_sitemap_master: 7
jp_vid_sitemap: 7
nav_menu_item: 125
ni-order-status: 2
page: 14
post: 89
product: 484
product_variation: 10644
revision: 356
shop_order_placehold: 1
wp_global_styles: 6
wp_navigation: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (23) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.2
CoBlocks: by GoDaddy – 3.1.12
Conditional Menus: by Themify – 1.2.5
WordPress.com Editing Toolkit: by Automattic – 4.27750
Google Listings and Ads: by WooCommerce – 2.7.5
Gutenberg: by Gutenberg Team – 18.6.1
Jetpack: by Automattic – 13.6-beta
Multiple Themes: by David Gewirtz – 7.1.1
Layout Grid: by Automattic – 1.8.4
Social Login, Social Sharing by miniOrange: by <a href="https://www.miniorange.com/">miniOrange</a> – 7.6.8
Ni WooCommerce Custom Order Status: by anzia – 2.2.4
Page Optimize: by Automattic – 0.5.5
Pinterest for WooCommerce: by WooCommerce – 1.4.2
Qikink Print On Demand and DropShipping: by Qikink – 1.0.2
String Locator: by InstaWP – 2.6.5
TI WooCommerce Wishlist: by TemplateInvaders – 2.8.2
WooCommerce Weight Based Shipping: by weightbasedshipping.com – 5.9.2
Advanced Shipment Tracking for WooCommerce: by zorem – 3.6.8
Min Max Quantity & Step Control for WooCommerce: by CodeAstrology Team – 6.4
1 Razorpay: Signup for FREE PG: by Team Razorpay – 4.6.7
WooCommerce.com Update Manager: by Automattic – 1.0.3
Variation Swatches for WooCommerce: by Emran Ahmed – 2.1.1
WooCommerce: by Automattic – 9.0.2

### Inactive Plugins (7) ###

Classic Editor: by WordPress Contributors – 1.6.3
Crowdsignal Forms: by Automattic – 1.7.2
Crowdsignal Polls & Ratings: by Automattic
Inc. – 3.1.1

Mailchimp for WooCommerce: by Mailchimp – 4.1
Product Image Zoom for WooCommerce: by wpbean – 1.05.4
Product Video Gallery for Woocommerce: by NikHiL Gadhiya – 1.4.2.7
WP Image Zoom: by SilkyPress – 1.57

### Dropin Plugins () ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Must Use Plugins (1) ###

wpcomsh-loader.php: by  –

### Settings ###

API Enabled: –
Force SSL: –
Currency: INR (₹)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 1 MB

### WC Pages ###

Shop base: #1004 - /
Cart: #845 - /cart/
Checkout: #847 - /checkout/
My account: #849 - /my-account/
Terms and conditions: #1198 - /1198-2/

### Theme ###

Name: Storefront
Version: 4.6.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
pattern-toolkit-full-composability
product-pre-publish-modal
settings
async-product-editor-category-field
launch-your-store
product-editor-template-system

Daily Cron: ✔ Next scheduled: 2024-07-07 12:38:59 +05:30
Options: ✔
Notes: 58
Onboarding: completed

### TI WooCommerce Wishlist Templates ###

Overrides: –

### Action Scheduler ###

Canceled: 2
Oldest: 2024-06-26 17:56:37 +0530
Newest: 2024-07-06 13:58:54 +0530

Complete: 44,741
Oldest: 2024-06-05 19:56:37 +0530
Newest: 2024-07-06 19:35:24 +0530

Failed: 351
Oldest: 2024-03-02 11:17:50 +0530
Newest: 2024-06-30 18:53:52 +0530

Pending: 5
Oldest: 2024-07-06 19:45:24 +0530
Newest: 2024-07-07 17:44:29 +0530

### Status report information ###

Generated at: 2024-07-06 19:41:17 +05:30
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by limewebdevelopment** [comment]
We've had two customers reporting this issue also.

**Comment by NovA-80** [comment]
The issue is also valid for the list of attribute values on Product/Organization/Attributes. Only first 10 are shown in the dropdown list.

**Comment by louwie17** [comment]
Thanks for creating this issue, this should be addressed in WooCommerce 9.1.0 in this change:
https://github.com/woocommerce/woocommerce/pull/48616

**Comment by louwie17** [comment]
Let me know if you can still reproduce it in 9.1.0? and if not we can close this issue.

**Comment by NovA-80** [comment]
In 9.1.2, the list of attribute values on Product/Organization/Attributes still shows only first 10...

**Comment by louwie17** [comment]
> In 9.1.2, the list of attribute values on Product/Organization/Attributes still shows only first 10...

Strange, I see it working for me. I can reproduce the above error in 9.0.2 and when I update to 9.1.2 I can't reproduce it, and it works correctly:
9.0.2:
![Screenshot 2024-07-16 at 8 53 07 AM](https://github.com/user-attachments/assets/c9f39ac2-4fc9-40ab-8ec5-69e049d3aa13)
9.1.2:
![Screenshot 2024-07-16 at 8 54 43 AM](https://github.com/user-attachments/assets/04864f98-3f3f-4b4c-9a9b-8bd4070dd945)

**Comment by NovA-80** [comment]
Hm, it seems that the problem fixed in the dialog for adding **New** attribute. But it remains in the dialog for **Editing** the existing attribute. These dialogs use different controls for values selection.

Global attribute values, 12 terms (from Beige to Yellow):
![Global attribute values](https://github.com/user-attachments/assets/5dfa8879-fb7c-412f-9b0c-5b006a9b03c0)

Adding new attribute to a product. 12 terms listed (from Beige to Yellow):
![2024-07-16_12-58-44](https://github.com/user-attachments/assets/7ba45c08-87f3-4ef8-9c1f-beed2e97e415)

Editing the attribute. Only 10 values listed (from Beige to Red):
![2024-07-16_12-51-42](https://github.com/user-attachments/assets/1b01aa01-8071-49cb-b73b-e5995726858e)

**Comment by louwie17** [comment]
Aaah good catch @NovA-80, we do actually have some issues in place to also update the editing modals with the same dropdowns as the `Add new` modal.
I will leave this issue open in the case until that is addressed.
