### ISSUE TITLE
[Checkout Block] Email field is case sensitive and removes coupon code

### ISSUE THREAD

**Issue by namiokuzono** [woothemes/woocommerce#50329]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The WooCommerce email field (using Woo Blocks) is case-sensitive when usage restrictions for emails are applied on coupons. As a result, an email with different letter casing than the one specified in the coupon usage restriction fails validation during the checkout process when finalizing payment, causing the coupon to be removed.

It seems like the Coupon settings do not allow any capital email address, but the Block Checkout allows capital letters in the email, which then causes the coupon to be removed when trying to place an order.

![https://cln.sh/mlHdmDKB](https://cln.sh/mlHdmDKB+)
Image link: https://cln.sh/mlHdmDKB

### Expected behavior

When an allowed email address is set as a usage restriction on a coupon, the coupon should remain valid and be applied during the entire checkout process, regardless of the email address casing entered by the customer.

### Actual behavior

When an email with different casing (e.g., TEST@TEST.com instead of test@test.com) is entered in the email field of the checkout using Woo Blocks, the coupon initially applies. However, the coupon is removed upon the payment process due to case sensitivity in the email field.

### Steps to reproduce

1. Set an allowed email as a usage restriction on a coupon in WooCommerce test@test.com
2. Go to checkout (using Blocks).
3. Enter an email in the checkout field with different casing TEST@TEST.com
4. Apply the coupon. It will initially apply successfully.
5. Proceed to place an order 
6. Observe that the coupon is removed before completing the payment.

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by namiokuzono** [comment]
Originally reported in 8428486-zen

**Comment by mansi-shah-2248** [comment]
Smart Coupons plugin users are facing this issue (following this).

[This pull request](https://github.com/woocommerce/woocommerce/pull/48611) should fix this issue as tried locally.

**Comment by brendanofarrell** [comment]
> Smart Coupons plugin users are facing this issue (following this).
> 
> [This pull request](https://github.com/woocommerce/woocommerce/pull/48611) should fix this issue as tried locally.

This does not fix the case-sensitive nature of the email address field.

**Comment by namiokuzono** [comment]
Prioritization request noted in this conversation: p1723022407275129-slack-C07414X4N

**Comment by wavvves** [comment]
Hi @namiokuzono, thank you for reporting this. I dug in to the code to make sure this wasn't a regression introduced by recent coupon work, and it seems to be unrelated, part of the validation occurring during place order, which means probably this has existed for quite some time now.

Pinging @opr about escalating priority, since this is a diverging behaviour from classic checkout flow and probably a quick fix

**Comment by opr** [comment]
@wavvves I think this would be a good bug to fix for the porter next week if you think you can take care of it. If it's done before Wednesday it can go into 9.3
