### ISSUE TITLE
Error: _load_textdomain_just_in_time Called Incorrectly for WooCommerce in WP 6.7.0-beta

### ISSUE THREAD

**Issue by kmjamsheed0** [woothemes/woocommerce#51843]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I'm currently running WordPress 6.7.0-beta, and I'm encountering the following error when visiting a product page or interacting with WooCommerce menus:

Function _load_textdomain_just_in_time was called incorrectly. Translation loading for the woocommerce domain was triggered too early. This is usually an indicator for some code in the plugin or theme running too early. Please see [Debugging in WordPress](https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/) for more information. (This message was added in version 6.7.0.)

The error seems to indicate that the translation loading for WooCommerce is happening too early in the execution order, likely due to a plugin or theme code being triggered prematurely.

### Expected behavior

No errors related to translation loading should be triggered during normal WooCommerce usage.

### Actual behavior

 The error message about _load_textdomain_just_in_time is displayed, indicating that translation loading was triggered too early.

### Steps to reproduce

1. Install WordPress 6.7.0-beta.
2. Install and activate WooCommerce.
3. Visit a product page or interact with WooCommerce menus.
4. The error message appears on the screen or in the debug log.

### WordPress Environment

WordPress Version: 6.7-beta1-59156
WooCommerce Version: 9.3.3
Theme: Storefront

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by webdados** [comment]
I can confirm this happens with WooCommerce 9.4.0-beta.2 and WordPress 6.7-beta1-59158

The notice has since been updated to 

`_load_textdomain_just_in_time` means that WooCommerce hasn't yet called `load_plugin_textdomain` (which is happening correctly on `init`) but a i18n function with the `woocommerce` textdomain was already called and WordPress is trying to load the domain "just in time".

In this case, the first string loaded is "WooCommerce" which makes me to believe this is caused by a call to `get_plugin_data` before `init`, because this functions tries to get the plugin name localized, unless [you `pass` false to its third parameter](https://developer.wordpress.org/reference/functions/get_plugin_data/) (which is how I fixed it on my plugins).

**Comment by coreymckrill** [comment]
I haven't been able to replicate the error log using WC 9.3.3 or 9.4 beta.2 along with WP 6.7-beta2. @kmjamsheed0 @webdados do you still get this with the WP beta2? If so, are there any other plugins involved? Could you provide some more detailed reproduction steps?

**Comment by kmjamsheed0** [comment]
Hi @coreymckrill ,

I'm currently not experiencing the error anymore. I'm using WooCommerce 9.4.0-beta.2 and WordPress 6.7-beta2-59195, and everything seems to be working fine now. It appears that the issue has been resolved with these updates.

Thank you for checking in!

**Comment by webdados** [comment]
Just made a fresh install to be sure it was not caused by my dev (messy) install 😂 and the notice is showing up

- Using local
- WordPress 6.7-beta2-59198 set to Portuguese
- WooCommerce 9.4.0-beta.2

![Image](https://github.com/user-attachments/assets/f785334b-b686-4cb9-b0f6-00892a18cabd)

<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 9.4.0-beta.2
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.8.2
Log Directory Writable: ✔
WP Version: 6.7-beta2-59198
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: pt_PT
External object cache: –

### Server Environment ###

Server Info: nginx/1.26.1
PHP Version: 8.3.11
PHP Post Max Size: 1.000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 8.6.0
(SecureTransport) LibreSSL/3.3.6

SUHOSIN Installed: –
MySQL Version: 8.0.16
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

attachment: 1
page: 7
post: 2
revision: 1
wp_navigation: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (1) ###

WooCommerce: by Automattic – 9.4.0-beta.2

### Inactive Plugins (2) ###

WooCommerce Beta Tester: by WooCommerce – 2.3.2
WordPress Beta Tester: by WordPress Upgrade/Install Team – 3.5.6

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 186 B

### WC Pages ###

Shop base: #7 - /loja/
Cart: #8 - /carrinho/ -  Contains the woocommerce/cart block
Checkout: #9 - /finalizar-compra/ -  Contains the woocommerce/checkout block
My account: #10 - /minha-conta/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Four
Version: 1.2
Author URL: https://pt.wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: /Users/marcoalmeida/Documents/Websites/_local/app/public/wp-content/plugins/woocommerce/templates/block-notices/error.php
/Users/marcoalmeida/Documents/Websites/_local/app/public/wp-content/plugins/woocommerce/templates/block-notices/notice.php
/Users/marcoalmeida/Documents/Websites/_local/app/public/wp-content/plugins/woocommerce/templates/block-notices/success.php


### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: product-data-views
experimental-blocks
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system
blueprint
reactify-classic-payments-settings
use-wp-horizon

Daily Cron: ✔ Next scheduled: 2024-10-10 09:54:42 +00:00
Options: ✔
Notes: 57
Onboarding: completed

### Action Scheduler ###

Complete: 7
Oldest: 2024-10-09 09:55:50 +0000
Newest: 2024-10-09 10:01:34 +0000

Pending: 1
Oldest: 2024-10-10 09:55:50 +0000
Newest: 2024-10-10 09:55:50 +0000


### Status report information ###

Generated at: 2024-10-09 10:03:00 +00:00
```
</details>

**Comment by kmjamsheed0** [comment]
Hi @coreymckrill 

After further testing, I’m unfortunately encountering the error again, but this time it seems to be happening specifically when I visit a translated WooCommerce page.

I'm still using WooCommerce 9.4.0-beta.2 and WordPress 6.7-beta2-59195, but the issue seems tied to the translation aspect of WooCommerce. Could you please advise if there have been any related updates?

Thank you for checking in!

**Comment by webdados** [comment]
Yeah, probably people are testing with WordPress set to English :-) They need to change the language.

**Comment by kmjamsheed0** [comment]
> Yeah, probably people are testing with WordPress set to English :-) They need to change the language.

@webdados  That makes sense! It seems like the issue is more noticeable when using translation.

**Comment by webdados** [comment]
It's not only mode noticeable as it is unique to non English.
"Load text domain" does nothing if WordPress is set to the default language.

**Comment by webdados** [comment]
Actually it looks worse, because the translation is not loading at all (still using the same fresh website mentioned above). Look as WooCommerce strings are the only one in English and not Portuguese:

![Image](https://github.com/user-attachments/assets/4b78747b-b5d0-4f68-add0-8de0cb1746e6)

**Comment by kmjamsheed0** [comment]
Also, I can't place an order from the translated checkout page because the cart is stuck in an endless AJAX loading loop in the order review section.

**Comment by webdados** [comment]
> Also, I can't place an order from the translated checkout page because the cart is stuck in an endless AJAX loading loop in the order review section.

That's because of the PHP notice. It's normal. Once the underlying issue is solved, that will go away.

The thing is... will the be fixed in the final release of 9.4? I really hope so.

**Comment by kmjamsheed0** [comment]
I solved the issue in my personal project by firing the `load_plugin_textdomain` function after WooCommerce setup. I achieved this by using the `after_setup_theme` hook:

```php
$this->loader->add_action( 'after_setup_theme', $plugin_i18n, 'load_plugin_textdomain' );

```

Alternatively, you can use any hook that fires after the ```plugins_loaded``` hook, which ensures that all plugins are fully loaded.

**Comment by webdados** [comment]
WordPress 6.7 requires that the text domains are only loaded on `init` or later.
https://github.com/WordPress/wordpress-develop/blob/trunk/src/wp-includes/l10n.php#L1344

**Comment by swissspidy** [comment]
Hi all,

For some context, this is a new change to prevent plugins from loading translation right away, without waiting for more parts of WordPress being loaded. A dev-note will be published soon with more details.

In WooCommerce, an initial change to address this was merged back in #47113, but since then there have been a couple of regressions. 

/cc @rodelgc @senadir

The 2 newly introduced issues I just spotted:

**`PatternsRegistry` constructor calls `__()`**

https://github.com/woocommerce/woocommerce/blob/0951f5fe1be19167ea3f02aa12735ed6f62257d7/plugins/woocommerce/src/Blocks/Patterns/PatternRegistry.php#L16-L37

Suggested fix: move out of the constructor into a new private `get_category_labels()` method.

**`BlockPatterns` constructor -> `PatternsHelper` -> `PatternsDictionary::get()``**

https://github.com/woocommerce/woocommerce/blob/0951f5fe1be19167ea3f02aa12735ed6f62257d7/plugins/woocommerce/src/Blocks/BlockPatterns.php#L85

https://github.com/woocommerce/woocommerce/blob/0951f5fe1be19167ea3f02aa12735ed6f62257d7/plugins/woocommerce/src/Blocks/AIContent/PatternsHelper.php#L97-L101

This one also causes an unnecessary `get_option()` call on every page load, which is a bit wasteful.

This can be initialized late instead.

Also, the `empty( $default_patterns_dictionary )` check is pointless. The array can never be empty, as it's static.

**Comment by webdados** [comment]
@swissspidy in your analysis/tests has WooCommerce loaded the translations at all?
In my [test setup](https://github.com/woocommerce/woocommerce/issues/51843#issuecomment-2401886145) the [translation for WooCommerce doesn't even load](https://github.com/woocommerce/woocommerce/issues/51843#issuecomment-2402344301).

/cc @rodelgc @senadir 
Have you looked into this? Do a fresh WordPress + WooCommerce + WordPress beta tester + WooCommerce beta tester, WP_DEBUG set to true, change the language to something else (Portuguese, for example). You'll see the notice and (as per my tests) **WooCommerce will not load the translations**, although the files were downloaded.
If this is confirmed, WooCommerce 9.4 cannot be shipped with this issue.

![Image](https://github.com/user-attachments/assets/780e369d-5101-4949-8113-8f9c46e806a1)
![Image](https://github.com/user-attachments/assets/4170ac9a-017b-4b82-bb40-78eb291ea0d5)

**Comment by swissspidy** [comment]
> in your analysis/tests has WooCommerce loaded the translations at all?

I see, this is an interesting scenario!

First and foremost: when WooCommerce fixes the two issues I pointed out causing this PHP warning, then the translations will be loaded fine. So ideally, these issues are fixed soon and everyone is happy.

The problem is, right now the loading order is as follows:

1. WooCommerce triggers `_load_textdomain_just_in_time` too early
2. Then, in https://github.com/woocommerce/woocommerce/blob/e148229edbface57b45c9dd73ee58337b80a3872/plugins/woocommerce/includes/class-woocommerce.php#L874-L876 it calls `unload_textdomain()`, removing all those loaded translations again.
3. Because WP 6.7 changes how `load_plugin_textdomain()` works, the following `load_plugin_textdomain()` call in WooCommerce doesn't do anything anymore.

I don't know why that `unload_textdomain()` call exists, but the general idea of loading translations just to unload & load them again is a bit pointless...

Anyhow, I just opened #52055 to address this (again).

In the meantime I'll also look into whether we need to further change `load_plugin_textdomain()` in WordPress core, as we don't want to break any plugins :-)

**Comment by webdados** [comment]
Great analysis @swissspidy 

I hope the Woo team, after my feedback about the translations not being loaded, and your in-depth analysis on the root of the issue, can make sure WooCommerce 9.4 does not ship with this bug, as there are thousands of non-English shops around the world. I guess one of the pitfalls here is that most stuff is tested with WP set to English.

> In the meantime I'll also look into whether we need to further change load_plugin_textdomain() in WordPress core, as we don't want to break any plugins :-)

I must confess I'm fixing ALL my 30+ plugins because of this, but it's my fault. WP didn't break my plugin. I was just loading stuff too early.

Also I believe the `unload_textdomain()` call is an edge case and not many plugins will be broken.

**Comment by dinhtungdu** [comment]
FYI: The `unload_textdomain` call was added in this PR: https://github.com/woocommerce/woocommerce/pull/15450.

**Comment by webdados** [comment]
9.4.0-rc.1 still hasn't got this fixed.

I don't think WooCommerce 9.4 can be released with a bug that will cause all international shops to NOT load the plugin translations.

**Comment by swissspidy** [comment]
The #52055 PR was milestoned for 9.5.0, FWIW.

**Comment by coreymckrill** [comment]
There is an rc.2 scheduled for next week that I believe will have fixes for this issue. See also the "Known issue" section of the [prerelease updates](https://developer.woocommerce.com/2024/09/20/woocommerce-9-4-pre-release-updates/) post.

**Comment by webdados** [comment]
> The [#52055](https://github.com/woocommerce/woocommerce/pull/52055) PR was milestoned for 9.5.0, FWIW.

So every non-english website in the world will turn to English on 9.4 😂

> There is an rc.2 scheduled for next week that I believe will have fixes for this issue. See also the "Known issue" section of the [prerelease updates](https://developer.woocommerce.com/2024/09/20/woocommerce-9-4-pre-release-updates/) post.

I really hope so.

**Comment by swissspidy** [comment]
@webdados No, that‘s not true. It only means you will see a warning if you haven‘t turned off warnings (which you should do on a production site)

**Comment by barryhughes** [comment]
> > The https://github.com/woocommerce/woocommerce/pull/52055 PR was milestoned for 9.5.0, FWIW.
> 
> So every non-english website in the world will turn to English on 9.4 😂

Our plan is to bring this (and another related fix) into 9.4. Whenever a PR is merged to `trunk`, though, a milestone is automatically set, as happened here. We adjust these on a case-by-case basis and cherry-pick the changes as needed into the active release branch.

**Comment by webdados** [comment]
@swissspidy Can't you replicate this? https://github.com/woocommerce/woocommerce/issues/51843#issuecomment-2415920213

**Comment by coreymckrill** [comment]
This should be fixed in [9.4.0-rc.2](https://github.com/woocommerce/woocommerce/releases/tag/9.4.0-rc.2)

**Comment by webdados** [comment]
I can confirm it is fixed on rc.2 and the WooCommerce translations are now loading (https://github.com/woocommerce/woocommerce/issues/51843#issuecomment-2415920213)

**Comment by shohel** [comment]
This issue still exists in WooCommerce version `9.8.1` with my site's language set to English.

> Notice: Function _load_textdomain_just_in_time was called incorrectly. Translation loading for the woocommerce domain was triggered too early. This is usually an indicator for some code in the plugin or theme running too early. Translations should be loaded at the init action or later. Please see [Debugging in WordPress](https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/) for more information. (This message was added in version 6.7.0.)

**Comment by barryhughes** [comment]
Hi @shohel,

This issue has been closed, and so, to get your bug report in front of the correct team it's probably best to create a fresh one. You can certainly link back to this issue, though.

> Notice: Function _load_textdomain_just_in_time was called incorrectly. Translation loading for the woocommerce domain was triggered too early. 

Please also note that this *could* be a problem in WooCommerce itself, or it may not be. It is, for example, possible for other plugins to make WooCommerce do things earlier in the request than it would normally do itself, which could lead to this problem.

Therefore, definitely do take the time to perform the usual debugging and conflict testing steps before logging a fresh bug report.

- [woocommerce.com/document/how-to-test-for-conflicts](https://woocommerce.com/document/how-to-test-for-conflicts/)
- [woocommerce.com/documentation/woocommerce/get-help/troubleshooting-get-help](https://woocommerce.com/documentation/woocommerce/get-help/troubleshooting-get-help/)

Thanks!
