### ISSUE TITLE
On mobile Checkout block, terms checkbox is rendered after the summary, separated from other fields

### ISSUE THREAD

**Issue by senadir** [woothemes/woocommerce#53063]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

We recently added the order summary to below Checkout so it's displayed twice, once before Checkout and once below Checkout. Yet in this iteration, we seem to render it above terms and condition checkbox, which breaks the follow, and makes it easy to miss, especially if you're using a payment method that will redirect directly from the payment method body (like PayPal and Cash App).

![Image](https://github.com/user-attachments/assets/9f4275a1-fb83-4933-8590-cde14faf8b98)

![Image](https://github.com/user-attachments/assets/9b5d8564-b065-4cf9-9108-453453e716bc)

### Expected behavior

Summary should be the first element above Place order, if not possible, terms and conditions should be above it. But Ideally we fix this once by moving summary below.

### Actual behavior

Terms and conditions is rendered below summary.

### Steps to reproduce

1. Add Terms and condition block (it should be added).
2. Make it Checkbox.
3. Go on Checkout via mobile view, notice it is separate

### WordPress Environment

trunk

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by samueljseay** [comment]
@senadir I'm a little confused? Why does this break the flow? You cannot submit the form without accepting and if you do try you'll see the checkbox right in front of you to tick it.

To me it would be much easier to miss if its further up the page.

**Comment by pmcpinto** [comment]
Both options have pros & cons. I don't have a strong preference. @elizaan36  wdyt?

One thing we should fix is that moving the T&C block will also move the order summary. See this screenshot:

![Image](https://github.com/user-attachments/assets/9358439d-bcac-4333-9000-5c29cd0c50dc)

**Comment by senadir** [comment]
@pmcpinto The goal of the issue is to move the Terms and Condition block to be before the summary, I'm not sure if we should be moving the summary to above payment as well?

**Comment by elizaan36** [comment]
I don't think the T&Cs should be moved to before the summary, it needs to be adjacent to the Place order button. This is the expected behavior per the latest designs (screenshot) but I'd like to take a close look at this with Yoann since he'll be focused on mobile checkout to start. 

It feels like a very loooong scroll and wonder if we could make the Place order button sticky as it is on the Cart.

![Image](https://github.com/user-attachments/assets/9625a19b-40d4-4fb2-a275-1a46544a9623)

**Comment by pierorocca** [comment]
+1 to the sticky button and wide place order button. Attaching the WooPay mobile optimized sticky button here for reference. Last month's conversion rate for returning users was 74.3%.

![Image](https://github.com/user-attachments/assets/d3453b59-e312-45cf-b66d-7da25240fa99)

**Comment by pmcpinto** [comment]
> @pmcpinto The goal of the issue is to move the Terms and Condition block to be before the summary, I'm not sure if we should be moving the summary to above payment as well?

Sorry if I wasn't clear. When the user moves the Terms and Condition block position, this also impacts the Order Summary position on mobile. Here's another example:

![Image](https://github.com/user-attachments/assets/167b15b3-0a67-4eb6-b003-4eb497e72b7f)

Moving the Terms and Condition block position shouldn't impact the Order Summary location on mobile. Makes sense?

**Comment by senadir** [comment]
I like the design that Piero shared, I think we should move the terms and conditions to be part of the place order button/block.

**Comment by pierorocca** [comment]
Legally, if it's a browsewrap scenario, it MUST be in close proximity to the button that binds the shopper to the terms. I.e. right next to it. Being able to move it anywhere is not an option.

**Comment by pmcpinto** [comment]
> I like the design that Piero shared, I think we should move the terms and conditions to be part of the place order button/block.

+1.

> Legally, if it's a browsewrap scenario, it MUST be in close proximity to the button that binds the shopper to the terms. I.e. right next to it. Being able to move it anywhere is not an option.

Good point. Currently, users can place the T&C block anywhere within the Checkout Fields area, which creates more harm than good. Maybe we should only allow users to set the T&C block above or below the Place Order block.

We ended up discussing different topics on this thread:
- Place order design (sticky and wide approach). We need to consider when the Show a "Return to Cart" link option is enabled.
- Decouple the Order summary location on mobile from the T&C location.
- T&C location. Should we add it to the Place order block and merge the settings? 
 
It may be worth creating separate issues for each change.

**Comment by pierorocca** [comment]
> Good point. Currently, users can place the T&C block anywhere within the Checkout Fields area, which creates more harm than good.

Exactly. Legal/compliance related issues are an area where things can be locked down with good reason. Above or below the button placement within the block is a good approach. Note with and without the checkbox will require slightly different styling or editable styling for text alignment.

> Place order design (sticky and wide approach). We need to consider when the Show a "Return to Cart" link option is enabled.

I was shocked to see "Return to Cart" right next to the place order button. I've never seen that placement before and I don't think it's a good practice. What's the rationale behind that placement and not adhering to norms like having the cart in the header and having the header hide/unhide on scroll?

**Comment by pierorocca** [comment]
If there's no sticky button or sticky button is disabled, I'd also recommend allowing the T&Cs to be completely removed in case the merchant's design has policies prominently displayed in the site footer in a way that it's in very close proximity to the Place Order button. Shopify's standard is a footer based approach and it works well in practice.

**Comment by pierorocca** [comment]
@yjailin you mentioned T&Cs placement today in our chat. As part of my own onboarding onto Checkout, I'm reviewing this Blocked issue and noticed @elizaan36 wanted to review this with you. Adding you to the discussion if you haven't seen it yet as you had some ideas around policy placement and when sticky buttons are or are not appropriate.

**Comment by ralucaStan** [comment]
@pierorocca @elizaan36 the team marked this as priority high, which means we should prioritize this on the design backlog as well

**Comment by senadir** [comment]
Also because the design looks broken with no checkbox.

**Comment by pierorocca** [comment]
@yjailin it's worth having a look at this as well, which i think you may have been. When there's a checkbox, there's flexibility where it can be placed legally. When there isn't, the terms must be next to the place order button legally.

**Comment by yjailin** [comment]
Hello, providing my feedback on this!

> We need to consider when the Show a "Return to Cart" link option is enabled.

We should remove the Back to cart link. This topic comes up frequently and i think we should fix this quickly. We shouldn't have a way out of Checkout so close to the Place order button. A Cart Icon in the header is the right place to edit the order.


> Decouple the Order summary location on mobile from the T&C location.T&C location. Should we add it to the Place order block and merge the settings?

(1) Decoupling Order Summary mobile position with T&C Block is absolutely something we should do. 
We should merge T&C block's settings within the Action block. Best approach since this checkbox has to be checked in order to place the order. 

(2) Alternative on mobile could be to couple Order Summary with Place order button position, instead of T&C block. And allow buyer to place T&C block anywhere he wants. But i feel like option (1) makes **way** more sense.


> T&C as a checkbox

Is it something we actually want to allow? Just curious to understand the value of asking buyers to check this before placing the orders as It adds a lot of friction. If there's actual usecases, i don't mind keeping this option, it's just something i need to ask.


> Sticky T&C + Place order button

The idea is interesting but here's the trick: If the page has a lot of scrolling, sticky button eats a lot ot space on mobile. It makes sense in case of a very short page (like in WooPay) but not when Checkout's page is long to scroll. We would also need to make sure the sticky placeholder disappears when scrolling at the end of the page. It would not work with a checkbox.

![Image](https://github.com/user-attachments/assets/468be307-5ba4-48a1-a578-2911838ddee0)

My reco would be:
- Remove Back to cart link from the action block
- Move T&C settings inside action block

In case T&C is a checkbox box or not, we could have a different treatment. :) 
- Checkbox = before place order button, regular size
- No checkbox = After button, smaller size.
Let me know how you feel about this.

<img width="1031" alt="Image" src="https://github.com/user-attachments/assets/349189e8-fd8e-4270-8057-9ea7f465110f" />

**Comment by senadir** [comment]
If we want to couple them, how would that look in desktop? still the same?

**Comment by yjailin** [comment]
> > `(2) Alternative on mobile could be to couple Order Summary with Place order button position, instead of T&C block. And allow buyer to place T&C block anywhere he wants. But i feel like option (1) makes **way** more sense.
> 
> If we want to couple them, how would that look in desktop? still the same?

@senadir We would keep the Order Summary where it is on Desktop. My assumption was that we have to couple the bottom Order Summary with another block on mobile, to determine its position, since it's supposed to appear before the Place Order Button / T&C block.

The problem wit solution (2) is that we would not be able to have T&C between Order Summary and Place Order button. So i think (1) Merge T&C with Action block would be simplier.

**Comment by yjailin** [comment]
@senadir @pierorocca can you have a look at [this](https://www.figma.com/design/fsQtn884prBGas6UkruLd2/Checkout-Block-Explorations?node-id=1547-70412&t=GEriJgktm3NDtAG5-1)?

**Comment by pierorocca** [comment]
Makes perfect sense to me @yjailin. @senadir do you see any technical issues with that approach or problems it might cause with the dynamic place order button work?

**Comment by pierorocca** [comment]
Reviewed and confirmed this is still valid. Marking as ready for engineering.

Current evidence: Latest audit evidence: Checkout.
