### ISSUE TITLE
Bug - CSV Import Issue: Product Prices Not Updating as Expected

### ISSUE THREAD

**Issue by SnowshedD** [woothemes/woocommerce#54397]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Upload of inventory lists with prices and so on is not working.  No matter how many times we have reformed the CSV.

### Expected behavior

1. I should have been able to import my inventory list, especially as WOO supposedly fixed it with a corrected version.
2. Despite this issue, I should have been able to manual go in and put the price in to each of my products

### Actual behavior

1. The inventory is not importing all the information.  In particularly, the price of each product.
2. Manual input of the price for each product is not updating.

### Steps to reproduce

1. Go to product that you want to change the price on.
2. Click on Quick edit
3. Input the price in to the price section.
4. Click update.
5. NO UPDATE OCCURS

### WordPress Environment

<details>
<summary>click to expand</summary>

WordPress address (URL): http://snowsheddesigns.com
Site address (URL): http://snowsheddesigns.com
WC Version: 9.4.3
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.8.2
Log Directory Writable: ✔
WP Version: 6.7.1
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 8.2.27
PHP Post Max Size: 256 MB
PHP Time Limit: 120
PHP Max Input Vars: 3000
cURL Version: 8.2.1
OpenSSL/3.1.4

SUHOSIN Installed: –
MySQL Version: 8.0.39-30
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 9.4.3
WC Database Prefix: rkp_
Total Database Size: 25.42MB
Database Data Size: 18.60MB
Database Index Size: 6.82MB
rkp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
rkp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
rkp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
rkp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
rkp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
rkp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
rkp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
rkp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
rkp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
rkp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
rkp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
rkp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
rkp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
rkp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
rkp_actionscheduler_actions: Data: 2.52MB + Index: 2.66MB + Engine InnoDB
rkp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
rkp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
rkp_actionscheduler_logs: Data: 1.52MB + Index: 0.39MB + Engine InnoDB
rkp_aioseo_cache: Data: 0.16MB + Index: 0.03MB + Engine InnoDB
rkp_aioseo_crawl_cleanup_blocked_args: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
rkp_aioseo_crawl_cleanup_logs: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
rkp_aioseo_notifications: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
rkp_aioseo_posts: Data: 1.50MB + Index: 0.02MB + Engine InnoDB
rkp_aioseo_writing_assistant_keywords: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
rkp_aioseo_writing_assistant_posts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
rkp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
rkp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
rkp_duplicator_packages: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
rkp_gla_attribute_mapping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
rkp_gla_budget_recommendations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
rkp_gla_merchant_issues: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
rkp_gla_shipping_rates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
rkp_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
rkp_ic_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
rkp_iepa_mm_custom_theme: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
rkp_iepa_mm_menugrouplists: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
rkp_jetpack_sync_queue: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
rkp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
rkp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
rkp_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
rkp_options: Data: 5.08MB + Index: 0.30MB + Engine InnoDB
rkp_postmeta: Data: 2.48MB + Index: 0.41MB + Engine InnoDB
rkp_posts: Data: 2.44MB + Index: 0.23MB + Engine InnoDB
rkp_sgs_log_events: Data: 0.13MB + Index: 0.06MB + Engine InnoDB
rkp_sgs_log_visitors: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
rkp_stripe_tax_for_wc_calculate_tax: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
rkp_stripe_tax_for_wc_options: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
rkp_stripe_tax_for_wc_products: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
rkp_stripe_tax_for_wc_tax_codes: Data: 0.20MB + Index: 0.00MB + Engine InnoDB
rkp_stripe_tax_for_wc_tax_transactions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
rkp_term_relationships: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
rkp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
rkp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
rkp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
rkp_trp_gettext_en_us: Data: 0.41MB + Index: 0.45MB + Engine InnoDB
rkp_trp_gettext_original_meta: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
rkp_trp_gettext_original_strings: Data: 0.36MB + Index: 0.22MB + Engine InnoDB
rkp_userfeedback_survey_responses: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
rkp_userfeedback_surveys: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
rkp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
rkp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
rkp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
rkp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
rkp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
rkp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
rkp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
rkp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
rkp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
rkp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
rkp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
rkp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
rkp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
rkp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
rkp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
rkp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
rkp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
rkp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
rkp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
rkp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
rkp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
rkp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
rkp_wpforms_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
rkp_wpforms_payment_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
rkp_wpforms_payments: Data: 0.02MB + Index: 0.14MB + Engine InnoDB
rkp_wpforms_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
rkp_wpgmza: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
rkp_wpgmza_admin_notices: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
rkp_wpgmza_circles: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
rkp_wpgmza_image_overlays: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
rkp_wpgmza_maps: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
rkp_wpgmza_point_labels: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
rkp_wpgmza_polygon: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
rkp_wpgmza_polylines: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
rkp_wpgmza_rectangles: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

al_product: 1
attachment: 652
custom_css: 1
customize_changeset: 1
feedback: 2
nav_menu_item: 4
page: 9
post: 7
product: 136
revision: 26
wp_font_face: 36
wp_font_family: 12
wpforms: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (27) ###

All in One SEO: by All in One SEO Team – 4.7.7
Duplicator: by Duplicator – 1.5.11.2
eCommerce Product Catalog for WordPress: by impleCode – 3.3.44
Envira Gallery Lite: by Envira Gallery Team – 1.9.0
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 9.2.4
Google for WooCommerce: by WooCommerce – 2.9.2
Ibtana - Ecommerce Product Addons: by VowelWeb – 0.4.7.2
Ibtana - WordPress Website Builder: by VowelWeb – 1.2.4.8
Jetpack: by Automattic – 14.1
HubSpot All-In-One Marketing - Forms, Popups, Live Chat: by HubSpot – 11.1.75
Mailchimp for WooCommerce: by Mailchimp – 4.4.1
OptinMonster: by OptinMonster Popup Builder Team – 2.16.13
Otter – Page Builder Blocks & Extensions for Gutenberg: by ThemeIsle – 3.0.8
Pinterest for WooCommerce: by WooCommerce – 1.4.13 (update to version 1.4.14 is available)
Speed Optimizer: by SiteGround – 7.7.2
Security Optimizer: by SiteGround – 1.5.7
Stripe Tax - Sales tax automation for WooCommerce: by  – 1.1.5
TikTok: by TikTok – 1.3.0
TranslatePress - Multilingual: by Cozmoslabs
Razvan Mocanu
Madalin Ungureanu
Cristophor Hurduban – 2.9.2

UserFeedback Lite: by UserFeedback Team – 1.3.0
WooPayments: by WooCommerce – 8.6.0 (update to version 8.7.0 is available)
WooCommerce Shipping & Tax: by WooCommerce – 2.8.5 (update to version 2.8.6 is available)
WooCommerce: by Automattic – 9.4.3 (update to version 9.5.2 is available)
WordPress Importer: by wordpressdotorg – 0.8.3
SiteGround Central: by SiteGround – 3.3.1
WP Go Maps (formerly WP Google Maps): by WP Go Maps (formerly WP Google Maps) – 9.0.44
WPForms Lite: by WPForms – 1.9.2.3

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 2 MB

### WC Pages ###

Shop base: ❌ Page ID is set
but the page does not exist

Cart: ❌ Page ID is set
but the page does not exist

Checkout: ❌ Page ID is set
but the page does not exist

My account: ❌ Page ID is set
but the page does not exist

Terms and conditions: ❌ Page not set

### Theme ###

Name: Designer Artist
Version: 0.5.1 (update to version 0.5.2 is available)
Author URL: https://www.vwthemes.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: designer-artist/woocommerce/archive-product.php
designer-artist/woocommerce/checkout/form-checkout.php version 3.5.0 is out of date. The core version is 9.4.0
designer-artist/woocommerce/global/wrapper-end.php
designer-artist/woocommerce/global/wrapper-start.php
designer-artist/woocommerce/single-product.php

Outdated Templates: ❌
					
					
						Learn how to update					 |
					
						
					
					
						Clear system status theme info cache

### WooPayments ###

Version: 8.6.0
Connected to WPCOM: Yes
WPCOM Blog ID: 239886987
Account ID: acct_1QVdIeFhxLmzkMeG
Payment Gateway: Enabled
Test Mode: Disabled
Enabled APMs: card,link
WooPay: Disabled
WooPay Incompatible Extensions: No
Apple Pay / Google Pay: Enabled (product,cart,checkout)
Fraud Protection Level: basic
Multi-currency: Enabled
Auth and Capture: Disabled
Documents: Disabled
Logging: Enabled

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: product-data-views
experimental-blocks
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system
blueprint
reactify-classic-payments-settings
use-wp-horizon

Daily Cron: ✔ Next scheduled: 2025-01-12 14:31:31 -05:00
Options: ✔
Notes: 72
Onboarding: completed

### Action Scheduler ###

Complete: 5,414
Oldest: 2024-12-12 11:31:51 -0500
Newest: 2025-01-12 08:22:38 -0500

Failed: 1
Oldest: 2024-12-13 15:39:41 -0500
Newest: 2024-12-13 15:39:41 -0500

Pending: 14
Oldest: 2025-01-12 08:25:54 -0500
Newest: 2025-02-02 03:04:04 -0500

### Status report information ###

Generated at: 2025-01-12 08:22:58 -05:00
</details>

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by SnowshedD** [comment]
After a month of trying to get my inventory properly on my site, I am giving up.  I have wasted way too much time on this.  It should be user-friendly and easy to do.  And I can build a computer and still cannot get this to work.

**Comment by imanish003** [comment]
@snowshedd Thanks for reporting this issue. I understand you're having trouble with updating product prices through the CSV import. I can see that you are using WooCommerce 9.4.3. I followed the steps you mentioned on WooCommerce 9.4.3, but I am not able to reproduce the issue. Here is a video of me trying to reproduce the issue:

https://github.com/user-attachments/assets/d401e164-a826-4b18-abf7-11b7021b19a6

- Are you able to reproduce the issue when all other plugins are disabled except WooCommerce?
- Can you verify that format of the CSV is correct? You can find a sample CSV file [here](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/sample-data/sample_products.csv)
- Any error messages or warnings you encountered during the import process (either on-screen or in the logs).
- Do you have any sample CSV file that you can share with us to test/reproduce the issue? (you can redact any sensitive information)

**Comment by SnowshedD** [comment]
So you are telling me that you could input a price for my products?  If so, it is NOT working for me and seems to be blocked.  I tried it 12 times and not once did my input of the price for my individual products stay.

1) If I disable all other plugins, including ones that have nothing to do with my products, then my site goes down so that makes no sense.

2) Yes, I used a CSV that was created from my product list that your team created.  I took YOUR WOO CREATED list and exported as CSV per your instructions.

3) No error messages or warnings.  It just would NOT allow the price to be saved when I put it in and then said update.

4) See attached CSV from the data you provided from my original excel.  I have attached all of the lists including the ones you provided and then the converted one from your data.


￼￼￼
Joan Kloth-Zanard

Owner of SnowShed Designs
&
2nd Life 4 All
***@***.***
203-770-0318
www.snowsheddesigns.com
www.2ndLife4All.com
www.Injeaniusdesigns.com
www.keepinguinstitches.com

**Comment by imanish003** [comment]
@SnowshedD 

> So you are telling me that you could input a price for my products?  If so, it is NOT working for me and seems to be blocked.  I tried it 12 times and not once did my input of the price for my individual products stay.

Let me clarify - I tested with WooCommerce's [default sample products CSV](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/sample-data/sample_products.csv), not your specific products. With the sample data, both importing and updating prices worked as expected. To properly investigate the issue you're experiencing, it would be very helpful if you could share your CSV file so I can attempt to reproduce the problem with your actual data. (Please redact any sensitive information)

> See attached CSV from the data you provided from my original excel.  I have attached all of the lists including the ones you provided and then the converted one from your data.

I don't see any CSV files attached to your response. Could you please share the CSV files again? This will help me better understand and investigate the issue you're experiencing.

**Comment by SnowshedD** [comment]
I can input the price for the product, but after saying update, it does not show the price.  I sent screenshots of this.

I have now gone into do a screenshot of the products and issues and all of my products are deleted.  This is NOT okay.

Clearly your system is blocking my documents that I have attached.  Please fix your system.  This will be the 3rd time I am sending this to you.

￼￼￼
Joan Kloth-Zanard

Owner of SnowShed Designs
&
2nd Life 4 All
***@***.***
203-770-0318
www.snowsheddesigns.com
www.2ndLife4All.com
www.Injeaniusdesigns.com
www.keepinguinstitches.com

**Comment by WunderBart** [comment]
Hi @SnowshedD! 👋

Thank you for your response! It seems the attachments didn’t come through via email. Sorry for the hassle! Could you kindly upload the CSV again, either directly on GitHub or through an external host (e.g., https://wetransfer.com/) and share the download link?

Thanks so much for your help! 🙏

**Comment by SnowshedD** [comment]
Please fix your system so I can upload.  I have no idea where to upped it to on GitHub since I have never used that before.  Here is a link to my google drive.  The folder contains all of the types of files and information I have used to work from for this issue.

https://drive.google.com/drive/folders/1xzOfjEmp7qIAV7FNGgUD00SpOzljqbXe?usp=share_link￼

Joan Kloth-Zanard

Owner of SnowShed Designs
&
2nd Life 4 All
***@***.***
203-770-0318
www.snowsheddesigns.com
www.2ndLife4All.com
www.Injeaniusdesigns.com
www.keepinguinstitches.com

**Comment by SnowshedD** [comment]
Use this link instead.

https://drive.google.com/drive/folders/1oD5p52kkBddU3motshg39x-i3CEBFEkh?usp=share_link￼
Joan Kloth-Zanard

Owner of SnowShed Designs
&
2nd Life 4 All
***@***.***
203-770-0318
www.snowsheddesigns.com
www.2ndLife4All.com
www.Injeaniusdesigns.com
www.keepinguinstitches.com

**Comment by WunderBart** [comment]
> Please fix your system so I can upload.

I’m sorry, but since GitHub is an external service that we use, we don’t have control over its message attachment functionality. 😔

> Use this link instead.

Regarding the link you provided—thank you! However, its visibility is currently set to private, so I’m unable to access it. To make it accessible, you can update the sharing settings by following these steps:  

1. Select the CSV file in your Drive.  
2. Click **Share**.  
3. Under **“General access,”** click the down arrow.  
4. Choose **Anyone with the link**.  

Thanks so much for your understanding! 🙌

**Comment by SnowshedD** [comment]
Please click to request that I share it will you. I am not making my files public.

Joan Kloth-Zanard

Owner of SnowShed Designs
&
2nd Life 4 All
***@***.***
203-770-0318
www.snowsheddesigns.com
www.2ndLife4All.com
www.Injeaniusdesigns.com
www.keepinguinstitches.com

**Comment by WunderBart** [comment]
Thanks for sharing the CSV! I noticed that its formatting is indeed broken, which is causing the import to fail. I’ve fixed the formatting and shared the updated file with you ([here](https://drive.google.com/file/d/17KyiTKw5-yOn0xPb0STsC44Y6aEwzuJn/view?usp=sharing)).  

However, it seems that the product images are no longer available (e.g., [http://snowsheddesigns.com/wp-content/uploads/2024/12/product-images/autumn-fair.jpg](http://snowsheddesigns.com/wp-content/uploads/2024/12/product-images/autumn-fair.jpg)). This means the import will fail again unless you explicitly skip the image import.  

To skip importing images, please follow the steps shown in the recording below:  

https://github.com/user-attachments/assets/6baf98b5-0785-4de0-bd5c-b24a59d52012  


Let me know if it helps! 🙏

**Comment by SnowshedD** [comment]
Yeah, the photos are still on the site but not tied to the products list.  But the products list I did have was removed by someone, NOT ME!!  In fact, I restored if from the trash and a week later it was gone.
Joani

Joan Kloth-Zanard

Owner of SnowShed Designs
&
2nd Life 4 All
***@***.***
203-770-0318
www.snowsheddesigns.com
www.2ndLife4All.com
www.Injeaniusdesigns.com
www.keepinguinstitches.com

**Comment by SnowshedD** [comment]
Still does not work.  See attached screenshot.  The product name is not listed but rather comes up as Product.  The price is not there and so on.

This is exactly what I have been telling you has been happening with every single import, and especially the ones you provide.

Joani
Joan Kloth-Zanard
￼

Owner of SnowShed Designs
&
2nd Life 4 All
***@***.***
203-770-0318
www.snowsheddesigns.com
www.2ndLife4All.com
www.Injeaniusdesigns.com
www.keepinguinstitches.com

**Comment by WunderBart** [comment]
> The product name is not listed but rather comes up as Product.

These are likely the previously imported products (the ones from the broken CSV). Before importing new ones you'll need to remove all those broken `Product`-titled ones! 🤞

**Comment by SnowshedD** [comment]
No, they are not.  I just redid it.  In fact, the other day there were no products listed.  And I was pissed that it was removed.  Today, there are products with names, so I told the import the 2nd time to include or whatever that check box says.  And still it imports the same.

Joan Kloth-Zanard

Owner of SnowShed Designs
&
2nd Life 4 All
***@***.***
203-770-0318
www.snowsheddesigns.com
www.2ndLife4All.com
www.Injeaniusdesigns.com
www.keepinguinstitches.com

**Comment by SnowshedD** [comment]
But I will now delete everything again leaving nothing in there.  I have also deleted all of the trash.  And it still comes up the same way.  See screenshot.

￼

Joan Kloth-Zanard

Owner of SnowShed Designs
&
2nd Life 4 All
***@***.***
203-770-0318
www.snowsheddesigns.com
www.2ndLife4All.com
www.Injeaniusdesigns.com
www.keepinguinstitches.com

**Comment by WunderBart** [comment]
> See screenshot.

I'm sorry, but no screenshots are being forwarded.

Just to be sure - I haven't updated your original file `Inventory Adjusted Jan 6 2025.csv` – I've uploaded a new one named `Inventory Adjusted Jan 20 2025.csv`. Are you attempting to import from the new file? The old one does import broken products for me (titled `Product` with empty fields) but the new one works as expected on my end!

**Comment by SnowshedD** [comment]
Whatever you sent me a link for is what I used.  If you did not fix it, then that is the problem.  I cannot fix it as I have no idea what is the problem.

I will post the screenshot to the drive you have access to.

Joan Kloth-Zanard

Owner of SnowShed Designs
&
2nd Life 4 All
***@***.***
203-770-0318
www.snowsheddesigns.com
www.2ndLife4All.com
www.Injeaniusdesigns.com
www.keepinguinstitches.com

**Comment by SnowshedD** [comment]
The problem is that every time you send me something in CSV, and I open it to save to my system, it has to open in Numbers and this is causing changes in the file.

Joan Kloth-Zanard

Owner of SnowShed Designs
&
2nd Life 4 All
***@***.***
203-770-0318
www.snowsheddesigns.com
www.2ndLife4All.com
www.Injeaniusdesigns.com
www.keepinguinstitches.com

**Comment by SnowshedD** [comment]
And now nothing is importing from the CSV file that you sent me.  It is completely blank.

Joan Kloth-Zanard

Owner of SnowShed Designs
&
2nd Life 4 All
***@***.***
203-770-0318
www.snowsheddesigns.com
www.2ndLife4All.com
www.Injeaniusdesigns.com
www.keepinguinstitches.com

**Comment by SnowshedD** [comment]
This is even worse.

Joan Kloth-Zanard

Owner of SnowShed Designs
&
2nd Life 4 All
***@***.***
203-770-0318
www.snowsheddesigns.com
www.2ndLife4All.com
www.Injeaniusdesigns.com
www.keepinguinstitches.com

**Comment by SnowshedD** [comment]
I will add a screenshot to the file of what happens when I take your uploaded file to my google drive that I actually save in the condition you provided it without opening it on my computer to the drive.

Not a single product is uploaded.

This is the worst system ever.

I am computer literate having been working with computer since 1984 and even I cannot get this to work.

Joan Kloth-Zanard

Owner of SnowShed Designs
&
2nd Life 4 All
***@***.***
203-770-0318
www.snowsheddesigns.com
www.2ndLife4All.com
www.Injeaniusdesigns.com
www.keepinguinstitches.com

**Comment by WunderBart** [comment]
> The problem is that every time you send me something in CSV, and I open it to save to my system, it has to open in Numbers and this is causing changes in the file. 

That might be the main issue on your end, but the good news is that you don't really need to open the file at all! You only need to download it to your local drive so that you can open it with the importer. The file should remain unchanged!

Also, would it be OK if I upload the udpated CSV with your products here for other developers to inspect? Right now, it would be difficult for others to debug since I'm the only one with access. 😄 

I'm sorry to hear it's all so frustrating! 😅 

--- 

_edit:_

Attaching CSVs as per https://github.com/woocommerce/woocommerce/issues/54397#issuecomment-2602945293:

- Original: [Inventory Adjusted Jan 6 2025.csv](https://github.com/user-attachments/files/18504918/Inventory.Adjusted.Jan.6.2025.csv)
- Fixed syntax:[Inventory Adjusted Jan 20 2025.csv](https://github.com/user-attachments/files/18481054/Inventory.Adjusted.Jan.20.2025.csv)

**Comment by SnowshedD** [comment]
I did that.  I downloaded it and installed YOUR COPY of the CSV and there is NOTHING that came in.  Please look at the Screenshots I just posted to the google drive.  I tried importing YOUR CSV twice and the same thing happened twice.

And yes, you can do that. 

And your system should be aware that your CSV files when opened use Numbers on a MAC and that this causes a corruption of the file.

Joan Kloth-Zanard

Owner of SnowShed Designs
&
2nd Life 4 All
***@***.***
203-770-0318
www.snowsheddesigns.com
www.2ndLife4All.com
www.Injeaniusdesigns.com
www.keepinguinstitches.com

**Comment by WunderBart** [comment]
> I tried importing YOUR CSV twice and the same thing happened twice

Just to doublecheck - did you set the image import to be skipped as presented in [these instructions](https://github.com/woocommerce/woocommerce/issues/54397#issuecomment-2602790320)?

It would also help if you could share a screen recording of the import process! 🙏

**Comment by SnowshedD** [comment]
There is no option for image import that I saw.

Joani

Joan Kloth-Zanard

Owner of SnowShed Designs
&
2nd Life 4 All
***@***.***
203-770-0318
www.snowsheddesigns.com
www.2ndLife4All.com
www.Injeaniusdesigns.com
www.keepinguinstitches.com

**Comment by SnowshedD** [comment]
So you should have told me from the start to tell it to NOT Import photos and it would have worked fine.  Now it is working.

For it to take two months or more to get to this point is unacceptable.

Joani

Joan Kloth-Zanard

Owner of SnowShed Designs
&
2nd Life 4 All
***@***.***
203-770-0318
www.snowsheddesigns.com
www.2ndLife4All.com
www.Injeaniusdesigns.com
www.keepinguinstitches.com

**Comment by WunderBart** [comment]
Thank you for the feedback. I understand how frustrating it must have been to go through this process. We should have communicated more clearly from the beginning, and I appreciate your patience in working through it. I’m glad it’s working now, and we’ll take this as an opportunity to improve moving forward. If there’s anything else I can assist you with, please let me know.

**Comment by SnowshedD** [comment]
Not right now.  And thank you for being the one to finally fix this issue.  This should be a huge red flag to WOO about many issues as follows:

1) MAC numbers files do not transpose properly to CSV files that your system can use
2) Better training needs to be done to help people out
3) Online instructions should state in red on the import page that if you do not have photos to import, to make the photos block to NOT import.

Joan Kloth-Zanard

Owner of SnowShed Designs
&
2nd Life 4 All
***@***.***
203-770-0318
www.snowsheddesigns.com
www.2ndLife4All.com
www.Injeaniusdesigns.com
www.keepinguinstitches.com

**Comment by WunderBart** [comment]
> 1) MAC Numbers files do not transpose properly to CSV files that your system can use

The original CSV you used (see attachments [here](https://github.com/woocommerce/woocommerce/issues/54397#issuecomment-2602933017)) had broken syntax, likely due to an issue that occurred while editing it in Numbers. While we can’t control how Apple’s Numbers handles CSVs, I recommend using an online CSV validator tool (search for `csv validator`) to ensure your file is properly formatted before importing. That said, I agree that implementing a built-in CSV validation step during the pre-import stage could make this process much smoother. I’ll create a feature request for this enhancement.

> 3) Online instructions should state in red on the import page that if you do not have photos to import, to make the photos block to NOT import

This is an excellent suggestion! Clear, informative messaging during the import process—especially when an issue occurs—could prevent unnecessary frustration. I’ll propose adding a more detailed error message explaining why an import might fail, as well as additional guidance to help users configure their settings correctly.

**Comment by SnowshedD** [comment]
The numbers files I used were never edited by me.  I only downloaded your file that you created from my excel to CSV which then opened it in numbers and which I then exported back to CSV file.

But glad the other ideas are good.


Joan Kloth-Zanard

Owner of SnowShed Designs
&
2nd Life 4 All
***@***.***
203-770-0318
www.snowsheddesigns.com
www.2ndLife4All.com
www.Injeaniusdesigns.com
www.keepinguinstitches.com

**Comment by WunderBart** [comment]
Created request: https://github.com/woocommerce/woocommerce/issues/54841

**Comment by SnowshedD** [comment]
What have you done now.

This is disgusting that it is still going on.

We just supposedly resolved this issue and imported all of my products with their prices.  Now none of my products is listed exempt something called a Sample.  This is really bad.  I want this fixed immediately.  This is now going on 3 months to fix and now all the work we did is gone.

Joani

Joan Kloth-Zanard
SnowShed Designs
***@***.***
www.snowsheddesigns.com
203-770-0318
