### ISSUE TITLE
Textdomain loading warning in woocommerce 9.80 beta-1

### ISSUE THREAD

**Issue by BackuPs** [woothemes/woocommerce#56113]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Notice: Function _load_textdomain_just_in_time was called incorrectly. Translation loading for the woocommerce domain was triggered too early. This is usually an indicator for some code in the plugin or theme running too early. Translations should be loaded at the init action or later. Please see Debugging in WordPress for more information. (This message was added in version 6.7.0.) in /var/docs/public/wp-includes/functions.php on line 6121

### Expected behavior

the same behaviour as in woo 9.7.1. No warning message

I am using wp 6.8

### Actual behavior

load the text domain at the correct moment

### Steps to reproduce

Install woo 9.8.0 beta.  Turn on debug mode in wordpress

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): http://mydomain.com
Site address (URL): http://mydomain.com
WC Version: 9.8.0-beta.1
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.9.2
Log Directory Writable: ✔
WP Version: ❌ 6.8-alpha-59837 - There is a newer version of WordPress available (6.8-beta1-59935)
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.52 (Ubuntu)
PHP Version: 8.3.17
PHP Post Max Size: 512 MB
PHP Time Limit: 600
PHP Max Input Vars: 5000
cURL Version: 7.81.0
OpenSSL/3.0.2

SUHOSIN Installed: –
MySQL Version: 8.0.41-0ubuntu0.22.04.1
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 9.7.0
WC Database Prefix: wp_
Total Database Size: 20.37MB
Database Data Size: 15.30MB
Database Index Size: 5.07MB
wp_woocommerce_sessions: Data: 0.14MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.05MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_aioseo_cache: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_cky_banners: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_cky_cookie_categories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_cky_cookies: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cmplz_cookiebanners: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cmplz_cookies: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cmplz_dnsmpd: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cmplz_services: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_ct_ugdpr_consent_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_daextlwcn_category: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_daextlwcn_consent_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_daextlwcn_cookie: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_daextlwcn_section: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_e_notes: Data: 0.02MB + Index: 0.17MB + Engine InnoDB
wp_e_notes_users_relations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_e_submissions: Data: 0.02MB + Index: 0.27MB + Engine InnoDB
wp_e_submissions_actions_log: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_e_submissions_values: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_eg_grids: Data: 0.03MB + Index: 0.02MB + Engine InnoDB
wp_eg_item_elements: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_eg_item_skins: Data: 0.11MB + Index: 0.03MB + Engine InnoDB
wp_eg_navigation_skins: Data: 0.14MB + Index: 0.02MB + Engine InnoDB
wp_fbv: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_fbv_attachment_folder: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gdpr_cc_options: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gdpr_consent_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gla_attribute_mapping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_budget_recommendations: Data: 0.19MB + Index: 0.11MB + Engine InnoDB
wp_gla_merchant_issues: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_shipping_rates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 7.31MB + Index: 0.13MB + Engine InnoDB
wp_postmeta: Data: 3.52MB + Index: 2.00MB + Engine InnoDB
wp_posts: Data: 1.52MB + Index: 0.16MB + Engine InnoDB
wp_responsive_menu_pro: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_revslider_css: Data: 0.13MB + Index: 0.02MB + Engine InnoDB
wp_revslider_css_bkp: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_layer_animations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_navigations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_navigations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_sliders: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_revslider_sliders7: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_revslider_sliders_bkp: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_revslider_slides: Data: 0.13MB + Index: 0.02MB + Engine InnoDB
wp_revslider_slides7: Data: 0.09MB + Index: 0.02MB + Engine InnoDB
wp_revslider_slides_bkp: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_revslider_static_slides: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_revslider_static_slides_bkp: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpomp_group_map: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wpomp_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wpomp_maps: Data: 0.01MB + Index: 0.00MB + Engine MyISAM

### Post Type Counts ###

attachment: 277
elementor_library: 2
gdpr_request: 1
master-popups: 1
nav_menu_item: 105
page: 152
portfolio: 31
post: 18
preset: 2
product: 28
product_variation: 7
revision: 136
slideshow: 5
wp_global_styles: 1
wp_navigation: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (4) ###

WooCommerce Beta Tester: by WooCommerce – 3.0.0
WooCommerce: by Automattic – 9.8.0-beta.1
WordPress Beta Tester: by WordPress Upgrade/Install Team – 3.6.2
Test jQuery Updates: by The WordPress Team – 3.0.2

### Inactive Plugins (1) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.7

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 331 KB

### WC Pages ###

Shop base: #5903 - /shop/
Cart: #5904 - /cart/ -  Contains the woocommerce_cart shortcode
Checkout: #5905 - /checkout/ -  Contains the woocommerce/checkout block
My account: #5906 - /my-account/ -  Contains the [woocommerce_my_account] shortcode
Terms and conditions: ❌ Page not set

### Theme ###

Name: WP Professional Multi-Purpose WordPress Theme
Version: 3.7.4 Build 20 february 2025
Author URL: 
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
Theme type: Classic theme
WooCommerce Support: ✔

### Templates ###

Overrides: custom-theme/woocommerce/archive-product.php
custom-theme/woocommerce/content-product-cat.php
custom-theme/woocommerce/content-product.php
custom-theme/woocommerce/global/breadcrumb.php
custom-theme/woocommerce/product-searchform.php
custom-theme/woocommerce/single-product/meta.php
custom-theme/woocommerce/single-product/product-image.php
custom-theme/woocommerce/single-product/product-thumbnails.php
custom-theme/woocommerce/single-product/rating.php
custom-theme/woocommerce/single-product/related.php
custom-theme/woocommerce/single-product/tabs/additional-information.php
custom-theme/woocommerce/single-product/tabs/description.php
custom-theme/woocommerce/single-product/tabs/tabs.php
custom-theme/woocommerce/single-product/title.php
custom-theme/woocommerce/single-product/up-sells.php
custom-theme/woocommerce/single-product-reviews.php
custom-theme/woocommerce/single-product.php
custom-theme/woocommerce/content-product_cat.php

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store
add-to-cart-with-options-stepper-layout

Disabled Features: product-data-views
experimental-blocks
coming-soon-newsletter-template
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system
reactify-classic-payments-settings
use-wp-horizon
blockified-add-to-cart
beta-tester-slotfill-examples

Daily Cron: ✔ Next scheduled: 2024-10-10 10:21:36 +00:00
Options: ✔
Notes: 81
Onboarding: completed

### Action Scheduler ###

Complete: 90
Oldest: 2024-10-09 06:43:29 +0000
Newest: 2025-02-07 12:12:00 +0000

Pending: 6
Oldest: 2025-02-08 12:11:55 +0000
Newest: 2025-03-05 09:17:05 +0000

### Status report information ###

Generated at: 2025-03-05 10:36:30 +00:00
`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by BackuPs** [comment]
back tracking shows this

 Array
(
    [0] => Array
        (
            [file] => /var/docs/mydomain.com/public/wp-includes/functions.php
            [line] => 6061
            [function] => wp_trigger_error
        )

    [1] => Array
        (
            [file] => /var/docs/mydomain.com/public/wp-includes/l10n.php
            [line] => 1371
            [function] => _doing_it_wrong
        )

    [2] => Array
        (
            [file] => /var/docs/mydomain.com/public/wp-includes/l10n.php
            [line] => 1409
            [function] => _load_textdomain_just_in_time
        )

    [3] => Array
        (
            [file] => /var/docs/mydomain.com/public/wp-includes/l10n.php
            [line] => 195
            [function] => get_translations_for_domain
        )

    [4] => Array
        (
            [file] => /var/docs/mydomain.com/public/wp-includes/l10n.php
            [line] => 307
            [function] => translate
        )

    [5] => Array
        (
            [file] => /var/docs/mydomain.com/public/wp-content/plugins/woocommerce/src/Internal/Features/FeaturesController.php
            [line] => 204
            [function] => __
        )

    [6] => Array
        (
            [file] => /var/docs/mydomain.com/public/wp-content/plugins/woocommerce/src/Internal/Features/FeaturesController.php
            [line] => 653
            [function] => get_feature_definitions
            [class] => Automattic\\WooCommerce\\Internal\\Features\\FeaturesController
            [type] => ->
        )

    [7] => Array
        (
            [file] => /var/docs/mydomain.com/public/wp-content/plugins/woocommerce/src/Internal/Features/FeaturesController.php
            [line] => 553
            [function] => feature_exists
            [class] => Automattic\\WooCommerce\\Internal\\Features\\FeaturesController
            [type] => ->
        )

    [8] => Array
        (
            [file] => /var/docs/mydomain.com/public/wp-content/plugins/woocommerce/src/Utilities/FeaturesUtil.php
            [line] => 42
            [function] => feature_is_enabled
            [class] => Automattic\\WooCommerce\\Internal\\Features\\FeaturesController
            [type] => ->
        )

    [9] => Array
        (
            [file] => /var/docs/mydomain.com/public/wp-content/plugins/woocommerce/src/Internal/EmailEditor/Package.php
            [line] => 38
            [function] => feature_is_enabled
            [class] => Automattic\\WooCommerce\\Utilities\\FeaturesUtil
            [type] => ::
        )

    [10] => Array
        (
            [function] => init
            [class] => Automattic\\WooCommerce\\Internal\\EmailEditor\\Package
            [type] => ::
        )

    [11] => Array
        (
            [file] => /var/docs/mydomain.com/public/wp-content/plugins/woocommerce/src/Packages.php
            [line] => 299
            [function] => call_user_func
        )

    [12] => Array
        (
            [file] => /var/docs/mydomain.com/public/wp-content/plugins/woocommerce/src/Packages.php
            [line] => 89
            [function] => initialize_packages
            [class] => Automattic\\WooCommerce\\Packages
            [type] => ::
        )

    [13] => Array
        (
            [file] => /var/docs/mydomain.com/public/wp-includes/class-wp-hook.php
            [line] => 324
            [function] => on_init
            [class] => Automattic\\WooCommerce\\Packages
            [type] => ::
        )

    [14] => Array
        (
            [file] => /var/docs/mydomain.com/public/wp-includes/class-wp-hook.php
            [line] => 348
            [function] => apply_filters
            [class] => WP_Hook
            [type] => ->
        )

    [15] => Array
        (
            [file] => /var/docs/mydomain.com/public/wp-includes/plugin.php
            [line] => 517
            [function] => do_action
            [class] => WP_Hook
            [type] => ->
        )

    [16] => Array
        (
            [file] => /var/docs/mydomain.com/public/wp-settings.php
            [line] => 577
            [function] => do_action
        )

    [17] => Array
        (
            [file] => /var/docs/mydomain.com/public/wp-config.php
            [line] => 97
            [args] => Array
                (
                    [0] => /var/docs/mydomain.com/public/wp-settings.php
                )

            [function] => require_once
        )

    [18] => Array
        (
            [file] => /var/docs/mydomain.com/public/wp-load.php
            [line] => 50
            [args] => Array
                (
                    [0] => /var/docs/mydomain.com/public/wp-config.php
                )

            [function] => require_once
        )

    [19] => Array
        (
            [file] => /var/docs/mydomain.com/public/wp-blog-header.php
            [line] => 13
            [args] => Array
                (
                    [0] => /var/docs/mydomain.com/public/wp-load.php
                )

            [function] => require_once
        )

    [20] => Array
        (
            [file] => /var/docs/mydomain.com/public/index.php
            [line] => 17
            [args] => Array
                (
                    [0] => /var/docs/mydomain.com/public/wp-blog-header.php
                )

            [function] => require
        )

)
, referer: http://mydomain.com/wp-admin/plugins.php

**Comment by triple0t** [comment]
Thank you for the report, @BackuPs
We have it on our radar and will fix it soon.

**Comment by BackuPs** [comment]
this is not fixed yet. latest beta with woocommerce 9.80 beta 1 gives now this error also

Notice: Function WP_Theme::is_block_theme was called incorrectly. This method should not be called before themes are set up. Please see Debugging in WordPress for more information. (This message was added in version 6.8.0.) in /var/docs/public/wp-includes/functions.php on line 6121


[Thu Mar 13 13:51:02.159812 2025] [php:notice] [pid 3359] [client 192.168.142.1:57604] Array
(
    [0] => Array
        (
            [file] => /var/docs/public/wp-includes/functions.php
            [line] => 6061
            [function] => wp_trigger_error
        )

    [1] => Array
        (
            [file] => /var/docs/public/wp-includes/class-wp-theme.php
            [line] => 1580
            [function] => _doing_it_wrong
        )

    [2] => Array
        (
            [file] => /var/docs/public/wp-includes/theme.php
            [line] => 4355
            [function] => is_block_theme
            [class] => WP_Theme
            [type] => ->
        )

    [3] => Array
        (
            [file] => /var/docs/public/wp-content/plugins/woocommerce/includes/wc-conditional-functions.php
            [line] => 517
            [function] => wp_is_block_theme
        )

    [4] => Array
        (
            [file] => /var/docs/public/wp-content/plugins/woocommerce/src/Blocks/Templates/ClassicTemplatesCompatibility.php
            [line] => 36
            [function] => wc_current_theme_is_fse_theme
        )

    [5] => Array
        (
            [file] => /var/docs/public/wp-content/plugins/woocommerce/src/Blocks/Templates/ClassicTemplatesCompatibility.php
            [line] => 29
            [function] => init
            [class] => Automattic\\WooCommerce\\Blocks\\Templates\\ClassicTemplatesCompatibility
            [type] => ->
        )

    [6] => Array
        (
            [file] => /var/docs/public/wp-content/plugins/woocommerce/src/Blocks/Domain/Bootstrap.php
            [line] => 263
            [function] => __construct
            [class] => Automattic\\WooCommerce\\Blocks\\Templates\\ClassicTemplatesCompatibility
            [type] => ->
        )

    [7] => Array
        (
            [file] => /var/docs/public/wp-content/plugins/woocommerce/src/Blocks/Registry/AbstractDependencyType.php
            [line] => 42
            [function] => Automattic\\WooCommerce\\Blocks\\Domain\\{closure}
            [class] => Automattic\\WooCommerce\\Blocks\\Domain\\Bootstrap
            [type] => ->
        )

    [8] => Array
        (
            [file] => /var/docs/public/wp-content/plugins/woocommerce/src/Blocks/Registry/SharedType.php
            [line] => 28
            [function] => resolve_value
            [class] => Automattic\\WooCommerce\\Blocks\\Registry\\AbstractDependencyType
            [type] => ->
        )

    [9] => Array
        (
            [file] => /var/docs/public/wp-content/plugins/woocommerce/src/Blocks/Registry/Container.php
            [line] => 96
            [function] => get
            [class] => Automattic\\WooCommerce\\Blocks\\Registry\\SharedType
            [type] => ->
        )

    [10] => Array
        (
            [file] => /var/docs/public/wp-content/plugins/woocommerce/src/Blocks/Domain/Bootstrap.php
            [line] => 166
            [function] => get
            [class] => Automattic\\WooCommerce\\Blocks\\Registry\\Container
            [type] => ->
        )

    [11] => Array
        (
            [file] => /var/docs/public/wp-content/plugins/woocommerce/src/Blocks/Domain/Bootstrap.php
            [line] => 82
            [function] => init
            [class] => Automattic\\WooCommerce\\Blocks\\Domain\\Bootstrap
            [type] => ->
        )

    [12] => Array
        (
            [file] => /var/docs/public/wp-content/plugins/woocommerce/src/Blocks/Package.php
            [line] => 106
            [function] => __construct
            [class] => Automattic\\WooCommerce\\Blocks\\Domain\\Bootstrap
            [type] => ->
        )

    [13] => Array
        (
            [file] => /var/docs/public/wp-content/plugins/woocommerce/src/Blocks/Registry/AbstractDependencyType.php
            [line] => 42
            [function] => Automattic\\WooCommerce\\Blocks\\{closure}
            [class] => Automattic\\WooCommerce\\Blocks\\Package
            [type] => ::
        )

    [14] => Array
        (
            [file] => /var/docs/public/wp-content/plugins/woocommerce/src/Blocks/Registry/SharedType.php
            [line] => 28
            [function] => resolve_value
            [class] => Automattic\\WooCommerce\\Blocks\\Registry\\AbstractDependencyType
            [type] => ->
        )

    [15] => Array
        (
            [file] => /var/docs/public/wp-content/plugins/woocommerce/src/Blocks/Registry/Container.php
            [line] => 96
            [function] => get
            [class] => Automattic\\WooCommerce\\Blocks\\Registry\\SharedType
            [type] => ->
        )

    [16] => Array
        (
            [file] => /var/docs/public/wp-content/plugins/woocommerce/src/Blocks/Package.php
            [line] => 44
            [function] => get
            [class] => Automattic\\WooCommerce\\Blocks\\Registry\\Container
            [type] => ->
        )

    [17] => Array
        (
            [function] => init
            [class] => Automattic\\WooCommerce\\Blocks\\Package
            [type] => ::
        )

    [18] => Array
        (
            [file] => /var/docs/public/wp-content/plugins/woocommerce/src/Packages.php
            [line] => 291
            [function] => call_user_func
        )

    [19] => Array
        (
            [file] => /var/docs/public/wp-content/plugins/woocommerce/src/Packages.php
            [line] => 89
            [function] => initialize_packages
            [class] => Automattic\\WooCommerce\\Packages
            [type] => ::
        )

    [20] => Array
        (
            [file] => /var/docs/public/wp-includes/class-wp-hook.php
            [line] => 324
            [function] => on_init
            [class] => Automattic\\WooCommerce\\Packages
            [type] => ::
        )

    [21] => Array
        (
            [file] => /var/docs/public/wp-includes/class-wp-hook.php
            [line] => 348
            [function] => apply_filters
            [class] => WP_Hook
            [type] => ->
        )

    [22] => Array
        (
            [file] => /var/docs/public/wp-includes/plugin.php
            [line] => 517
            [function] => do_action
            [class] => WP_Hook
            [type] => ->
        )

    [23] => Array
        (
            [file] => /var/docs/public/wp-settings.php
            [line] => 578
            [function] => do_action
        )

    [24] => Array
        (
            [file] => /var/docs/public/wp-config.php
            [line] => 97
            [args] => Array
                (
                    [0] => /var/docs/public/wp-settings.php
                )

            [function] => require_once
        )

    [25] => Array
        (
            [file] => /var/docs/public/wp-load.php
            [line] => 50
            [args] => Array
                (
                    [0] => /var/docs/public/wp-config.php
                )

            [function] => require_once
        )

    [26] => Array
        (
            [file] => /var/docs/public/wp-blog-header.php
            [line] => 13
            [args] => Array
                (
                    [0] => /var/docs/public/wp-load.php
                )

            [function] => require_once
        )

    [27] => Array
        (
            [file] => /var/docs/public/index.php
            [line] => 17
            [args] => Array
                (
                    [0] => /var/docs/public/wp-blog-header.php
                )

            [function] => require
        )

)
, referer: http://wp-admin/plugins.php?plugin_status=active&paged=1&s
[Thu Mar 13 13:51:02.159873 2025] [php:notice] [pid 3359] [client 192.168.142.1:57604] PHP Notice:  Function WP_Theme::is_block_theme was called <strong>incorrectly</strong>. This method should not be called before themes are set up. Please see <a href="https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/">Debugging in WordPress</a> for more information. (This message was added in version 6.8.0.) in /var/docs/public/wp-includes/functions.php on line 6121, referer: http://wp-admin/plugins.php?plugin_status=active&paged=1&s
[Thu Mar 13 13:51:02.162726 2025] [php:notice] [pid 3359] [client 192.168.142.1:57604] Array
(
    [0] => Array
        (
            [file] => /var/docs/public/wp-includes/functions.php
            [line] => 6061
            [function] => wp_trigger_error
        )

    [1] => Array
        (
            [file] => /var/docs/public/wp-includes/class-wp-theme.php
            [line] => 1580
            [function] => _doing_it_wrong
        )

    [2] => Array
        (
            [file] => /var/docs/public/wp-includes/theme.php
            [line] => 4355
            [function] => is_block_theme
            [class] => WP_Theme
            [type] => ->
        )

    [3] => Array
        (
            [file] => /var/docs/public/wp-content/plugins/woocommerce/includes/wc-conditional-functions.php
            [line] => 517
            [function] => wp_is_block_theme
        )

    [4] => Array
        (
            [file] => /var/docs/public/wp-content/plugins/woocommerce/includes/class-wc-brands.php
            [line] => 41
            [function] => wc_current_theme_is_fse_theme
        )

    [5] => Array
        (
            [file] => /var/docs/public/wp-includes/class-wp-hook.php
            [line] => 324
            [function] => register_hooks
            [class] => WC_Brands
            [type] => ->
        )

    [6] => Array
        (
            [file] => /var/docs/public/wp-includes/class-wp-hook.php
            [line] => 348
            [function] => apply_filters
            [class] => WP_Hook
            [type] => ->
        )

    [7] => Array
        (
            [file] => /var/docs/public/wp-includes/plugin.php
            [line] => 517
            [function] => do_action
            [class] => WP_Hook
            [type] => ->
        )

    [8] => Array
        (
            [file] => /var/docs/public/wp-settings.php
            [line] => 578
            [function] => do_action
        )

    [9] => Array
        (
            [file] => /var/docs/public/wp-config.php
            [line] => 97
            [args] => Array
                (
                    [0] => /var/docs/public/wp-settings.php
                )

            [function] => require_once
        )

    [10] => Array
        (
            [file] => /var/docs/public/wp-load.php
            [line] => 50
            [args] => Array
                (
                    [0] => /var/docs/public/wp-config.php
                )

            [function] => require_once
        )

    [11] => Array
        (
            [file] => /var/docs/public/wp-blog-header.php
            [line] => 13
            [args] => Array
                (
                    [0] => /var/docs/public/wp-load.php
                )

            [function] => require_once
        )

    [12] => Array
        (
            [file] => /var/docs/public/index.php
            [line] => 17
            [args] => Array
                (
                    [0] => /var/docs/public/wp-blog-header.php
                )

            [function] => require
        )

)
, referer: http://wp-admin/plugins.php?plugin_status=active&paged=1&s
[Thu Mar 13 13:51:02.162792 2025] [php:notice] [pid 3359] [client 192.168.142.1:57604] PHP Notice:  Function WP_Theme::is_block_theme was called <strong>incorrectly</strong>. This method should not be called before themes are set up. Please see <a href="https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/">Debugging in WordPress</a> for more information. (This message was added in version 6.8.0.) in /var/docs/public/wp-includes/functions.php on line 6121, referer: http://wp-admin/plugins.php?plugin_status=active&paged=1&s

**Comment by gigitux** [comment]
@BackuPs Thanks for the report. This issue is referring to the `is_block_theme` function. There is a dedicated issue for this warning: https://github.com/woocommerce/woocommerce/issues/56322

**Comment by BackuPs** [comment]
Still issues with latest woocommerce beta and latest wp 6.8 beta 3

Notice: Function _load_textdomain_just_in_time was called incorrectly. Translation loading for the woocommerce domain was triggered too early. This is usually an indicator for some code in the plugin or theme running too early. Translations should be loaded at the init action or later. Please see [Debugging in WordPress](https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/) for more information. (This message was added in version 6.7.0.) in /var/docs/server.tst/public/wp-includes/functions.php on line 6121

**Comment by triple0t** [comment]
Hi @BackuPs, Thanks for the report. 

The issue has been resolved and will be included in the upcoming WooCommerce 9.8 Release Candidate.

Read more on the announcement post here: https://developer.woocommerce.com/2025/03/14/woocommerce-9-8-rc-1-is-delayed/

**Comment by jasperf** [comment]
I am currently on WooCommerce 9.8.1 and WordPress 6.8. I currently still see the notice
```
wp acorn optimize:clear
Notice: Function _load_textdomain_just_in_time was called <strong>incorrectly</strong>. Translation loading for the
 <code>woocommerce</code> domain was triggered too early. This is usually an indicator for some code in the plugin or
 theme running too early. Translations should be loaded at the <code>init</code> action or later. Please see <a 
href="https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/">Debugging in WordPress</a> 
for more information. (This message was added in version 6.7.0.) in /srv/www/imagewize.com/current/web/wp/wp-includes/functions.php on line 6121

   INFO  Clearing cached bootstrap files.  

  cache ................................................................................. 9.58ms DONE
  compiled .............................................................................. 2.41ms DONE
  config ................................................................................ 0.61ms DONE
  events ............................................................................... 40.21ms DONE
  routes ................................................................................ 0.49ms DONE
  views ................................................................................. 5.48ms DONE
  blade-icons ........................................................................... 0.21ms DONE
  acf-composer .......................................................................... 0.35ms DONE
```

[SystemStatusReport_imagewize.test_2025-04-18T01-51-33.txt](https://github.com/user-attachments/files/19806905/SystemStatusReport_imagewize.test_2025-04-18T01-51-33.txt)

mentioned it earlier at https://github.com/generoi/sage-woocommerce/issues/35 and indicated how I use WooCommerce in `setup.php` which seems to be fine using Generoi WooCommerce. I was sent to https://github.com/woocommerce/woocommerce/issues/52646 and finally landed here.

**Comment by gigitux** [comment]
This will be fixed by https://github.com/woocommerce/woocommerce/pull/57291 in the WooCommerce 9.9.
