### ISSUE TITLE
registerTemplateRestrictedBlockType: Restrict Block Registration to Specific Templates

### ISSUE THREAD

**Issue by tjcafferkey** [woothemes/woocommerce#56198]
Some blocks such as the Catalog Sorting block is designed specifically for the WooCommerce Product Catalog template and should not be available for insertion or registration on unrelated templates, such as the homepage block template. This issue extends the discussion in https://github.com/woocommerce/woocommerce/issues/42387, where the block’s unrestricted registration was identified as a problem. To address this, we propose introducing a new JavaScript API for registering blocks with template-specific restrictions.

### Proposed Solution

Create a new JavaScript API, registerTemplateRestrictedBlockType, to allow developers to register blocks that are only available for specific templates. This API will extend the functionality of registerBlockType (from Gutenberg) and registerProductBlockType (from WooCommerce) by adding a templates parameter to specify allowed template IDs.

### API Signature

`registerTemplateRestrictedBlockType( name, settings, templates )`

* `name`: (string) The block’s unique name (e.g., `woocommerce/catalog-sorting`).
* `settings`: (object) The block settings object, consistent with `registerBlockType` and `registerProductBlockType`.
* `templates`: (array) An array of template IDs (e.g., `['product-catalog']`) where the block can be registered and inserted. If the current template is not in this array, the block will not be registered.

**Comment by amitraj2203** [comment]
Hi @tjcafferkey,
I would like to work on this issue. As mentioned in the issue description, I will create a new JavaScript API with the given function signature `registerTemplateRestrictedBlockType` and also develop appropriate test cases for it. This will allow developers to register blocks that are only available for specific templates.
If you think the approach is correct, could you please assign this issue to me?
Thank you!

**Comment by tjcafferkey** [comment]
That's great! We'd definitely welcome a PR on this issue, happy to assist in any way we can. You assessment of the approach appears to be correct, yes.

**Comment by amitraj2203** [comment]
@tjcafferkey While working on this issue, I ran into some confusion. Most of the tasks are done, but I’m struggling to reliably detect whether we are on the:
- Templates preview page : `wp-admin/site-editor.php?p=%2Ftemplate` or
- Actually editing a template : `wp-admin/site-editor.php?p=%2Fwp_template%2Ftwentytwentyfive%2F%2Fhome&canvas=edit`

This distinction is important because we need to unregister the block on templates where it’s not allowed. However, when navigating to _Appearance > Editor > Templates_, the block appears broken in the preview cards because it gets unregistered at that point. _I’m testing the `catalog-sorting` block as per the issue description._

I’ve tried various selectors, but they’re not behaving as expected. For instance, when I open the Home template, `getEditedPostId()` returns `twentytwentyfive//home`. But if I go back to the Templates overview (where all templates are listed), the value remains the same — it doesn’t reset unless I open another template for editing.

I did come across the [isPreviewMode](https://github.com/WordPress/gutenberg/pull/66149) selector, which works accurately in most cases. However, it doesn’t seem to function correctly in Grid preview mode — the same issue occurs where the value doesn’t update until a template is edited. In contrast, it behaves as expected in Table and List views.

![Image](https://github.com/user-attachments/assets/679ab8fb-93ab-4de8-94dd-f0d8568d1a1b)


Let me know how you suggest we proceed or if there’s any workaround you’d recommend.

Thanks!

**Comment by tjcafferkey** [comment]
@amitraj2203 this issue seems really familiar, if I am understanding you correctly then we fixed this issue with our `registerProductBlockType` function here https://github.com/woocommerce/woocommerce/pull/53997.

We essentially allowed all blocks to be registered on the template preview in the dataview since they can't be inserted here anyway so we dont have to worry about conditionally registering them.

I'd look towards this function [registerProductBlockType](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/client/blocks/assets/js/atomic/utils/register-product-block-type.ts) for inspiration here.

Hope this helps, let me know if it doesn't!

**Comment by amitraj2203** [comment]
Hi @tjcafferkey,

Thanks for the help and for pointing me towards the `registerProductBlockType` function. I've been looking at that implementation, but I'm still encountering issues with the catalog-sorting block on the templates preview page.

I've opened a draft [PR](https://github.com/woocommerce/woocommerce/pull/57901) that you can review to see my current implementation. I'm passing these template IDs where the `catalog-sorting` block should be allowed in these templates only:

```
'archive-product',
'product-search-results', 
'taxonomy-product_attribute',
'taxonomy-product_brand',
'taxonomy-product_cat',
'taxonomy-product_tag'
```

**The specific issue I'm facing:**

1. When I first open _Appearance > Editor_ (which loads the home template)
2. Then click on the Templates button to view all templates - the `catalog-sorting` block appears broken in the preview cards
3. However, if I refresh the page while on the template-preview page (`wp-admin/site-editor.php?p=%2Ftemplate`), the block starts working fine
4. But if I open any template where the block isn't allowed and then go back to the template-preview page, the block breaks again

It seems like the block unregistration is affecting the template preview cards, even though we should allow all blocks to be registered on the template preview (as you mentioned, they can't be inserted there anyway).

Could you take a look at my draft [PR](https://github.com/woocommerce/woocommerce/pull/57901) and see if there's something I'm doing differently from the `registerProductBlockType` implementation? I'd appreciate any guidance on how to handle this template preview issue correctly.

Thanks!

**Comment by tjcafferkey** [comment]
Thank you for opening up a PR! I'm going to see if I can carve out some time to look at this, but in the meantime I'm also going to loop @gigitux in here since he also has context on the `registerProductBlock` function, just incase he has some time to review your PR before I do 🙂

**Comment by kkoteen** [comment]
Hey @tjcafferkey, this issue has been open for a while, and the PR was closed. Can we close this issue as well?

**Comment by tjcafferkey** [comment]
@kkoteen even though its still valid I think we can close this for now.
