### ISSUE TITLE
Custom block-based checkout field not being validated if it has conditional hidden rules

### ISSUE THREAD

**Issue by webdados** [woothemes/woocommerce#58488]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When registering a custom block-based checkout field with `woocommerce_register_additional_checkout_field` we have the option to set hidden to `true`, `false`, or an array of json schema validation rules.

If we use the last, that field is never validated with the function passed to the `validate_callback` argument, even if it's shown. I expect for the validation not to happen if it's hidden at the moment, but if the rules make it visible, it should be run through the `validate_callback` function, which it doesn't.

This happens because `$this->is_hidden_field( $key, $document_object )` inside `CheckoutFields::get_contextual_fields_for_location` returns `false` when the field is always visible (no hidden conditional rules) and so the `validate_callback` is used, and returns `true` if the field has hidden conditional rules even if it's visible by those rules. Inside `is_hidden_field` `Validation::validate_document_object( $document_object, $field['hidden'] )` is returning true with valid hidden conditional rules which makes this function return true (is hidden).

### Expected behavior

Even if the field has conditional hidden rules, it should be validated if it's shown by its rules.

If the field  has conditional hidden rules, it should be NOT be validated if it's hidden by its rules.

### Actual behavior

Not coherent. Even if the field is shown, the `validate_callback` is not called.

### Steps to reproduce

1. Register a field and make it show conditional, also create a validate_callback function for it and return a WP_Error
2. Run the checkout and make sure that field is shown by the rules: it won't be validated and the checkout will go through without errors
3. Now remove the conditional hidden rules: it will be validated and the checkout will throw an error

### WordPress Environment

<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 9.9.0
Legacy REST API Package Version: O plugin Legacy REST API não está instalado neste site.
Action Scheduler Version: ✔ 3.9.2
Log Directory Writable: ✔
WP Version: ❌ 6.9-alpha-60258 - Há uma nova versão do WordPress disponível (6.9-alpha-60272)
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: –
Language: pt_BR
External object cache: –

### Server Environment ###

Server Info: nginx/1.26.1
Server Architecture: Darwin 24.5.0 arm64
PHP Version: 8.3.0
PHP Post Max Size: 1.000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 8.7.1
(SecureTransport) LibreSSL/3.3.6

SUHOSIN Installed: –
MySQL Version: 8.0.35
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

acf-field: 38
acf-field-group: 8
amn_smtp: 1
atividade: 4
attachment: 6283
aw_workflow: 6
blocks: 8
chefpanda_market: 3
doctor: 4
easy-pricing-table: 1
featured_item: 8
frm_form_actions: 1
frm_styles: 1
homey_reservation: 2
ibwp_mp_popup: 1
listing: 1
mb_payment_request: 1
medical-agreements: 3
medical-booking: 10
medical-consultation: 6
medical-exam: 2
medical-specialty: 4
memberpressproduct: 2
nav_menu_item: 25
oksofasstore: 3
page: 79
person: 5
post: 23
private_post: 4
product: 7970
product_variation: 138
revision: 363
shop_coupon: 25
shop_order: 971
shop_order_placehold: 6
shop_order_refund: 93
shop_subscription: 10
store: 1
szbdzones: 1
was: 1
wc_appointment: 1
wc_conditional_fee: 1
wc_order_status: 9
wc-donation: 2
wc-donation-report: 6
wcdp_payment: 4
wd_client_contract: 1
wd_support_ticket: 1
webdados_client_serv: 15
webdados_service: 8
wfacp_checkout: 1
wffn_ty: 1
wishlist: 1
wp_block: 1
wp_global_styles: 6
wp_navigation: 1
wp_template: 1
wp_template_part: 1
wpbdp_listing: 1
wpcf7_contact_form: 6
wpforms: 1
wps_subscriptions: 1
wpsc_ticket_thread: 3

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (9) ###

WooCommerce Beta Tester: por WooCommerce – 3.0.0
WooCommerce: por Automattic – 9.9.0
WordPress Beta Tester: por WordPress Upgrade/Install Team – 3.6.3

### Inactive Plugins (347) ###

Not relevant

### Dropin Plugins () ###

db.php: db.php

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: appointment (appointment)
external (external)
grouped (grouped)
mwb_booking (mwb_booking)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: ✔
Enabled Features: marketplace
order_attribution
site_visibility_badge
hpos_fts_indexes
email_improvements
custom_order_tables


### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 dias
Level threshold: –
Log directory size: 81 KB

### WC Pages ###

Base da loja: #14857 - /loja-pt/
Carrinho: #17882 - /cart-blocks/ -  Contém o bloco woocommerce/cart
Finalização de compra: #17884 - /checkout-blocks-2/ -  Contém o bloco woocommerce/checkout
Minha conta: #16787 - /my-account-2/ -  Contém o shortcode [woocommerce_my_account]
Termos e condições: #16621 - /16621-2/

### Theme ###

Name: Storefront Child
Version: 20230130.01
Author URL: 
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 4.6.1
Parent Theme Author URL: https://woocommerce.com/
Theme type: Tema clássico
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store
add-to-cart-with-options-stepper-layout
disable-core-profiler-fallback

Disabled Features: product-data-views
experimental-blocks
coming-soon-newsletter-template
minified-js
point-of-sale
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system
use-wp-horizon
blockified-add-to-cart
beta-tester-slotfill-examples

Daily Cron: ✔ Next scheduled: 2025-03-26 15:19:07 +00:00
Options: ✔
Notes: 202
Onboarding: completed

### Action Scheduler ###

Concluído: 3.558
Oldest: 2025-04-11 00:50:00 +0100
Newest: 2025-06-02 21:36:06 +0100

Malsucedido: 2.350
Oldest: 2023-02-01 17:31:32 +0000
Newest: 2025-04-22 15:46:01 +0100

Pendente: 2
Oldest: 2025-06-02 22:36:06 +0100
Newest: 2025-06-03 09:45:41 +0100


### Status report information ###

Generated at: 2025-06-02 21:52:13 +01:00
```
</details>

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by webdados** [comment]
I've put together a quick test in the form of a plugin:

```
<?php
/**
 * Plugin Name:          Test custom field validation
 * Version:              1.0
 * Author:               Marco Almeida
 * Requires at least:    6.3
 * Tested up to:         6.8
 * Requires PHP:         7.4
 * Update URI:           false
 * Requires Plugins:     woocommerce
 */
// Exit if accessed directly.
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

// Add plugin initialization hook.
add_action( 'woocommerce_init', 'test_custom_field_validation_init', 1 );

/**
 * Plugin initialization function.
 */
function test_custom_field_validation_init() {
		// Register checkout fields
		add_action( 'woocommerce_init', 'test_custom_field_validation_register_checkout_fields' );
}

/**
 * Register checkout fields
 */
function test_custom_field_validation_register_checkout_fields() {

	$namespace = 'tcf';

	// Field 1 - Always visible
	woocommerce_register_additional_checkout_field(
		array(
			'id'                         => $namespace . '/field_1',
			'label'                      => 'Field 1',
			'location'                   => 'contact',
			'type'                       => 'select',
			'hidden'                     => false,
			'required'                   => false,
			'validation'                 => false,
			'attributes'                 => array(
			),
			'options' => array(
				array(
					'value' => 'do_not_show_field_2',
					'label' => 'Do not show field 2',
				),
				array(
					'value' => 'show_field_2',
					'label' => 'Show field 2',
				),
			),
			'validate_callback' => 'test_custom_field_validation_validate_callback',
		)
	);

	// Field 2 - Visible only if Field 1 = show_field_2
	woocommerce_register_additional_checkout_field(
		array(
			'id'                         => $namespace . '/field_2',
			'label'                      => 'Field 2',
			'location'                   => 'contact',
			'type'                       => 'text',
			'hidden'                     => array(
				'checkout' => array(
					'properties' => array(
						'additional_fields' => array(
							'properties' => array(
								$namespace . '/field_1' => array(
									'not' =>
										array( 'const' => 'show_field_2' )
								),
							),
						),
					),
				),
			), // This makes the validation_callback not to be called, even when the field is visible - If it's changed to false, the validation runs 
			'required'                   => false,
			'validation'                 => false,
			'attributes'                 => array(
			),
			'validate_callback' => 'test_custom_field_validation_validate_callback',
		)
	);
}

/**
 * Validation callback
 */
function test_custom_field_validation_validate_callback( $value, $field ) {

	$namespace = 'tcf';

	// Debug
	error_log( 'test_custom_field_validation_validate_callback ' . $field['id'] . ' - Value: ' . $value );

	// Validate
	switch( $field['id'] ) {
		case $namespace . '/field_1':
			// return new WP_Error( $namespace, 'Error for field 1 - Value: ' . $value );
			break;
		case $namespace . '/field_2':
			return new WP_Error( $namespace, 'Error for field 2 - Value: ' . $value );
			break;
	}
}

/**
 * Declare HPOS and Blocks compatibility
 */
add_action(
	'before_woocommerce_init',
	function () {
		if ( class_exists( '\Automattic\WooCommerce\Utilities\FeaturesUtil' ) ) {
			\Automattic\WooCommerce\Utilities\FeaturesUtil::declare_compatibility( 'custom_order_tables', __FILE__, true );
			\Automattic\WooCommerce\Utilities\FeaturesUtil::declare_compatibility( 'cart_checkout_blocks', __FILE__, true );
		}
	}
);
```

**Comment by senadir** [comment]
While I'm able to reproduce this on trunk, I'm unable to reproduce it on this branch https://github.com/woocommerce/woocommerce/pull/57965 so I'm assuming both got fixed.

**Comment by senadir** [comment]
Possibly due to wrapped/unwrapped bug.

**Comment by senadir** [comment]
Yeah confirmed, on trunk, this is fixed if I change the rules to:
```php
'hidden'            => array(
	'type'       => 'object',
	'properties' => array(
		'checkout' => array(
			'properties' => array(
				'additional_fields' => array(
					'properties' => array(
						$namespace . '/field_1' => array(
							'not' =>
								array( 'const' => 'show_field_2' ),
						),
					),
				),
			),
		),
	),
),
```

**Comment by webdados** [comment]
I've checked the last trunk (with #57965 merged already - confirmed by the fact complex hidden/required rules are working), and the validation for fields with hidden rules is still not working (plugin above).

<img width="1257" alt="Image" src="https://github.com/user-attachments/assets/153494e5-4456-48e1-8218-05dfb3f163c6" />

It is easily tested by looking at the error_log and you only get `test_custom_field_validation_validate_callback tcf/field_1` but never `test_custom_field_validation_validate_callback tcf/field_2`, even after that second field is visible by the fact `field_1 = show_field_2`

**Comment by webdados** [comment]
Any news on this? @senadir were you able to reproduce the problem with the latest trunk?
Would be great to have this fixed for 10.0

**Comment by senadir** [comment]
Yeah this should have been fixed with [Accept both wrapped and unwrapped JSON schema for additional fields #57965](https://github.com/woocommerce/woocommerce/pull/57965) and I confirmed that, let me know if you saw a regression

**Comment by webdados** [comment]
I think I did, yes. I activated the plugin above and the validation never runs for field_2. You're not able to reproduce it on your install now? The validation is running for field_2?

**Comment by webdados** [comment]
Additional information after some more tests.

On the [example above](https://github.com/woocommerce/woocommerce/issues/58488#issuecomment-2933731958), if I change the "hidden" conditional rules of field_2 to a core address field, it works.

In short, with this hidden rules, the validation runs whenever field_2 is visible:

```
'hidden'            => array(
	'customer' => array(
		'properties' => array(
			'shipping_address' => array(
				'properties' => array(
					'country' => array(
						'type' => 'string',
						'enum' => array( 'ES' ),
					),
				),
			),
		),
	),
),
```

With this hidden rules (based on another custom field), the validation never runs for field_2 (even if visible at the moment):

```
'hidden'            => array(
	'checkout' => array(
		'properties' => array(
			'additional_fields' => array(
				'properties' => array(
					$namespace . '/field_1' => array(
						'not' =>
							array( 'const' => 'show_field_2' ),
					),
				),
			),
		),
	),
),
```

**Comment by webdados** [comment]
As discussed with @senadir outside GH, this is still not fixed. I think the fix is #58992 - Can we expect this for 10.1?

**Comment by webdados** [comment]
I don't think this is fixed on 10.1.0-rc.1

`validate_callback` is never called for fields that are conditionally shown

**Comment by webdados** [comment]
I can confirm this is still not fixed on 10.1.1
