### ISSUE TITLE
Manage stock on variations not set using REST API

### ISSUE THREAD

**Issue by kallewallin** [woothemes/woocommerce#7561]
Version 2.2.10

We can't set the managing_stock flag on variations using the REST API

The following works on regular product

PUT wc-api/v2/products/[id]

{  
   "product":{  
      "stock_quantity":5,
      "managing_stock":true
   }
}

When we try the following:

PUT wc-api/v2/products/[id]

{  
   "product":{  
      "type":"variable",
      "variations":[  
         {  
            "id":"466",
            "stock_quantity":5,
            "managing_stock":true
         }
      ]
   }
}

managing_stock is not set to true on the variation. if we however manually set managing_stock from admin and run the same PUT request it works and stock_quantity is updated. The same thing goes for "managing_stock":false(works on product but not on variation)

**Comment by claudiosmweb** [comment]
Fixed in WooCommerce 2.3.5

**Comment by kallewallin** [comment]
We installed 2.3.5 and it still behaves the same.

I still can't change the managing_stock flag on variations, only products. Is this fix not out yet?

**Comment by claudiosmweb** [comment]
To be honest, just in master for now 0148a1bd86a2b6a3699ce5d12094451f62ff50ba

**Comment by kallewallin** [comment]
Thanks!
