### ISSUE TITLE
discount amount wrong in order and invoice with "including tax" setting 

### ISSUE THREAD

**Issue by wozo** [woothemes/woocommerce#7756]
The discount amount displayed in the coupon line seams to be wrong with the setting "Display Prices During Cart and Checkout: Including tax".

To reproduce the issue:

- In woocommerce "Tax" settings set 
  - Enable Taxes
  - "Prices Entered With Tax" to "Yes"
  - Display Prices in the Shop to "Including tax"
  - Display Prices During Cart and Checkout: to "Including tax".
  - Set standard tax rate to 20%
- Create a product  € 100.- (Taxable)
- Create a coupon for 100% cart discount 
- Buy the test product (apply the coupon)

alle prices are displayed correct 

eg. Cart Totals
Subtotal €100,00
Coupon: testcoupon -€100,00 
Total  €0,00 (Includes €0,00 VAT)

eg. Checkout
Testproduct: €100,00	
Subtotal: 	€100,00
Coupon: testcoupon -€100,00 
Total: €100,00 (Includes €16,67 VAT)

until the "order received" page
here the discount value is displayed not correct
(can't be higher than the product price inkl. tax)

Testproduct:	€100,00	
Subtotal: 	€100,00
Discount: 	-€116,67
Total: €0,00 (Includes €0,00 VAT)

also in the order e-mails and in the invoice the dicount is not displayed correct (Discount: 	-€116,67)

if you change the setting: 
Display Prices During Cart and Checkout: to "Excluding tax"
the prices are displayed different but correct

eg. Cart Totals
Subtotal 	€83,33
Coupon: testcoupon -€83,33
VAT: €0,00
Total: €0,00

eg. Checkout
Testproduct: €83,33	
Subtotal 	€83,33
Coupon: testcoupon -€83,33
VAT 	€0,00
Total €0,00

eg order received, mails or invoice:
Testproduct:	€83,33 (ex. VAT)	
Subtotal: 	€83,33 (ex. VAT)
Discount: 	-€100,00
VAT: 	€0,00
Total: €0,00

**Comment by mikejolley** [comment]
This is fixed in master and will be in 2.3.7

**Comment by wozo** [comment]
updated to 2.3.7
the discount amounts are correct now for existing users or guests (Discount: -€100)

when you create an account during checkout the problem still persists
wrong discount amount displayed (Discount: -€116,67) in order, order mails and invoice
