### ISSUE TITLE
PayPal Standard gateway is not logging debug information

### ISSUE THREAD

**Issue by dgwatkins** [woothemes/woocommerce#7801]
I expected to see information in the log about payment transactions, but this only happens when PayPal is in sandbox mode. This is in WC_Gateway_Paypal_Response::log()

I believe this is a bug: we should be checking if the log is enabled, not sandbox.

**Comment by roykho** [comment]
This was already fixed in the public release since 2.3.6

**Comment by dgwatkins** [comment]
For your info, I have 2.3.7 installed and its not fixed there.
But I saw its fixed in the master branch.

Thanks!

**Comment by roykho** [comment]
Strange, should be there as you can see here http://cld.wthms.co/106L7

**Comment by dgwatkins** [comment]
In 2.3.7 its checking for sandbox, so it only logs in sandbox mode
![screen shot 2015-04-07 at 12 00 58](https://cloud.githubusercontent.com/assets/17052/7021012/db4501d4-dd1d-11e4-931e-010243b6794f.png)

**Comment by claudiosmweb** [comment]
cc @mikejolley
